encode/httpx

- httpcore/config.py
- httpcore/connections.py
- httpcore/datastructures.py
- httpcore/pool.py
- setup.py
- tests/conftest.py
- tests/test_pool.py
Implements keep-alive and connection pooling.
Remaining tasks:
> Connection pooling

- httpcore/backends/default.py
Refs https://github.com/encode/httpcore/issues/16
> Graceful behavior for unclosed HTTPS connections

- httpcore/models.py
while investigating this https://github.com/huge-success/sanic/issues/1569, i found most of the increased build time has been spent on str/bytes concatenation (https://github.com/encode/httpcore/blob/master/httpcore/models.py#L675) with 100% cpu bounded.
FYI: those tests (https://github.com/huge-success/sanic/blob/master/tests/test_request_stream.py#L8) are the root cause of longer time build.
and they become pretty fast after this patch.
> optimize str bytes concatenation

- requirements.txt
- tests/conftest.py
- tests/dispatch/test_connections.py
Add `https_server` test fixture.
The self-signed certificate was created using [these steps](https://devcenter.heroku.com/articles/ssl-certificate-self).
> Add test to https server

- httpcore/__init__.py
- httpcore/client.py
- httpcore/concurrency.py
- httpcore/dispatch/connection.py
- httpcore/dispatch/connection_pool.py
- httpcore/interfaces.py
- tests/conftest.py
- tests/dispatch/test_http2.py
- tests/dispatch/utils.py
The low-level "make an outbound connection, and return a pair of streams" is now wrapped up in a `ConcurrencyBackend` interface. I think this *should* allow us to add trio support fairly easily if we want it.
Also it'll make it much easier for us to fully test out the HTTP handling without *neccessarily* needing to spin up a server to test against, since we can inject a backend that presents the stream interfaces without actually connecting to the network.
> Add `ConcurrencyBackend` interface

- httpcore/dispatch/http11.py
> Drop unreachable except block

- httpcore/__init__.py
- tests/test_timeouts.py
> Add test for write timeout error

- httpcore/__init__.py
- httpcore/api.py
- httpcore/client.py
- httpcore/concurrency.py
- httpcore/config.py
- httpcore/dispatch/connection.py
- httpcore/dispatch/connection_pool.py
- httpcore/dispatch/http11.py
- httpcore/dispatch/http2.py
- httpcore/interfaces.py
- tests/client/test_auth.py
- tests/client/test_cookies.py
- tests/client/test_redirects.py
- tests/dispatch/test_connections.py
- tests/test_config.py
We use `SSLConfig` and `TimeoutConfig` under the hood to wrap up all the SSL and timeout configuration. However the *user facing* arguments for `timeout`, `verify`, and `cert` should match up with how `requests` expects them.
> Work on bringing API into parity with `requests`.

- httpcore/dispatch/http2.py
Refs #80
This deals with a couple of apparent issues on the HTTP/2 implementation.
* acknowledge handled data to the connection, so that it doesn't get blocked.
* handle `StreamReset`.
`www.google.com` is still responding with a 400 protocol error after these changes, but it's an improvement.
> Handle StreamReset, and acknowledge received data

- httpcore/dispatch/http11.py
- httpcore/models.py
- tests/models/test_requests.py
Don't setup a 'Host' header automatically under `prepare_request`.
Only send the header with HTTP/1.1
Closes #80
> Drop Host header for HTTP/2

- http3/__init__.py
- http3/client.py
- http3/models.py
- tests/client/test_client.py
Allows the usage of eg. `client = Client(base_url="https://www.example.com")`
This is particularly useful when used as a test client, so eg.
```python
client = Client(app=app, base_url="https://testserver")
r = client.get('/')
```
If the test client is setup in fixtures, then test cases can just use relative URLs everywhere for testing the application.
> Add `base_url` support.

- http3/__init__.py
- http3/config.py
Closes https://github.com/encode/requests-async/issues/57
> Use urllib3's DEFAULT_CIPHERS for ssl config

- http3/client.py
- http3/concurrency.py
- http3/dispatch/connection.py
- http3/dispatch/http11.py
- http3/dispatch/http2.py
- http3/interfaces.py
- tests/client/test_client.py
- tests/dispatch/utils.py
We're need to handle early connection closes properly.
* Client sends the initial part of the request.
* Server responds and closes the connection.
* Client attempts to keep sending the remainder of the request body, but the connection is closed.
We need to branch our flow control, so that sending the request body and reading the response are run in seperate flows of control.
Closes #95
Closes #96
> Handle early connection closes

- http3/client.py
- http3/decoders.py
- http3/dispatch/asgi.py
- http3/dispatch/http11.py
- http3/dispatch/http2.py
- http3/dispatch/wsgi.py
- http3/models.py
- http3/multipart.py
* Include `Host` header when the request is instantiated. Ensures that it is incuded when making ASGI/WSGI requests.
* Add `raise_app_exceptions=False` API for WSGI/ASGI client, in order to inspect raw 500 responses.
* Don't incorrect quote multipart data.
* Allow str type in `data=...`.
* Tweak decoder header ordering.
> Include host header directly

- http3/__init__.py
- http3/__version__.py
- http3/client.py
- http3/config.py
- http3/models.py
- scripts/publish
- tests/models/test_requests.py
- tests/test_api.py
* Improve "User-Agent" header.
* Add "Connection: Keep-Alive" by default. Not required since it's the default for HTTP/1.1 anyways, but better to keep in line with requests' behavior.
* Expose USER_AGENT and types to package imports.
* Allow `URL` to accept any schemes - only error on non-HTTP at the point of `Client.send`.
> Minor tweaks in line with requests behavior

- http3/models.py
- http3/utils.py
- tests/models/test_responses.py
- tests/test_utils.py
Fixes #74
This PR replicates requests's logic where we typically use `response.text` and it's encoding detection via headers. In cases where it's not available [a helper function](https://github.com/kennethreitz/requests/blob/master/requests/utils.py#L851-L886) is used to detect possible UTF encodings which I ~shamelessly~ humbly copied over along with its tests (many thanks to the requests team for the complete coverage).
> Encoding detection in Response.json

- http3/config.py
- requirements.txt
- tests/conftest.py
- tests/test_config.py
Regarding disabling commonName: commonName support has been deprecated in urllib3 for over 5 years now and Chrome and Firefox don't support commonName for new certificates I think it's time we turn it off where we can (Python 3.7+ and OpenSSL 1.1.0+).
> Support client cert passwords, new TLS options

- httpx/status_codes.py
The status codes 418 and 451 are defined in RFCs 2324 and 7725, and are both fun and practical. I've used 418 as a testing status during development, and 451 is a reasonable inclusion given GDPR and other privacy and legal-related reasons content may be unavailable.
For reference, [Golang][1] and [Symphony][2] implement both, and other languages and frameworks such as [Ruby][3] and [Starlette][4] implement at least one (451).
Both are also documented in the [MDN developer docs][5], so may I should make a PR to Starlette next to add support for 418. :smiley: 
[1]: https://golang.org/src/net/http/status.go
[2]: https://github.com/symfony/symfony/blob/master/src/Symfony/Component/HttpFoundation/Response.php
[3]: https://ruby-doc.org/stdlib-2.6.3/libdoc/net/http/rdoc/Net/HTTP.html#class-Net::H …
> Additional HTTP Status Codes 418, 451

- httpx/models.py
- tests/models/test_url.py
Resolves #113
This turned out to be super easy, as casting a `str` to a `str` is idempotent, so adding `str` to the isinstance check allows it to pass equality checks with `str`s.
> Allow string comparison for URL().__eq__

- httpx/concurrency.py
- httpx/dispatch/connection.py
- httpx/dispatch/connection_pool.py
- httpx/dispatch/http11.py
- httpx/dispatch/http2.py
- httpx/exceptions.py
- httpx/interfaces.py
- tests/dispatch/test_connection_pools.py
- tests/dispatch/test_http2.py
- tests/dispatch/utils.py
- tests/test_multipart.py
Check for connection aliveness on re-acquiry from connection pool.
Superseeds #143
Great work on this @yeraydiazdiaz! There was a last little bit of extra cleanup on the connection pool handling that we can do now, which it made sense for me to pick up. I think we're good to go on this one now.
> Check disconnections on connection reacquiry

- httpx/models.py
- tests/models/test_url.py
We were calling `.normalize` on relative URLs, which was dropping out relative leading path portions. (So eg. `../foo` was being treated as `/foo`.)
Closes #142
Refs #138
> Fix `URL.join(...)`

- httpx/config.py
So I just added the two deprecated version to the SSL context, As we support python 3.6 this should be good but this way of building the sslContext seems to be deprecated in 3.7
https://docs.python.org/3/library/ssl.html#ssl.OP_NO_TLSv1
https://docs.python.org/3/library/ssl.html#ssl.SSLContext.minimum_version
> Removed deprecated TLS versions

- httpx/models.py
- requirements.txt
- setup.py
- tests/models/test_url.py
This does the switch on the URL level as a part of normalization. Adds a new dependency that is under my control currently and potentially will be under the python-http org.
> Switch hosts in HSTS preload list to HTTPS

- docs/api.md
- httpx/client.py
- httpx/models.py
- tests/client/test_headers.py
This PR resolves #149, by adding `headers` as an arg to the `BaseClient` class, as with `cookies`, and also adds a `merge_headers` function to... merge the headers. I started by copying `merge_cookies`, but got a `NoneType is not iterable` error when trying to use it, so I changed the conditional to ensure that both the passed `headers` and `self.headers` were set, and returning one or the other in the case that they are not. This will still return `None` if neither are set.
I haven't added test cases, yet, but I did test against httpbin.org. I could check out adding something based on the existing [cookie tests](https://github.com/encode/httpx/blob/master/tests/client/test_cookies.py), but wanted to get some feedback first.
```
Python 3.7.3 (default, Jun 24 2019, 04:54:02) 
Type …
```
> Add headers to BaseClient

- docs/api.md
- httpx/dispatch/connection_pool.py
- httpx/models.py
Resolves #165
Adds `.scheme` from `URL` to `Origin` for comparison purposes, keeps `.is_ssl` for use in https://github.com/encode/httpx/blob/master/httpx/dispatch/connection.py#L69
Adjusts `ConnectionStore` typing to use py3.5+ format.
> Make Origin use scheme, not is_ssl

- httpx/multipart.py
- tests/test_multipart.py
This resolves #164. Fixed using non-ASCII letters in `multipart/form-data` request.
> Fixed multipart header params encoding

- httpx/models.py
Drops `rfc3986.uri.URIReference` from being referenced in any public interface.
In fact it *wasn't* actually included in `URLTypes` in the first place.
Our `copy_with` and `join` will be less efficient - but if we want to resolve that we should do it in a different way, rather than exposing implementation-level types in our public interface.
> Remove 'URIReference' from public interfaces

- httpx/models.py
- httpx/utils.py
- tests/models/test_queryparams.py
Allow primitive data types for query params.
Closes #154
> Tweak query param types

- httpx/models.py
- tests/models/test_url.py
Resolves #150 and adds tests based on deviations from 2003 spec: https://unicode.org/reports/tr46/#Deviations
This also enables Unicode® Technical Standard #46 to normalize capital letters and such, and a test based on the example given in the [module documentation](https://github.com/kjd/idna#compatibility-mapping-uts-46).
Since the idna encode() function chokes on colons, I've split and rejoined the authority string and added to the tests to make sure the port stays as expected.
> Update IDNA encoding to 2008 spec

- httpx/client.py
- httpx/models.py
- tests/client/test_client.py
- tests/models/test_url.py
> Move HSTS preload checking to client

- httpx/client.py
- httpx/concurrency.py
- httpx/dispatch/http11.py
- httpx/dispatch/http2.py
- httpx/exceptions.py
- httpx/interfaces.py
- httpx/models.py
- tests/client/test_async_client.py
- tests/client/test_client.py
- tests/dispatch/utils.py
I created a HttpxError as base class for other Httpx exception. And added request for exception happening during the "send" (e.g. ConnectTimeout, ReadTimeout) and response for raise_for_status and errors linked to "too many redirect" (which should be close to the requests API). 
Things that may need attention:
- As the request/response object is separated from the IO, I catch HttpxError during sending in BaseClient and re-raise with the extra request info
- For the tests I added an extra check in methods test_raise_for_status but didn't find tests for redirect or tests mocking network failures, is it by design or still to be added ? 
Closes #141
> Added base class HttpxError with request/response attribute

- httpx/utils.py
> added `~/.netrc` and `~/_netrc` files for netrc path

- setup.py
Adds the `py.typed` marker file and `package_data` entry from PEP 561 (fixes #193). 
Tested locally with `pip install --editable .`.
> Enable mypy to discover type hints as specified in PEP 561

- httpx/models.py
- tests/test_decoders.py
This is my proposed fix for #195 
It just discards invalid header values for Content-Encoding
> Fail silently if invalid Content-Encoding is sent

- httpx/config.py
- httpx/multipart.py
- httpx/utils.py
- setup.py
- tests/test_config.py
Since httpx targets Python 3.6+, I figured it would be good to use the `pathlib.Path` object functions rather than `os.path.*`, for a slightly better interface.
> Use pathlib.Path instead of os.path functions

- tests/test_decoders.py
This fixes a test broken by a fixup commit in https://github.com/encode/httpx/pull/196.
> Fix invalid content test

- httpx/__init__.py
- httpx/client.py
- httpx/exceptions.py
- httpx/models.py
- tests/client/test_headers.py
- tests/client/test_redirects.py
> Remove "host" header on redirects if URL origin has changed

- .isort.cfg
- noxfile.py
- setup.cfg
This centralizes all the tooling configurations that will be used by
flake8, mypy, isort, pytest, and coverage tools.
It prevents the config file bloating at the project and also makes the
editor linters to automatic detects the project coding standards.
It also removes the .isort.cfg file and the configurations hardcoded at
the noxfile to prevent duplication.
> Centralize tooling configuration

- tests/client/test_redirects.py
The `response.is_redirect` is already implicitly tested to be _True_ in the other test case that disallows redirects (https://github.com/encode/httpx/blob/master/tests/client/test_redirects.py#L220) but I thought it would be good to have it explicit in the first simpler test case.
> Expand disallow_redirects test assert

- httpx/config.py
- httpx/dispatch/connection.py
- tests/test_config.py
> Removed asyncio usage within SSLConfig

- httpx/config.py
- tests/test_config.py
Fixes #166. Allows users to configure an `SSLConfig` instance by passing in an `SSLContext` object that they've loaded CA certs, ciphers, etc onto.
> Accept SSLContext into SSLConfig(verify=...)

- noxfile.py
> Added diff flag to black for improved CI lint error digging

- httpx/concurrency.py
- httpx/interfaces.py
- httpx/status_codes.py
- tests/dispatch/test_connection_pools.py
- tests/test_api.py
I have fixed some of the typos inside the docstrings, that I found while reading through the source code. 
Also, I changed the comparator inside the `StatusCode` to use chained comparators (suggested by Pycharm), which I can drop it, to only make the PR about typos. :grinning:
> Fix typos in docstrings

- httpx/api.py
- httpx/client.py
- tests/client/test_auth.py
> added trust_env attribute on the client instance

- .travis.yml
- httpx/config.py
- httpx/dispatch/http11.py
This is a work-around for this bug: nedbat/coveragepy#772 which makes `break` statements not show up in the opcodes if they immediately precede a `return` statement due to peep-hole optimizations. This allows us to say we want 3.8 to always pass on CI. :)
Maybe in the future we should rely on Codecov to aggregate our code coverage so we don't need to do this but that has it's own set of issues.
> Skip coverage on breaks right before returns for Python 3.8

- CHANGELOG.md
- setup.py
This adopts the style of urllib3 for a changelog. I stopped at 0.6.x as the releases before had mostly a single minor change and a release. If we want to trim it earlier we can as well.
> Add CHANGELOG.md for tracking releases

- test-requirements.txt
`setup.py` already defines the base requirements for `httpx`,  so we can install the package itself for development instead of re-listing those requirements in `test-requirements.txt`. :-)
> Install package locally in test-requirements.txt

- httpx/client.py
- tests/client/test_client.py
As suggested in #214 (https://github.com/encode/httpx/pull/214#issuecomment-522241493).
We still need the `backend` argument on `Client` for some of the tests (e.g. the HTTP2 mock backend in `test_http2.py`), so I figured a simple inheritance check would be enough, esp. since the `backend` argument is not documented.
> Enforce that sync client uses asyncio-based backend

- docs/advanced.md
- httpx/client.py
- httpx/dispatch/asgi.py
- httpx/dispatch/wsgi.py
Removes the undocumented `raise_app_exceptions` keyword argument on the client instance, in favour of forcing explicit `WSGIDispatch` or `ASGIDispatch` for any non-default instantiations.
Adds some better documentation around fine-grained WSGI/ASGI control.
> Drop `raise_app_exceptions` Client argument.

- httpx/models.py
- tests/client/test_auth.py
> fixed __repr__ function of Headers and Url classes to not show auth info explicitly.

- httpx/__init__.py
- httpx/client.py
- httpx/concurrency/asyncio.py
- httpx/dispatch/connection.py
- httpx/dispatch/connection_pool.py
- httpx/dispatch/http11.py
- httpx/dispatch/http2.py
Fixes #245 
Breaking things up from #217 for ease of review, this turns `concurrency.py` into a `concurrency` package.
Splitting `interfaces.py` into `concurrency/interfaces.py` will be tackled in a future PR.
> Turn concurrency.py into its own sub-package

- httpx/concurrency/asyncio.py
- httpx/dispatch/asgi.py
- httpx/interfaces.py
Adds a queue interface abstracting away specifics from `asyncio.Queue`, used inside `BodyIterator`.
Refs #247
> Add BaseQueue interface

- httpx/config.py
- tests/test_config.py
> added test for HTTPVersionConfig type error

- httpx/concurrency/asyncio.py
- httpx/concurrency/base.py
- httpx/dispatch/asgi.py
Add a `BaseEvent` interface to abstract away `asyncio.Event()`, esp. in `ASGIDispatch`.
Refs #247
> Add BaseEvent interface

- httpx/__init__.py
- httpx/concurrency/asyncio.py
- httpx/concurrency/base.py
- httpx/dispatch/connection.py
- httpx/dispatch/http11.py
- httpx/dispatch/http2.py
- tests/dispatch/utils.py
Based on a suggestion from @tomchristie in https://github.com/encode/httpx/pull/217#issuecomment-522571545, simplifies the stream interface by merging `BaseReader` and `BaseWriter` into a unified stream interface.
> Unify BaseReader and BaseWriter as BaseStream

- httpx/concurrency/asyncio.py
- httpx/concurrency/base.py
- httpx/dispatch/asgi.py
- httpx/dispatch/http11.py
- httpx/dispatch/http2.py
Refs #247 
Getting close :tada:
> Remove usage of loop.create_task in ASGIDispatch

- .travis.yml
See https://blog.travis-ci.com/2018-11-19-required-linux-infrastructure-migration
> Travis CI: sudo no longer required

- httpx/dispatch/asgi.py
> Add backend param to ASGIDispatcher

- .travis.yml
- codecov.yml
- setup.cfg
As can be seen in #263 we can't have all code be covered by Python 3.6 and I don't want to mark that large chunk of code as `no cover`.
> Rely on codecov for 100% project coverage

- tests/dispatch/test_http2.py
- tests/dispatch/test_threaded.py
- tests/test_asgi.py
There were a few test cases that didn't have an async equivalent, so I added those (mostly by copy-paste-asyncify-ing, but I think it ends up being fine from a maintainability perspective).
Besides expanding functional coverage, these will be useful to test alternative backends that can't shouldn't be with the sync `Client`. For example, this will allow us to test HTTP/2 with the trio backend.
> Add missing async test cases

- httpx/concurrency/asyncio.py
- httpx/concurrency/base.py
- httpx/dispatch/asgi.py
- httpx/dispatch/connection.py
- httpx/dispatch/connection_pool.py
- httpx/dispatch/threaded.py
- httpx/dispatch/wsgi.py
- tests/test_concurrency.py
This primitive will be used for HTTP CONNECT tunnel proxies to apply TLS onto either a raw socket stream or an existing TLS stream.
> Add ConcurrencyBackend.start_tls()

- httpx/client.py
- tests/client/test_async_client.py
- tests/client/test_redirects.py
- tests/concurrency.py
- tests/conftest.py
- tests/dispatch/test_connection_pools.py
- tests/dispatch/test_connections.py
- tests/dispatch/test_http2.py
- tests/dispatch/test_threaded.py
- tests/dispatch/utils.py
- tests/test_asgi.py
- tests/test_timeouts.py
Fixes #271 
Mostly adds a `backend` fixture and use it in the relevant tests, and some refactoring of HTTP/2 and connection pool tests to be more backend-agnostic as well.
I'm thinking that now we don't really test the usual path (e.g. not passing a `backend` to `AsyncClient`). This can be easily fixed by adding `None` as an extra backend to make `AsyncClient` & others use their default backend. This increases the duration of the test suite though (~20%?), so… any thoughts?
> Parametrize tests with concurrency backend

- httpx/concurrency/asyncio.py
- tests/client/test_client.py
- tests/conftest.py
- tests/dispatch/test_connection_pools.py
- tests/dispatch/test_connections.py
- tests/test_api.py
- tests/test_concurrency.py
Following https://github.com/encode/httpx/pull/276#issuecomment-525709778 cc @tomchristie
> Serve test server in thread

- tests/conftest.py
We've got lots of tests for environment variable features and it'd be good if we didn't have to worry about setting something in one test and it affecting a different test.
> Add fixture for ensuring os.environ is not persisted past a test

- httpx/middleware.py
- httpx/models.py
NOTE:
__setitem__ in class Headers already encodes with its encoding attribute
Added check to skip encoding the value if it is already bytes.
Closes #318
> Setting HOST header to url.authority.encode('ascii') in redirect middleware

- .gitignore
- test-requirements.txt
Refs https://github.com/MagicStack/uvloop/issues/266, and prompted by https://github.com/encode/httpx/pull/153 and https://github.com/encode/httpx/pull/276#issuecomment-528998323.
Opening this mostly to see if this fixes the build. We don't know how long the issue may stay though, so perhaps we could consider keeping this until things are sorted out?
(Also, this is probably affecting uvicorn as well.)
> Pin uvloop<0.13 to fix 3.8-dev build

- httpx/client.py
- httpx/middleware/base.py
- httpx/middleware/basic_auth.py
- httpx/middleware/custom_auth.py
- httpx/middleware/redirect.py
- httpx/utils.py
Prompted by https://github.com/encode/httpx/pull/305#issuecomment-529144881
Moves the existing middleware in `middleware.py` into their own module in a `middleware` package.
Next up, a basic auth refactor including:
- Add and use `to_bytes()`
- Extract a reusable `build_basic_auth_header()` helper.
> Refactor middleware

- docs/advanced.md
- docs/api.md
- httpx/client.py
- tests/client/test_async_client.py
- tests/client/test_client.py
- tests/conftest.py
Using a Client instance to make build requests
```python
>>> client = httpx.Client()
>>> r = client.build_request("GET", "https://example.com")
>>> r
<AsyncRequest('GET', 'https://example.com')>
>>> client.send(r)
<Response [200 OK]>
```
And async client
```python
>>> client = httpx.AsyncClient()
>>> r = client.build_request("GET", "https://example.com")
>>> r
<AsyncRequest('GET', 'https://example.com')>
>>> client.send(r)
<coroutine object AsyncClient.send at 0x7fbc588f7560>
```
Closes #174
> Add `build_request` for `Client`

- httpx/__init__.py
- httpx/client.py
- httpx/middleware/digest_auth.py
- httpx/models.py
- httpx/utils.py
- tests/client/test_auth.py
Split from https://github.com/encode/httpx/pull/305
This PR introduces a `DigestAuth` middleware that can be used as an `auth` parameter to `Client` and the request methods.
This works for the synchronous Client situations, for example:
```python
import httpx
URL = "https://httpbin.org/digest-auth/auth/yeray/{password}/{algorithm}"
ALGORITHMS = [
"MD5",
"MD5-SESS",
"SHA",
"SHA-SESS",
"SHA-256",
"SHA-256-SESS",
"SHA-512",
"SHA-512-SESS",
]
def main():
password = "foo"
with httpx.Client(auth=httpx.DigestAuth("yeray", password)) as client:
for algorithm in ALGORITHMS:
response = client.get(URL.format(password=password, algorithm=algorithm))
print("FAILED!" if response.status_code != 200 else "", algorithm, response)
print("\nThis should fail...")
print(client.get(URL.format(password="bar", …
```
> DigestAuth as middleware - No nonce count

- httpx/__init__.py
- httpx/concurrency/asyncio.py
- httpx/concurrency/base.py
- httpx/dispatch/connection.py
- httpx/dispatch/http11.py
- httpx/dispatch/http2.py
- tests/dispatch/utils.py
- tests/test_concurrency.py
Prompted by https://github.com/encode/httpx/issues/275#issuecomment-531349234, this is a probably valuable refactoring anyway and a good first step towards UDP support.
> Rename Stream to TCPStream

- setup.py
Fixes #193
I realized `zip_safe=False` was missing by [comparing with Starlette](https://github.com/encode/starlette/blob/master/setup.py). Upon more research, it seems this is actually a [mypy/setuptools requirement](https://mypy.readthedocs.io/en/latest/installed_packages.html#making-pep-561-compatible-packages).
My QA process:
```bash
python -m venv venv
. venv/bin/activate
pip install /path/to/httpx
ls venv/lib/python3.7/site-packages/httpx | grep py.typed
```
> Fix missing py.typed file

- httpx/client.py
- httpx/concurrency/asyncio.py
- httpx/concurrency/base.py
- httpx/concurrency/trio.py
- httpx/dispatch/asgi.py
- httpx/dispatch/http2.py
- setup.cfg
- setup.py
- test-requirements.txt
- tests/concurrency.py
- tests/conftest.py
- tests/dispatch/test_connection_pools.py
- tests/test_timeouts.py
Fixes #120 
**Current status**: we're blocked by the connection pool implicitly relying on asyncio polling sockets in the background to tell if they're still readable. See discussion around https://github.com/encode/httpx/pull/276#discussion_r322002604.
Most of the notes below are outdated.
---
Getting the tests to pass on this one ended up having to tackle more tricky issues than I initially thought. (There's still `start_tls()` to figure out, but that will be for a future PR.)
So, a few notes, from the most straight-forward to the most obscure:
- I took the liberty to refactor `HTTP2Dispatcher.initiate_connection()` into an async function; it allowed to remove the need for `write_no_block()` on the concurrency backend (which trio does not have an obvious equivalent for). Things seem to …
> Add trio concurrency backend

- httpx/dispatch/http2.py
- tests/dispatch/test_http2.py
- tests/dispatch/utils.py
Some servers that are high on the Alexa 1M don't follow RFCs and ignore unknown settings. Since we don't benefit from this setting we should stop sending it.
This is only part 1 of #236
> Remove ENABLE_CONNECT_PROTOCOL from HTTP/2 Settings

- httpx/config.py
`f` prefix only affect the following string.
```Python
var = 0
string1 = (
f"test "
"{var}"
)
string2 = (
"test "
f"{var}"
)
assert string1 == "test {var}"
assert string2 == "test 0"
```
> fix invalid f-string

- httpx/dispatch/asgi.py
- httpx/models.py
- httpx/utils.py
- tests/models/test_headers.py
- tests/test_utils.py
Working on and debugging #352, I noticed we didn't have debug logs for the `ASGIDispatch`, so here they are. :)
Example output:
```python
import httpx
async def app(scope, receive, send):
assert scope["type"] == "http"
await send(
{
"type": "http.response.start",
"status": 200,
"headers": [[b"content-type", b"text/plain"]],
}
)
await send({"type": "http.response.body", "body": b"Hello, world!"})
with httpx.Client(app=app) as client:
r = client.get("http://app")
print(r)
```
```console
20:18:22.096 - httpx.dispatch.asgi - started
20:18:22.096 - httpx.dispatch.asgi - received message={'type': 'http.response.start', 'status': 200, 'headers': '<...>'}
20:18:22.096 - httpx.dispatch.asgi - received message={'type': 'http.response.body', 'body': '<13 bytes>'}
20:18:22.097 - httpx.dispatch.asgi - …
```
> Add debug logs to ASGIDispatch

- noxfile.py
So that it is checked during CI. Currently it is only run in the lint session which is not run during CI.
> Run isort in the nox check session

- httpx/concurrency/asyncio.py
- tests/test_timeouts.py
> Fix bug when using client without timeouts under 3.6

- httpx/client.py
- httpx/dispatch/proxy_http.py
- tests/client/test_proxies.py
Proxies aren't being constructed in the same way as the primary dispatcher for the Client so end up with defaults for `verify`, etc causing certificates outside of the certifi bundle to fail even when specified via `verify`.
I removed the `proxies` parameter for individual requests as it's broken in the same way but this PR doesn't provide a fix. That work can be done in a separate PR?
Closes #376.
> Propogate Client config to HTTPProxy

- docs/async.md
Following the addition of trio support via #276.
> Document supported async libraries

- docs/advanced.md
- httpx/__init__.py
- httpx/dispatch/__init__.py
Resolves #398
`ASGIDispatch` and `WSGIDispatch` were added to `dispatch` namespace first, then imported from there in the top-level package.
This way they're available at both `httpx.ASGIDispatch` and `httpx.dispatch.ASGIDispatch` which might be handy.
> Expose ASGIDispatch & WSGIDispatch in the 'dispatch' namespace.

- setup.py
This should help to discover httpx from PyPI. We can always remove the Trio framework when moving its support to a third-party package.
> setup.py: add AsyncIO and Trio frameworks

- httpx/client.py
- noxfile.py
- test-requirements.txt
- tests/dispatch/test_proxy_http.py
As mentioned in https://github.com/encode/httpx/pull/375#issuecomment-534197215, this adds `flake8-pie` as a dependency which adds a few checks, two of which are triggered in the current codebase:
- PIE781: You are assigning to a variable and then returning. Instead remove the assignment and return.
- PIE782: Unnecessary f-string. You can safely remove the f prefix.
The following lint messages were fixed after adding the requirement (found with `nox -s check`):
```
nox > flake8 httpx tools tests setup.py noxfile.py
httpx/client.py:338:9: PIE781: You are assigning to a variable and then returning. Instead remove the assignment and return.
httpx/client.py:731:9: PIE781: You are assigning to a variable and then returning. Instead remove the assignment and return. …
```
> Add flake8 pie plugin

- .travis.yml
Taken from [this comment](https://github.com/encode/httpx/pull/423#issuecomment-537455052).
Until we get a stable 3.8 release we'll say passing 3.8 is optional.
> Skip Python 3.8-dev builds on Travis

- README.md
- docs/advanced.md
- docs/compatibility.md
- docs/contributing.md
- docs/index.md
- docs/parallel.md
- docs/quickstart.md
This PR fixes a variety of spelling mistakes and grammar issues across the documentation. Hopefully, this helps you all out, keep up the great work!
> Fix typos, spelling issues, and grammar in docs

- scripts/publish
- setup.cfg
- test-requirements.txt
Closes #432
For now both sdist and wheel are built and uploaded, but as @graingert commented https://github.com/encode/httpx/issues/432#issuecomment-537913387 I can drop the sdist if you want.
Tested locally and the wheel is built correctly, the only step I could not test is the upload with twine to PyPI.
> Build and upload wheels to PyPI

- docs/compatibility.md
Add compatibility differences with get, delete, head, and options.  
Relevant discussion: #395
> Add compatibility differences with get, delete, head, options

- docs/api.md
Added missing files parameter for `post()`, `patch()` and `put()` helper functions
and for Client's `.post()`, `.patch()`, and `.put()` methods in docs. #409
> Add missing files parameter on .post(), .patch(), and .put() (#409)

- docs/async.md
Current page 404s since the href is incorrect.
https://www.encode.io/httpx/async/ contains a link to 'paralell requests' that points to https://www.encode.io/parallel/
> Fix link to parallel page from async page

- httpx/models.py
- tests/models/test_url.py
Closes: #437 
As mentioned in #417 from now on we can copy `username`,  `password`, `host`, `port` and create a new URL from old url instance. After merging this PR, we can apply this to the source PR.
> added authority copy feature in URL.copy_with

- MANIFEST.in
Fixes: #193 
Using `include_package_data=True` in the call to `setuptools.setup` means that the `package_data={'httpx': 'py.typed'}` is ignored when packaging to source because the referenced file isn't in `MANIFEST.in` (see https://setuptools.readthedocs.io/en/latest/setuptools.html#including-data-files). This PR adds `httpx/py.typed` to `MANIFEST.in`. 
Tested by running `python3 setup.py sdist bdist_wheel` then installing from the generated tarball:
```
$ python3 setup.py sdist bdist_wheel
running sdist
running egg_info
creating httpx.egg-info
writing httpx.egg-info/PKG-INFO
writing dependency_links to httpx.egg-info/dependency_links.txt
writing requirements to httpx.egg-info/requires.txt
writing top-level names to httpx.egg-info/top_level.txt
writing manifest file …
```
> Ensure py.typed makes it into source distributions.

- tests/client/test_client.py
These test were spurriously failing on my machine, e.g. giving "0.063" which failed 0.05 ± 0.01.
I tweaked them so that repeating the tests 30 times does not fail:
```console
$ pip install pytest-repeat
$ pytest --count=30 -k test_elapsed_delay
```
> Fix flaky elapsed delay test

- scripts/publish
- test-requirements.txt
As [discussed here](https://github.com/encode/httpx/pull/439#discussion_r331390607) removed `wheel` package from `test-requirements.txt` and moved the check in `./scripts/publish`.
> Remove wheels package from test-requirements.txt

- tests/conftest.py
Small refactoring based on the observation that trio is always installed during tests.
> Don't check trio import in definition of backend fixture params

- httpx/models.py
- httpx/utils.py
- tests/models/test_queryparams.py
Fixes #366 
Re-running the example from https://github.com/encode/httpx/issues/366#issuecomment-533786466:
```python
import httpx
import requests
URL = "https://httpbin.org/get"
PARAMS = {"documentIds": ["a55b2f894b90dd1213201471_25", "b54b2f894b90dd1213201471_9"]}
resp = requests.get(URL, params=PARAMS)
print("requests", resp.json()["args"])
r = httpx.get(URL, params=PARAMS)
json = r.json()
assert isinstance(json, dict)
print("httpx", json["args"])
print("httpx", str(httpx.QueryParams(PARAMS)))
```
```console
requests {'documentIds': ['a55b2f894b90dd1213201471_25', 'b54b2f894b90dd1213201471_9']}
httpx {'documentIds': ['a55b2f894b90dd1213201471_25', 'b54b2f894b90dd1213201471_9']}
httpx documentIds=a55b2f894b90dd1213201471_25&documentIds=b54b2f894b90dd1213201471_9
```
> Allow lists in query params

- docs/contributing.md
- noxfile.py
Quick addition to our `nox` setup to allow serving docs using `nox` instead of having to install `mkdocs` and `mkdocs-material` locally.
(Not a fan of the snake_cased command name, but both "docs:watch" and "docs-watch" messed with the unselection of the task when running `$ nox`.)
(Edit: edited to `$ nox -s serve`.)
> Allow serving docs via nox

- httpx/utils.py
- tests/test_utils.py
1. Our `get_environment_proxies()` relies on the standard library function [urllib.request.getproxies_environment()](https://github.com/python/cpython/blob/f5ed41c1ae9a575e965d55c6a5e86fb59181eee8/Lib/urllib/request.py#L2456) to do the parsing work, which already prefers lower case envvars. So we only need to filter out protocols which we don't support.
2. As such, we only need to test if the filtering works as intended. (Resolves #456)
---
Additional thoughts:
1. I can't figure out the intention of `"://" in key`  in httpx/utils.py, L226. It looks unnecessary
2. [urllib.request.proxy_bypass](https://github.com/python/cpython/blob/f5ed41c1ae9a575e965d55c6a5e86fb59181eee8/Lib/urllib/request.py#L2737) looks like a robust implementation of 'NO_PROXY'。 #360
3. On Windows and macOS, …
> Remove redundant proxy settings

- docs/contributing.md
- scripts/test
Prompted by https://github.com/encode/httpx/pull/399#discussion_r329471921
Running
```bash
$ scripts/test
```
runs the test suite and runs the `check` session.
I made it so that the test suite only for the current Python version is run (e.g. 3.7), but we could also run `$ nox -s test` so that all available Python versions are tested (e.g. all of 3.6, 3.7 and 3.8 if they're detected as available by `nox`). This is mostly because running tests against all Python versions can get very long, esp. because virtualenvs aren't reused. Thoughts?
> Add test script

- docs/advanced.md
- docs/quickstart.md
Reference issue #434 
I've added a small intro to HTTPX timeouts, sections with examples (plain request, client, timeout config object) and a paragraph about disabling timeouts.
btw, I apologize for any grammar mistakes, English is my second language.
> Add timeout fine-tunning advanced docs section

- httpx/utils.py
- tests/test_utils.py
This PR implements logic requested in https://github.com/encode/httpx/pull/462#issuecomment-539971761
This method could be moved if utils is not a good place, maybe in HTTPProxy.
If you wanted something else, please let me know.
> should-b-proxied: logic whether url to be proxied

- docs/advanced.md
- docs/api.md
- docs/compatibility.md
- docs/environment_variables.md
- docs/parallel.md
Refs https://github.com/encode/httpx/issues/422#issuecomment-537906693, closes #422.
> Document client block-usage and close()

- httpx/concurrency/asyncio.py
- httpx/concurrency/base.py
- httpx/concurrency/trio.py
- httpx/dispatch/proxy_http.py
- tests/dispatch/utils.py
- tests/test_concurrency.py
Fixes Python 3.8.0 TLS issue (see second commit & #477)
I like this approach better than mutating the insides of a `TCPStream` when switching to TLS. Instead, a new `TCPStream` instance is returned. This pattern better matches the way Trio abstracts streams which also seems to be the way asyncio is headed for Python 3._next_.
Fixing the Python 3.8 issue does not require this refactor, but this makes the fix a lot cleaner.
> Proposal: Make start_tls a method on streams & return a new stream

- docs/advanced.md
- httpx/multipart.py
- tests/test_multipart.py
Fixes https://github.com/encode/httpx/issues/481
The tuple values of the `files` dictionary passed to `multipart_encode` now support:
- `None` filenames, the header will not include the `filename` section
- `str` objects as the contents, as opposed to file-like objects
I wasn't sure about adding docs about it as [requests seems to not include it](https://requests.readthedocs.io/en/master/user/advanced/#post-multiple-multipart-encoded-files) and it seemed more of an implementation detail that doesn't quite fit in the quickstart guide. But I'm happy to include it if we think it's worth it.
> Multipart files tweaks

- .travis.yml
Change python 3.8-dev to python 3.8 in Travis as python 3.8 is officially released
> Change python 3.8-dev to python 3.8 in travis

- httpx/concurrency/asyncio.py
- tests/test_concurrency.py
We discussed calling `wait_closed()` on the `StreamWriter` in #369, but never implemented it due to a transient issue with SSL connections ([comment](https://github.com/encode/httpx/pull/369#discussion_r327187795)).
I now better understand the issue and have written a [lengthy explanation](https://github.com/aio-libs/aiohttp/issues/3535#issuecomment-544279431) on the related aiohttp issue (since that seems to have the most visibility).
The error makes sense if you think about it, and it's clear why it was showing up in our test--because we weren't making sure we consumed the entire response before closing the connection.
I'm not sure if we need to handle this error--I think in most cases the entire response should be consumed before we close a stream. My thinking was we try this and see …
> asyncio: Wait for the stream to close when closing

- tests/test_config.py
Just a bit of moving timeout config tests around so they're all close to one another, and add one or two tests for the default cases. Would help reduce the scope of #490.
> Reorganize timeout config tests

- test-requirements.txt
uvloop has shipped a 0.14 release candidate which uvicorn now uses, so the temporary fix from #323 should not be necessary anymore.
> Remove pin on uvloop in test-requirements

- docs/environment_variables.md
- httpx/config.py
- httpx/dispatch/connection.py
- httpx/dispatch/connection_pool.py
- httpx/dispatch/http11.py
- httpx/dispatch/http2.py
- httpx/dispatch/proxy_http.py
- httpx/utils.py
- tests/test_utils.py
Refs #495 
This PR converts existing `DEBUG` logs to the `TRACE` level, and renames `HTTPX_DEBUG` to `HTTPX_LOG_LEVEL`.
Example in a Uvicorn setting:
```python
from starlette.applications import Starlette
from starlette.responses import JSONResponse
import httpx
app = Starlette()
client = httpx.AsyncClient()
app.add_event_handler("shutdown", client.close)
@app.route("/")
async def home(request):
resp = await client.get("https://httpbin.org/headers")
return JSONResponse(resp.json())
```
Still to do in future PRs:
- Add logging of requests into `DEBUG` log lines will be added in a subsequent PR.
- Colour logs based on the log-level (Uvicorn overrides this, but right now HTTPX does not do colouring on its own). Could take a similar approach to https://github.com/encode/databases/pull/156 …
> Convert debug logs to trace logs

- tests/test_utils.py
- tests/utils.py
Spun up from #502 to help reduce its scope - simplify how we test debug logs.
> Refactor debug and trace log tests

- docs/environment_variables.md
- httpx/client.py
- httpx/utils.py
- tests/conftest.py
- tests/test_utils.py
Fixes #495 
This PR is a follow-up for #500 which:
- Adds debug logs on each HTTP request. (@tomchristie I chose to issue logs from clients, instead of e.g. `ConnectionPool`, so that they get issued regardless of the dispatcher in use (e.g. `ConnectionPool` vs `ASGIDispatcher`).)
- Tweaks the general log format, which was e.g. missing the date and the log level name.
@tomchristie I noticed the date and logger name are missing in Uvicorn logs. Perhaps a good idea to add those there as well? In particular, not having the logger name makes the origin of logs unclear: do they come from Uvicorn, HTTPX, Databases…? See example here:
> Add debug logs

- docs/advanced.md
- httpx/api.py
- httpx/client.py
> Add docs on SSL certificates

- tests/dispatch/test_http2.py
Right now the `master` build is [failing](https://travis-ci.org/encode/httpx/builds/608437975) because the live HTTP/2 request made to nghttp2.org is timing out, probably because the website is suffering some issues right now.
This PR makes the test xfail on some predictable failure cases.
Note that the `socket.gaierror` block is not ideal — when resolving #349 we should switch to whichever HTTPX-native exception is introduced.
> Improve robustness of live HTTP/2 test

- httpx/__init__.py
- httpx/concurrency/asyncio.py
- httpx/concurrency/base.py
- httpx/concurrency/trio.py
- httpx/dispatch/http11.py
- httpx/dispatch/http2.py
- httpx/dispatch/proxy_http.py
- tests/dispatch/utils.py
This PR renames `BaseTCPStream`, backend subclasses `asyncio.TCPStream` and `trio.TCPStream`, to `BaseSocketStream` / `SocketStream`, to not limit name/usage to TCP specific streams.
Related to #511
> Rename TCPStream to SocketStream

- httpx/middleware/redirect.py
- noxfile.py
- test-requirements.txt
- tests/client/test_redirects.py
Cookies are not being properly handled by redirect responses.
(Specifically, expired cookies in a response, are still included in any redirect request)
> Fix redirect cookie behavior

- httpx/concurrency/asyncio.py
- tests/test_concurrency.py
This adds support for proxy tunnels for Python 3.6 + asyncio.
Based almost entirely on this comment: https://github.com/urllib3/urllib3/issues/1323#issuecomment-362494839 Massive thanks to @florimondmanca for finding this!
Closes #515.
> Backport start_tls() support for Python 3.6

- docs/compatibility.md
Adds a *mocking* section to the `Requests Compatibility Guide` in the docs, mentioning `respx` as an HTTPX alternative to `responses` and `requests-mock`.
> Document mocking compatibility

- CHANGELOG.md
- httpx/__version__.py
Figured 3.6 proxy tunnel support (ref #515) was important enough to be worth a release already. :-)
> Release 0.7.8

- httpx/client.py
- httpx/concurrency/asyncio.py
- httpx/concurrency/base.py
- httpx/concurrency/trio.py
- httpx/dispatch/connection.py
- httpx/dispatch/connection_pool.py
- tests/client/test_async_client.py
- tests/client/test_client.py
- tests/conftest.py
- tests/test_concurrency.py
This PR adds support for connecting through unix domain sockets.
New client argument `uds` is added to define unix domain socket path to use.
**Usage:**
```py
async with httpx.AsyncClient(uds="/var/run/docker.sock") as client:
r = await client.get("http://docker/version")
```
Solves previously discussed topic in #133
> Add support for unix domain sockets

- docs/advanced.md
This PR adds a `Unix Domain Sockets` section to the `Advanced Usage` page, describing the `uds` parameter.
> Document unix domain sockets

- docs/async.md
Fixes #179, refs (or fixes?) #508.
> Document when to use AsyncClient

- httpx/dispatch/http11.py
- httpx/exceptions.py
- tests/conftest.py
- tests/dispatch/test_connections.py
here is a proposed fix.  I wasn't too clear on the test suite (as usual :), but I was able to make a case that triggers the failure mode and test that the fix works as expected.
Addresses github issue #96
Fixes #96
> Handle h11.Connection.next_event() RemoteProtocolException

- httpx/concurrency/asyncio.py
- httpx/concurrency/trio.py
- tests/concurrency.py
- tests/test_concurrency.py
Fixes #527 
Turns out that the bug was also present on trio, so I added a fix and test for it too.
I'm not *sure* that we'd also need a lock around the asyncio write operation (we already have one on trio), but no bug was reported yet and we should probably investigate that separately anyway.
> Fix race condition on stream.read

- httpx/client.py
- httpx/utils.py
- tests/test_utils.py
I'm not wild about our `@functools.lru_cache(1)` on a method in the client.
I've refactored the netrc handling, in a way that I think is a little clearer about where we're holding onto state.
At the moment I've used `self.netrc = NetRCInfo()` on the client instance. We're looking up the netrc file on a per-client basis, and changes to the environment are reflected if you instantiate a new client.
If we really wanted we *could* potentially switch to a global `NETRC = NetRCInfo()` instead, and only ever make a single lookup, but I think scoping to the client is probably the sensible thing to do.
> Refactor netrc handling

- httpx/client.py
- tests/client/test_proxies.py
The `._dispatcher_for_request()` method should *really* be more tightly scoped as `dispatcher_for_url`. We also don't need to be passing the proxy configuration as an argument.
> Clean up '_dispatcher_for_request' into 'dispatcher_for_url'

- httpx/concurrency/base.py
Drop unneccessary `iterate_in_threadpool` and `iterate` from concurrency backends.
> Drop `iterate_in_threadpool` and `iterate`

- tests/test_concurrency.py
Cleanly separate TCP/UDS test cases — this should make skipping the UDS test case on Windows trivial (see https://github.com/encode/httpx/pull/566#issuecomment-559865587).
Also cleanup the atrocious `lambda`s I originally used in the `get_cipher` parametrization. 😄
> Refactor start_tls tests

- httpx/models.py
- tests/models/test_queryparams.py
Addresses: https://github.com/encode/httpx/issues/546
Attempting to address the issue, whilst keeping the element of surprise low for existing use cases.
> Preserve list type query paramaters when merging QueryParams objects

- docs/compatibility.md
- httpx/models.py
- httpx/status_codes.py
- tests/models/test_responses.py
Adds a `response.is_error` property, which closes #543
Our section in the requests compat docs details httpx's usage of `response.is_error` vs. requests' usage of `response.is_ok`...
> We don't support `response.is_ok` since the naming is ambiguous there, and might incorrectly imply an equivalence to `response.status_code == codes.OK`. Instead we provide an `.is_error` property.
What do we think?
> Add `Response.is_error`

- httpx/decoders.py
- httpx/models.py
- tests/models/test_responses.py
- tests/test_decoders.py
Closes #413
Implemented as sans-io incremental universal newline decoder, so we can test it nicely in isolation.
> Add `Response.stream_lines()`

- httpx/models.py
- httpx/multipart.py
- tests/test_multipart.py
> Files without a filename should not set a Content-Type in multipart data.

- docs/advanced.md
Change docs to reflect changes made in #520 
Closes #579
> Clarify multipart documentation

- docs/advanced.md
- docs/http2.md
- docs/index.md
- httpx/__init__.py
- httpx/api.py
- httpx/client.py
- httpx/config.py
- httpx/dispatch/connection.py
- httpx/dispatch/connection_pool.py
- httpx/dispatch/proxy_http.py
- mkdocs.yml
- tests/client/test_proxies.py
- tests/dispatch/test_http2.py
- tests/test_concurrency.py
- tests/test_config.py
- tests/test_multipart.py
* HTTP/2 is off by default.
* `Client(http2=True)` to enable
* Added HTTP/2 docs.
Closes #582
Still TODO:
API changes for `http_version=...` to `http_2=[True|False]`, so we should leave this to a 0.9 release.
> Better HTTP/2 defaults.

- docs/advanced.md
The docs now call out `backend='trio'`/`backend='asyncio'`, and includes basic asyncio and trio examples.
Furthermore we no longer list asyncio as the "default", since it's actually not. AutoDetect is the default.
Refs #389
> Improve backend docs, particularly wrt. autodetection

- tests/dispatch/test_http2.py
* `Timeout` -> `TimeoutException` in an HTTP/2 test case.
> Fix exception name in test case.

- docs/api.md
- httpx/models.py
- tests/client/test_client.py
- tests/models/test_responses.py
Renames `.raw()` to `.stream_raw()`, and renames `.stream()` to `.stream_bytes()`, so that we have a nice consistent suite of streaming operations...
* `response.stream_raw()`
* `response.stream_bytes)`
* `response.stream_text()`
* `response.stream_lines()`
Plus also...
* `response.read()`, `response.close()`
The existing `.raw` and `.stream` methods remain for compat, but issue warnings.
This is the first part of #588
We don't yet have any streaming docs. We might want to wait until we also address the second part of this work, and add the documentation as part of *that* pull request rather than *this* one, since we've got some new API that we want to add there.
> Consistent suite of `stream_*` methods

- httpx/concurrency/asyncio.py
- httpx/concurrency/base.py
- httpx/concurrency/trio.py
- httpx/dispatch/http2.py
A little bit of rationalization of our HTTP/2 handling, so that we can drop the quirky "write_no_block" primitive from our backend API.
I want to follow this up with some more substantial clean ups of our HTTP/2 implementation, but let's do this incrementally.
> Drop write_no_block from backends.

- CHANGELOG.md
I *think* that this is everything we need to call out from a user-facing perspective.
There's a few other refactorings that I've omitted, since they're strictly behind-the-scenes.
https://github.com/encode/httpx/commits/master
> Update changelog to include 'master'

- docs/compatibility.md
- docs/quickstart.md
- httpx/__init__.py
- httpx/api.py
- httpx/client.py
- tests/client/test_async_client.py
- tests/client/test_client.py
- tests/test_api.py
- tests/test_timeouts.py
Streaming a request looks like this...
```python
async with httpx.stream("GET", "https://www.example.com") as response:
async for line in response.stream_lines():
print(line)
```
This ensures that our streaming I/O is always properly context scoped.
Essentially closes #555
Closes #588
**TODO**:
> Add Client.stream() method.

- httpx/__init__.py
- httpx/concurrency/asyncio.py
- httpx/concurrency/auto.py
- httpx/concurrency/base.py
- httpx/concurrency/trio.py
- httpx/dispatch/http2.py
- tests/test_concurrency.py
Fixes #565 
There's a subtle case regarding handling multi-errors (i.e. what happens if `coroutine2` raises an exception while we're handling an exception raised by `coroutine2`), but I'd suggest handling it in a subsequent PR. I left a comment in the code regarding this.
> Drop BackgroundManager in favor of fork(func1, func2)

- docs/advanced.md
- docs/compatibility.md
- docs/environment_variables.md
- httpx/client.py
Refs #554.
Adds a warning not to use `cert=...`, `verify=...`, or , `truts_env=...` on client methods, but instead pass them to the client init (and use a different client instance if you need different cert/verify/trust_env configuration.)
I *think* that addressing #554 is the right thing to do, particularly wrt. honing in on a 1.0. (It's much easier for us to add them back in if we decide we really want to, than it is to take them out.)
Benefits here are that:
* Connection pooling will be seperate for differing `cert`/`verify` cases.
* The change will positively impact the dispatcher API, and improve implementation clarity all the way through.
**TODO**:
As I say, we *could* come back to including these at a future date if we really want them, but I think it's better that we start from …
> Warn if cert / verify / trust_env are passed to client.request()

- httpx/dispatch/connection.py
- httpx/dispatch/proxy_http.py
Prompted by https://github.com/encode/httpx/issues/496#issuecomment-562505159
Removes pending HTTP version-specific usage from `HTTPProxy`, in order to make it easier to disable HTTP/2 by default in the future (by lazily importing `h2`).
I added a few extra comments in there to further clarify how and why `.tunnel_start_tls()` works.
> Move tunnel_start_tls() to HTTPConnection

- docs/advanced.md
- httpx/__init__.py
- httpx/dispatch/proxy_http.py
- tests/client/test_auth.py
- tests/client/test_cookies.py
- tests/client/test_headers.py
- tests/client/test_proxies.py
- tests/client/test_queryparams.py
- tests/client/test_redirects.py
- tests/concurrency.py
- tests/conftest.py
- tests/dispatch/test_connection_pools.py
- tests/dispatch/test_connections.py
- tests/dispatch/test_proxy_http.py
- tests/dispatch/utils.py
- tests/models/test_url.py
- tests/test_concurrency.py
- tests/test_config.py
- tests/test_decoders.py
- tests/test_multipart.py
- tests/test_timeouts.py
Drops various private API from the top-level API.
We should recommend that our users *only* import the top-level `httpx` package, rather than importing sub-modules, in order to help guide them towards public API only.
Eg.
✅ Approved usage:
```python
import httpx
httpx.URL(...)
```
⚠️ Uh-oh:
```python
from httpx.models import URL
URL(...)
```
Refs #606
> Tighten up top-level API to only expose public API

- docs/compatibility.md
- docs/quickstart.md
- httpx/models.py
- tests/client/test_client.py
- tests/models/test_responses.py
Change streaming API to use styles like `response.aiter_bytes()` instead of `response.stream_bytes()`.
> Add `aiter_bytes` style methods on response.

- CHANGELOG.md
- httpx/__version__.py
I think we're about ready to go here.
Final bits to decide:
> Version 0.9

- CHANGELOG.md
- httpx/__version__.py
- httpx/concurrency/auto.py
Seems that we don't have coverage for this yet.
> Add 'fork' to auto backend

- httpx/concurrency/asyncio.py
- httpx/concurrency/trio.py
- tests/test_concurrency.py
Stream operations like `.read()` and `.write()` now have a mandatatory `timeout: Timeout` argument, rather than an optional one.
We can also drop the `self.timeout` state where stream instances had a "default" timeout associated with them. At this level of the API it's better for us to force a timeout to be explicitly passed. (Plus it already *is* everywhere we're using it.)
> Manadatory timeout argument on backend operations.

- tests/client/test_async_client.py
- tests/client/test_redirects.py
- tests/concurrency.py
- tests/conftest.py
- tests/dispatch/test_connection_pools.py
- tests/dispatch/test_connections.py
- tests/dispatch/test_http2.py
- tests/dispatch/test_proxy_http.py
- tests/dispatch/utils.py
- tests/test_concurrency.py
- tests/test_timeouts.py
Following up comments from #614, this PR updates the tests so that:
- They prefer passing the string-form backend (`"auto"`, `"asyncio"`, `"trio"`) to all pieces of public API.
- The `"auto"` option is put under test as well.
Fixes a bunch of `NotImplementedError`s in the `concurrency` test utils as well.
Tests that use the `backend` are now twice as many (because the `backend` fixture now has two more params - auto-in-asyncio and auto-in-trio). I figured the test suite was still fast enough that running all these tests for each situation was acceptable, rather than e.g. unit-testing that passing `"asyncio"` looks up `AsyncioBackend`. Now that I wrote about it I'm less sure this wouldn't be preferable.
> Refactor tests in the light of backend auto-detection

- httpx/concurrency/asyncio.py
- httpx/concurrency/base.py
- httpx/concurrency/trio.py
- httpx/dispatch/http11.py
Now that we always just "send a request, read the response" rather than any fancy "start sending the request, and start reading a response" we can drop the rather awkward `TimeoutFlag` that allowed us to switch from read timeouts to write timeouts as soon as we started seeing any response data.
> Drop TimeoutFlag

- httpx/concurrency/asyncio.py
- httpx/concurrency/auto.py
- httpx/concurrency/base.py
- httpx/concurrency/trio.py
- tests/test_concurrency.py
Turns out that neither of our HTTP/1.1 or HTTP/2 implementations actually require any backgrounding. I'm curious if there's any performance implications to this wrt. HTTP/2 that backgrounded writes would deal with, but if that *is* the case, then we can always bring fork back in. Right now we just don't need it, which is 👍.
> Drop 'fork'

- httpx/dispatch/base.py
- httpx/dispatch/connection.py
- httpx/dispatch/http11.py
- httpx/dispatch/http2.py
To progress towards resolving #496, we need to isolate the manipulation of `HTTP2Connection` in `HTTPConnection`.
This PR (inspired by #604) introduces a base `OpenConnection` interface that `HTTP11Connection` and `HTTP2Connection` implement, which allows `HTTPConnection` to hold a single `open_connection` object instead of one of `h11_connection` or `h2_connection`.
> Add OpenConnection base class

- httpx/config.py
- tests/test_config.py
* Drop `DEFAULT_SSL_CONFIG` - We're not actually using it anywhere.
* Scope `DEFAULT_CA_BUNDLE_PATH` more tightly.
> Minor config cleanup

- httpx/concurrency/asyncio.py
- httpx/concurrency/base.py
- httpx/concurrency/trio.py
* Drop unused methods from BaseEvent.
* Use an explicit Event class in the asyncio implementation, rather than a lazy cast-and-hope.
> Refactor BaseEvent

- httpx/dispatch/http2.py
This refactor moves all the H2 state management onto the Connection class, rather than being per-stream.
I think we'll want to eventually move our stream-locks out of the stream implementation and onto  HTTP2Connection instead, so eg...
```python
async with self.write_lock:  # Ensure that outgoing data cannot get sent out-of-sequence.
data_to_send = self.state.data_to_send()
await self.socket.write(data_to_send, timeout)
```
> Ensure H2 state is only accessed by the connection, not per-stream.

- httpx/concurrency/asyncio.py
- httpx/concurrency/auto.py
- httpx/concurrency/base.py
- httpx/concurrency/trio.py
- httpx/dispatch/connection.py
- httpx/dispatch/connection_pool.py
- tests/dispatch/test_connection_pools.py
Closes #34
Closes #95 (as best we can)
Closes #289
> Keep-alive timeouts.

- httpx/dispatch/http2.py
- tests/dispatch/utils.py
Have confirmed that this closes #262
😊😊😊
> Bump up flow control defaults

- CHANGELOG.md
- httpx/__version__.py
- Added expiry to Keep-Alive connections, resolving issues with acquiring connections. (Pull #627)
- Increased flow control windows on HTTP/2, resolving download speed issues. (Pull #629)
> Version 0.9.4

- httpx/models.py
> Explicit Content-Type headers should take precedence over encoding Content-Type headers.

- httpx/concurrency/asyncio.py
Fixes #634 
Basically reverts #494.
Opening this as a POC - not sure this is the best way to fix things, or that this won't break other stuff.
> asyncio: Don't wait for the stream to close

- requirements.txt
Prompted by https://github.com/encode/httpx/pull/639#issuecomment-566235998. This issue is affecting all new builds (e.g. https://github.com/encode/httpx/pull/641). I notified the `regex` maintainers about it [here](https://bitbucket.org/mrabarnett/mrab-regex/issues/343/wheel-for-linux) and the issue is tracked [here](https://bitbucket.org/mrabarnett/mrab-regex/issues/349/no-module-named-regex_regex-regex-is-not-a), but for now we should get our CI back on track.
> Force compiling 'regex' from source to resolve failing CI builds

- httpx/client.py
- httpx/content.py
- httpx/models.py
- httpx/multipart.py
- tests/client/test_redirects.py
- tests/dispatch/test_http2.py
- tests/dispatch/utils.py
- tests/models/test_requests.py
- tests/test_content.py
This pull requests adds `RequestContent` as the internal interface for all request body construction. The RequestContent interface provides:
* `.get_headers()` - Return the headers for the encoding.
* `.is_rewindable()` - True if the content can be replayed, False otherwise.
* `async def __aiter__() -> bytes` - Returns the byte stream for the encoded data.
There are a few concrete implementations.
* `RequestContent` - An empty request content.
* `BytesRequestContent` - Handles plain bytes and str content.
* `StreamingRequestContent` - Handles byte async iterables. Not rewindable.
* `JSONRequestContent` - Handles JSON data.
* `URLEncodedRequestContent` - Handles URL encoded form data.
* `MultipartEncodedRequestContent` - Handles Multipart encoded form data.
There is also a top level …
> Added RequestContent

- httpx/client.py
- httpx/models.py
- tests/client/test_headers.py
- tests/models/test_url.py
Closes #646
Resolved two issues when the default port is explicitly included in the URL, eg... `http://www.facebook.com:80/`
* HSTS - We were updating the scheme to `https`, but not stripping the port.
* Host headers - We were using `www.facebook.com:80` as the Host header, I *think* that's porbably technically okay-by-the-book, but causes many server implementations to issue incorrect redirect-to-https behavior, redirecting to `https://www.facebook.com:80/`.
After this pull request we...
* Strip any `":80"` port portion from the URL on HSTS URL updates.
* Use `{url.host}` for the host header if there is no explicit port, or if the explicit port is the defaut, otherwise use `{url.host}:{url.port}`.
* No longer add an empty userinfo section when `url.copy_with` includes host/port changes.
> Fix Host header and HSTS when the default port is in URL.

- CHANGELOG.md
- httpx/__version__.py
- Fix Host header and HSTS rewrites when an explicit `:80` port is included in URL. (Pull #649)
- Query Params on the URL string are merged with any `params=...` argument. (Pull #653)
- More robust behavior when closing connections. (Pull #640)
- More robust behavior when handling HTTP/2 headers with trailing whitespace. (Pull #637)
- Allow any explicit `Content-Type` header to take precedence over the encoding default. (Pull #633)
> Version 0.9.5

- setup.py
We ought to prefer using the latest `h11`, but we *are* still 0.8 compatible, so restrict allowed versions to `0.8.*`, `0.9.*`.
> Upgrade h11 to support both 0.8 and 0.9.

- httpx/concurrency/asyncio.py
- httpx/concurrency/auto.py
- httpx/concurrency/base.py
- httpx/concurrency/trio.py
- httpx/dispatch/connection_pool.py
Some internal refactoring, to make the usage of backend 'semaphore' and 'event' classes more consistent.
* Switch to `create_semaphore()` for consistency with `create_event()`.
* Stop using `BasePoolSemaphore`, and instead just use a generic `BaseSemaphore`. Pass the `exc_class=PoolTimeout`, so that backend semaphores are *not* specific to any particular use-case. (We don't strictly need to do this, but I think it feels neater?)
* Move implementations into more consistent locations, so that event and semaphore implementations are kept close.
> Rationalize backend Semaphore interface slightly

- httpx/models.py
- tests/dispatch/test_http2.py
- tests/models/test_responses.py
- tests/test_decoders.py
- tests/test_multipart.py
Prompted by https://github.com/encode/httpx/pull/665/files#r360601429: `response.request` is only ever `None` in our tests, so let's make it non-optional to provide better type-checking UX on the user side.
> Make 'request' non-optional on responses

- tests/client/test_async_client.py
- tests/client/test_redirects.py
- tests/conftest.py
- tests/dispatch/test_connection_pools.py
- tests/dispatch/test_connections.py
- tests/dispatch/test_http2.py
- tests/dispatch/test_proxy_http.py
- tests/test_concurrency.py
- tests/test_timeouts.py
https://github.com/encode/httpx/pull/615 removed passing `backend=...` to most of our tests, but we still had a `backend` fixture. It was declared as a test function parameter but not actually used.
This PR replaces this fixture with another one, `async_environment`. It is invoked using `@pytest.mark.usefixtures()` and should be applied when we want to run a test against all async environments.
> Clean up 'backend' fixture

- docs/api.md
The `Response` API reference still showcased the `stream_*` methods instead of `aiter_*` - refs #610.
> Fix out-of-date streaming methods on Response API docs

- tests/client/test_cookies.py
More tests type-checking, refs #650.
> Type-check test_cookies.py

- httpx/models.py
> Drop Request.read()

- docs/api.md
- httpx/client.py
- httpx/models.py
- tests/client/test_redirects.py
> Rename 'next' to 'anext' on Response

- docs/advanced.md
- docs/api.md
- docs/compatibility.md
- docs/environment_variables.md
- docs/http2.md
- httpx/__init__.py
- httpx/api.py
- httpx/client.py
- httpx/dispatch/asgi.py
- httpx/dispatch/base.py
- tests/client/test_async_client.py
- tests/client/test_auth.py
- tests/client/test_client.py
- tests/client/test_cookies.py
- tests/client/test_headers.py
- tests/client/test_properties.py
- tests/client/test_proxies.py
- tests/client/test_queryparams.py
- tests/client/test_redirects.py
- tests/dispatch/test_http2.py
- tests/test_asgi.py
- tests/test_multipart.py
- tests/test_timeouts.py
- tests/test_utils.py
Refs #667 
- Rename `Client` to `AsyncClient`
- Update references to `Client` in core and tests.
- Change docs to encourage using `AsyncClient` from 0.10.0 and on.
- Add `Client` synonym for backwards compat with `0.9.*`.
Regex search & replace was a good mate on this one. 💯
> Rename Client to AsyncClient (with compat synonym)

- httpx/backends/asyncio.py
- httpx/backends/auto.py
- httpx/backends/base.py
- httpx/backends/trio.py
- httpx/dispatch/http2.py
As noted in https://github.com/encode/httpx/pull/660#issuecomment-567906879
This will allow us to then:
* Move read/write locks *outside* the stream, and onto the HTTP classes instead, with a view to resolving #551.
* Revisit https://github.com/encode/httpx/pull/624, which needs locking behavior to get fully sorted. (With a view to resolving #514)
> Switch from an Event primitive to a Lock primitive

- docs/api.md
- httpx/client.py
- httpx/models.py
- tests/models/test_responses.py
Couple of further tweaks on top of #687, with thanks to @gdhameeja ✨
* `Response(content=...)` is a closed response and should have `response.elapsed == datetime.timedelta(0)`.
* `._elapsed` should only be set when the response is closed. Any further calls to `.close` should have no effect.
Closes #655
> response.elapsed now reflects entire request/response time.

- CHANGELOG.md
- README.md
- docs/index.md
- httpx/__version__.py
Closes #667
The 0.10.0 makes some changes that will allow us to support both sync and async interfaces.
In particular with streaming responses the `response.read()` method becomes `response.aread()`, and the `response.close()` method becomes `response.aclose()`.
If following redirects explicitly the `response.next()` method becomes `response.anext()`.
- End HTTP/2 streams immediately on no-body requests, rather than sending an empty body message. (Pull #682)
- Improve typing for `Response.request`: switch from `Optional[Request]` to `Request`. (Pull #666)
- `Response.elapsed` now reflects the entire download time. (Pull #692)
- Added `AsyncClient` as a synonym for `Client`. (Pull #680)
- Switch to `response.aread()` for conditionally reading streaming responses. (Pull #674)
- Switch to …
> Version 0.10.0

- httpx/content_streams.py
- tests/test_content_streams.py
Adds `is_stream_consumed` boolean to AsyncIteratorStream, along with check to ensure stream is only consumed once. Also adds associated test.
Closes #668
> Closes #668 - AsyncIteratorStream should error if `__iter__` is called twice.

- httpx/backends/asyncio.py
- httpx/backends/trio.py
> Lock around `stream.write` and `stream.close` operations

- httpx/dispatch/base.py
- httpx/dispatch/connection.py
- httpx/dispatch/http11.py
- httpx/dispatch/http2.py
Since we're not 100% on if we want #496 or not, I think we should drop the `OpenConection` abstraction for now - really we should only introduce that if we need it.
I've also made some other refactoring tweaks:
* `.open_connection` -> `.connection`.
* Drop `.set_open_connection` in favor of just instantiating the connection where used.
* More robust behavior for `.is_http2`, `.is_closed`, `.is_connection_dropped` properties.
Also closes #689
> Drop `OpenConnection`

- httpx/config.py
No longer required since #617. 👍
> Drop unused `SSLConfig.with_overrides`

- httpx/models.py
Although this might look like an API breaking change on first sight, I think we could actually treat it as a borderline bugfix...
We're currently exposing a `.cookies` property on `Request`, but we don't *do anything with it*.
If a user builds a request instance explicitly, and sets items on `request.cookies` it won't have any effect.
I'd potentially be okay with us *having* a `request.cookies` property at some point, tho it's not neccessarily a given that we ought to. Given that it doesn't currently have the behavior users would expect from it, I think it's reasonable just to drop it outright for now.
> Drop non-functional `Request.cookies` property.

- httpx/__init__.py
- httpx/config.py
- httpx/models.py
[The doc](https://www.encode.io/httpx/advanced/#setting-and-disabling-timeouts) says we can disable timeout by setting it to None, but currently `TimeoutTypes`  doesn't allow a None, so I added it.
Plus, cleans up two removed entries from `__all__`.
> Make timeout parameter None-able & cleanup __all__.

- httpx/client.py
- httpx/config.py
- httpx/dispatch/proxy_http.py
- httpx/models.py
- tests/client/test_redirects.py
- tests/dispatch/test_http2.py
- tests/dispatch/utils.py
- tests/models/test_responses.py
- tests/test_decoders.py
* `nocover` on deprecated API.
* `nocover` on areas that are not available on all Python versions.
* `nocover` on xfail exception cases in tests.
* Test for uncovered behavior accessing `response.elapsed` before response is closed.
* Test for uncovered behavior of `aiter_text()` decoding.
* Refactor to remove uncovered line from test utils.
* Ingest request body in RedirectBodyUnavailable test case.
> Bump coverage

- CHANGELOG.md
- httpx/__version__.py
- Fix issue with concurrent connection acquiry. (Pull #700)
- Fix write error on closing HTTP/2 connections. (Pull #699)
> Version 0.10.1

- httpx/config.py
- httpx/dispatch/connection.py
- httpx/dispatch/connection_pool.py
- httpx/dispatch/proxy_http.py
- tests/client/test_proxies.py
- tests/dispatch/test_connections.py
The HTTPConnection class now takes any ssl configuration as a single `ssl: SSLConfig` argument.
As a result, the ConnectionPool class holds a single `SSLConfig` argument, that only ever ends up being loaded once.
I've dropped the `run_in_threadpool` behavior since we're only making a single load-from-disk per Client instance here.
Should provide slightly better performance since we're not reloading the SSLContext once-per-connection anymore.
I'd like to iterate on this further so that the context loading just happens directly when instantiating `SSLConfig`. However, I'm going to leave that to a follow-up PR, in order to keep this managably reviewable.
> SSLConfig refactor

- httpx/content_streams.py
- httpx/models.py
- tests/models/test_responses.py
- tests/test_content_streams.py
Refs #572 
Add sync interfaces for streaming on responses.
Draft PR at the moment just to demonstrate how it'll look... The tests will need filling out to.
Related to this will be:
* Ability to support both sync and async request bodies... We need an `IteratorStream` in `content_streams.py`.
* `.next()`
> Sync streaming interface on responses

- httpx/backends/auto.py
- httpx/utils.py
- tests/concurrency.py
- tests/dispatch/utils.py
- tests/test_decoders.py
* Remove unused util function, `kv_format(...)`.
* Remove redundant extra line in test case.
* Use `nocover` on case of runtime errors when running under an asyncio library other than asyncio/trio.
* Drop redundant usage of async `sleep` in test cases.
Remaining cases:
> More coverage improvements

- httpx/config.py
- httpx/dispatch/connection.py
- tests/test_config.py
Follow up to #706
Load the SSLContext at the point that SSLConfig is initialized, rather than per-request.
One benefit of this is that we'll now raise any configuration errors that the point of client-init, rather than on the initial request.
> Load SSL Context on init

- docs/quickstart.md
Prompted by https://github.com/encode/httpx/pull/718#issuecomment-570696266 :-)
> Fix typo in 'Redirection and History' docs

- httpx/client.py
- tests/client/test_auth.py
Fixes #669 
Based on @gdhameeja's work in #686 🌟🙇
The updated tests contain:
- Asserts on `response.history` in the digest auth case.
- An isolated test case using an imaginary auth scheme, for in-depth verification of what gets pushed to the history.
> Record history of requests made during authentication

- httpx/backends/asyncio.py
- httpx/backends/trio.py
- httpx/exceptions.py
- httpx/utils.py
Fixes #349 
- Wrap `OSError` exceptions raised in backends `.read()`, `.write()`, `.close()`, as well as `.open_xxx_stream()` methods.
- For trio, handle `BrokenResourceError` exceptions as well when we can expect trio to raise them instead of `OSError`-derived exceptions.
- Specialize `ConnectionClosed` to be a subclass of `NetworkError`.
Note that we're not doing special handling for `ConnectionError` because it's a subclass of `OSError`.
Not married to the naming/API specifics of the `as_network_error()` construct — could also be e.g. `raise_as(NetworkError, OSError)`. But I think it's a good idea to have a dedicated utility for actually performing the wrapping, instead of bare `try/except`. Eg. this centralizes which behavior we'd like to expose w.r.t. exposing or hiding the …
> Wrap network errors as HTTPX-specific exceptions

- httpx/__init__.py
- httpx/client.py
- httpx/dispatch/connection_pool.py
- httpx/dispatch/proxy_http.py
- httpx/models.py
- tests/models/test_url.py
> Drop `Origin` from public API

- httpx/client.py
Switch `proxies_to_dispatches` to `get_proxy_map`.
This style means that we end up with a map of `{key: Proxy()}`, which is sync/async compatible,
so `get_proxy_map` is shared across both implementations, where `proxies_to_dispatchers` could not be.
Should mean that addressing any thing else demo'ed by #716 can be a single fairly clean PR for review.
> proxies_to_dispatchers -> get_proxy_map

- httpx/__init__.py
- httpx/api.py
- httpx/client.py
- httpx/config.py
- httpx/dispatch/__init__.py
- httpx/dispatch/asgi.py
- httpx/dispatch/base.py
- httpx/dispatch/urllib3.py
- httpx/dispatch/wsgi.py
- httpx/models.py
- setup.cfg
- setup.py
- tests/client/test_client.py
- tests/client/test_proxies.py
- tests/dispatch/test_proxy_http.py
- tests/models/test_requests.py
- tests/test_api.py
- tests/test_wsgi.py
> Reintroduce sync API.

- httpx/config.py
Include description of `soft_limit` and `hard_limit` on PoolLimits.
Refs #708, but probably not sufficient to close it.
We'll probably want an explicit section in the advanced docs on connection pool limits, pool timeouts, max streams per connection etc. Also complicated by the sync implementation currently having a different style of behavior to the async version.
> Improve docstring for PoolLimits

- CHANGELOG.md
- docs/quickstart.md
- httpx/__version__.py
- mkdocs.yml
- setup.py
Closes #724
Also requires the following, before merge:
I've currently listed the release date here as tomorrow (Thursday 9th January). I don't *think* we've got any blockers left at this point, @florimondmanca?
The 0.11 release reintroduces our sync support, so that `httpx` now supports both a standard thread-concurrency API, and an async API.
Existing async `httpx` users that are upgrading to 0.11 should ensure that:
* Async codebases should always use a client instance to make requests.
* The async client is named as `httpx.AsyncClient()`.
* When instantiating proxy configurations use the `httpx.Proxy()` class, instead of the previous `httpx.HTTPProxy()`. This new configuration class works for configuring both sync and async clients.
We believe the API is now pretty much stable, and are …
> Version 0.11.0

- docs/async.md
```python
>>> import asyncio
>>> async def stream():
client = httpx.AsyncClient()
async with client.stream('GET', 'https://www.example.com/') as response:
async for chunk in response.aiter_content():
print(chunk)
>>> asyncio.run(stream())
```
```
File "<pyshell#7>", line 1, in <module>
asyncio.run(stream())
File "C:\Program Files\Python37\lib\asyncio\runners.py", line 43, in run
return loop.run_until_complete(main)
File "C:\Program Files\Python37\lib\asyncio\base_events.py", line 583, in run_until_complete
return future.result()
File "<pyshell#6>", line 4, in stream
async for chunk in r.aiter_content():
NameError: name 'r' is not defined
File "<pyshell#4>", line 1, in <module>
asyncio.run(stream())
File …
```
> Fix typo in 'Streaming responses' docs

- docs/CNAME
Add the missing `CNAME` file to the `docs` root directory.
This file is (secretly) added by GitHub when a custom domain is setup via the "Settings" page. But we need to commit it to the repo so that MkDocs keeps it when deploying.
(I deployed the docs manually to publish recent typo fixes, which is when `CNAME` was removed from the `gh-pages` branch by MkDocs.)
Thanks @lilydjwg for noticing this here: https://github.com/encode/httpx/commit/f46ac022eb11ff53f38037f21ab3d8bc8ad89b46#commitcomment-36755660
> Setup custom domain for docs site

- docs/quickstart.md
Fixes syntax highlighting in "quickstart" page.
> Fix syntax highlighting

- setup.py
For programmatic access to metadata on PyPI.
Also add the "Python 3 Only" Trove classifier, which can also be useful for programmatic use.
> Add docs and repo to project_urls metadata

- httpx/decoders.py
- tests/test_decoders.py
Closes #756 
`DeflateDecoder` now attempt both "deflate" decoding and "zlib" decoding.
> Support both zlib and deflate encodings

- httpx/dispatch/urllib3.py
Closes #762
The `urllib3.ProxyManager` instantiation wa broken because it was passing an `httpx.URL()` instance as the `url` argument, instead of the plain string representation.
> Fix urllib3 proxy instantiation

- httpx/client.py
- tests/client/test_redirects.py
When making a request with `.stream(... allow_redirects=False)` any redirect response that is returned should be streamable, and not have already been read.
```python
>>> with httpx.stream("GET", "https://daringfireball.net/css/ie_sucks.php", allow_redirects=False) as response:
...     body = b''.join([chunk for chunk in response.iter_raw()])
... 
File "<stdin>", line 2, in <module>
File "<stdin>", line 2, in <listcomp>
File "/Users/tomchristie/Temp/venv/lib/python3.7/site-packages/httpx/models.py", line 939, in iter_raw
raise StreamConsumed()
httpx.exceptions.StreamConsumed
```
> Fix for streaming a redirect response body with allow_redirects=False

- httpx/client.py
- httpx/models.py
- tests/client/test_redirects.py
Gracefully handle redirect with malformed `Location` headers such as `Location: https://:443/`
Closes #771
> Handle redirect with malformed Location headers missing host.

- CHANGELOG.md
- httpx/__version__.py
* Fixed usage of `proxies=...` on `Client()`. (Pull #763)
* Support both `zlib` and `deflate` style encodings on `Content-Encoding: deflate`. (Pull #758)
* Fix for streaming a redirect response body with `allow_redirects=False`. (Pull #766)
* Handle redirect with malformed Location headers missing host. (Pull #774)
> Version 0.11.1

- docs/advanced.md
- httpx/config.py
- tests/test_config.py
Fixes https://github.com/encode/httpx/issues/779
Use the [same logic from `proxy_http`](https://github.com/encode/httpx/blob/master/httpx/dispatch/proxy_http.py#L83-L96) in the `Proxy` config, e.g. detects if credentials are present in the proxy URL and adds the authorization header accordingly. Also remove the credentials for the URL.
> Detect credentials in proxy URLs and create Proxy-authorization header

- httpx/config.py
FORWARD_ONLY seems correct
https://github.com/encode/httpx/blob/b23420392efdcc10f3d802f335739d9cb3d72d5c/httpx/dispatch/proxy_http.py#L63
and
https://github.com/encode/httpx/blob/b23420392efdcc10f3d802f335739d9cb3d72d5c/httpx/config.py#L326
seems different.
> Fix `httpx.Proxy(..., mode="FORWARD_ONLY")` configuration.

- tests/dispatch/test_connection_pools.py
> Fix simple typo: conncurrent -> concurrent

- docs/advanced.md
- docs/async.md
Refs #798 
The motivation is to make it clearer that app-based dispatchers aren't actually making network calls, and that actually the scheme/hostname/port in URLs are irrelevant in those cases…
Is this a good idea at all?
> Use a base_url in app dispatcher examples

- docs/advanced.md
- httpx/_auth.py
- httpx/_client.py
- tests/client/test_auth.py
If set then responses are read by the client before being sent back into the auth flow.
This is a work-in-progress. This branch has no test coverage right now because I don't fully understand the implications of this change. Currently there are five tests which fail if `requires_response_body` is set to `True`. These are all asserting that the response hasn't yet been read, or it isn't closed.
I can't figure out a way to ensure these tests all pass with `requires_response_body=True`. It's difficult because the response needs to be read before passing it back to `auth_flow`, but we need to pass it back in order to get the `StopIteration` to determine when to return.
Fixes #802
> Add Auth.requires_response_body attribute

- httpx/_models.py
Reproduce steps:
```python
>>> r = httpx.Client()
>>> r.headers['Velocity®Ultra'] = 'Velocity®Ultra'
File "<stdin>", line 1, in <module>
File "/usr/lib/python3.7/site-packages/httpx-0.11.1-py3.7.egg/httpx/_models.py", line 518, in __setitem__
set_key = key.lower().encode(self.encoding)
UnicodeEncodeError: 'ascii' codec can't encode character '\xae' in position 8: ordinal not in range(128)
```
> When setting headers, fallback to `utf-8` if no encoding is specified yet.

- httpx/_config.py
Now httpx ignore `cert` param for Client Side Auth if set `verify=False`. This is different behaviour with `requests`
> Forward `cert` param to SSLConf if `verify=False`

- httpx/_client.py
Closes #824
Actually it would be *better* for us to gracefully handle the case where one or more `close()` calls error, and still end up calling all of them, only raising an exception at the end, however there's no reason that we can treat that as an incremental improvement on top of this.
> Close proxy dispatch classes on Client.close()

- docs/advanced.md
This PR updates the documentation on `Client` instances:
- Add info on motivations for using clients over the top-level API (with some IMO necessary info about connection pooling and its benefits)
- Dedicate the "Usage" section to context-managed vs. `.close()`-style usage.
- Move info on making requests from "Usage" to a new dedicated section.
- Clarify behavior on client-level vs request-level params, esp. using dedicated section headers.
- Update the section on `.build_request()` to more generally detail how to use explicit `Request` instances (can be linked to in #823 once this is merged).
> Revamp docs on Client instances

- httpx/_content_streams.py
- tests/test_multipart.py
Noticed this looking in to #777.
We're allowing `data={"a": ["1", "2", "3"]}`, which makes sense, but also `data={"a": {"1": ["ignore", "this"], "2": ["ignore", "this"]}}` which doesn't.
> Don't support broken dict-of-dicts case for data argument.

- httpx/_client.py
- tests/client/test_proxies.py
This PR addresses issue https://github.com/encode/httpx/issues/360. I found this issue by attempting to use httpx in a environment that had both endpoints that needed to be proxied and ones that needed to stay in the local network. That is when I found out that there was no "NO_PROXY" support.
> Enable NO_PROXY environment variable support 

- setup.cfg
``httpx`` requires Python > 3 so its wheel must not be tagged as universal.
Fixes #850
> Do not mark wheel as universal

- CHANGELOG.md
Closes #829
The 0.12 release tightens up the API expectations for `httpx` by switching to private module names to enforce better clarity around public API.
All imports of `httpx` should import from the top-level package only, such as `from httpx import Request`, rather than importing from privately namespaced modules such as `from httpx._models import Request`.
* Support making response body available to auth classes with `.requires_response_body`. (Pull #803)
* Export `NetworkError` exception. (Pull #814)
* Add support for `NO_PROXY` environment variable. (Pull #835)
* Switched to private module names. (Pull #785)
* Drop redirect looping detection and the `RedirectLoop` exception, instead using `TooManyRedirects`. (Pull #819)
* Drop `backend=...` parameter on `AsyncClient`, in favour of …
> Version 0.12

- httpx/_content_streams.py
Probably due to the mypy 0.770 release very recently (https://github.com/python/mypy/issues/8437)…
Discovered as this is affecting https://github.com/encode/httpx/pull/861, which was reproducible if upgrading to `mypy==0.770` locally.
> Fix type checking breakage

- httpx/_content_streams.py
- tests/test_content_streams.py
Fix #862 
Could have conflict with #857
> Fix multipart edge cases with `data={}` and/or `files={}`

- CHANGELOG.md
- httpx/__version__.py
To close #864
Will issue a PyPI release from this, ensuring that `__pycache__` is properly clean first.
> Version 0.12.1

- docs/compatibility.md
* Add prepare_request equivalent of httpx to compatibility document
* Add difference b/w httpx.Request and requests.Request arguments to compatibility document
Fixes #795
> Add docs on request instances to Requests compatibility guide

- README.md
- docs/index.md
- docs/third-party-packages.md
- mkdocs.yml
Fixes #805 
This page is based on the format used in [Starlette - Third Party Packages](https://www.starlette.io/third-party-packages/) for consistency. :-)
> Add 'Third Party Packages' docs page

- docs/api.md
- httpx/_client.py
The Client docstring incorrectly says that it takes an ASGI app when it actually takes a WSGI app.
Also the AsyncClient's API isn't in the docs anywhere, so it is difficult to tell that you should use that instead.
It is arguable that the API of the AsyncClient should be on the Async client, and a link to it could be on the API page, but I think it makes more sense to have all the API in one place.  Happy to be corrected on this.
Fixes #879
> Fix Client Docstring and add AsyncClient to API docs

- httpx/_content_streams.py
- httpx/_models.py
- httpx/_types.py
- httpx/_utils.py
Extracted of #881 to reduce its scope.
We're using `AnyStr` in several places to refer to "either bytes or str", i.e. `Union[str, bytes]`.
But `AnyStr` is not a synonym for `Union[str, bytes]`, so we should really just be using `Union[str, bytes]`.
(For details: `AnyStr` is meant to be used when we can accept either, but don't allow them to mix, so eg `(s1: AnyStr, s2: AnyStr) -> AnyStr)` would either accept str/str and return str, or accept bytes/bytes and return bytes. See [typing docs](https://docs.python.org/3/library/typing.html#typing.AnyStr).)
This PR introduces a `StrOrBytes` util type to use across the codebase.
> Drop usage of `AnyStr`

- requirements.txt
We had a few hot fixes in our `requirements.txt` file due to transient failures in certain of our test dependencies — dropping them as these failures should be fixed by now.
> Remove stitches in `requirements.txt`

- README.md
- httpx/_exceptions.py
This PR fixes the remaining places where we refer to this project as "httpx" (lowercase) in a prose context, when we should be using "HTTPX" (uppercase).
> Fix casing nits

- httpx/_client.py
- httpx/_exceptions.py
A small quality-of-life improvement to our typing coverage: make sure that type checkers are aware that `HTTPError.request` always refers to a well-defined `Request` instance.
With the current state of things, assuming the issue described in #885 was fixed (it is addressed here too), mypy wouldn't let users access the `request` without casting it to a non-`None` first, which is bad UX.
There's also a hidden assumption that `exc.request` always has a request set, but it's not enforced anywhere in the code.
This PR updates `HTTPError` and the population of the request to reflect these points.
> Improve type hinting for `HTTPError.request`

- .github/ISSUE_TEMPLATE/1-question.md
- .github/ISSUE_TEMPLATE/2-bug-report.md
- .github/ISSUE_TEMPLATE/3-feature-request.md
A second iteration over #741, with templates for questions, bug reports and feature requests.
I think with these in place we can hope to reduce maintainer burden, as contributors will *think* more thoroughly about alternatives to opening an issue, possible solutions, etc.
This should help improve the contributing experience for all. :-)
(I based these off of the default GitHub templates, as well as those we can find on the [FastAPI repo](https://github.com/tiangolo/fastapi/issues/new/choose).)
> Add issue templates

- httpx/_api.py
- httpx/_auth.py
- httpx/_client.py
- httpx/_config.py
- httpx/_content_streams.py
- httpx/_dispatch/urllib3.py
- httpx/_models.py
- httpx/_types.py
- httpx/_utils.py
Refs https://github.com/encode/httpx/issues/789#issuecomment-578143085
Move all type definitions and aliases to a centralized `_types` module, instead of them being scattered across the code base. In line with what we do in HTTPCore. :-)
A simpler version of #881, branched off from `master`, and without any typing changes - only import changes.
> Move types definitions to a dedicated module

- httpx/_decoders.py
`hasattr` has a nasty performance penalty when it returns false: in the background it is actually a try/except AttributeError.  Since we know the method we want won't change, by instead caching the bound method object we can amortise the cost across an entire encoded body.
> Avoid hasattr in hot loop in brotli decoder

- httpx/_models.py
This enables us (or everyone else) to control emitted messages via the PYTHONWARNINGS environment variable or by -W option.
> Proper warning level of deprecation notice

- .github/workflows/test-suite.yml
- CHANGELOG.md
- README.md
- docs/index.md
- requirements.txt
- setup.py
The 0.13.0.dev0 is a *pre-release* version. To install it, use `pip install httpx --pre`.
This release switches to `httpcore` for all the internal networking, which means:
* We're using the same codebase for both our sync and async clients.
* HTTP/2 support is now available with the sync client.
* We no longer have a `urllib3` dependancy for our sync client, although there is still an *optional* `URLLib3Dispatcher` class.
> Version 0.13.0.dev0

- httpx/_dispatch/asgi.py
- tests/test_asgi.py
I've been trying to track down what broke for me when using httpx with starlette==0.13.3 with ASGI dispatch, see encode/starlette#908.
There are kind of two different problems:
1. Starlette calls both the `receive()` (to check for disconnects) and `send()` (to send the response) concurrently in its `StreamingResponse` type. It tries to wait for _either_ of those two options to complete (using `asyncio.wait({tasks}, return_when=asyncio.FIRST_COMPLETED)`). Because the ASGI dispatch in httpx is generally effectively synchronous, both `send()` and `receive()` may never return control to the event loop when called which means that if either task that is waited on _does not_ complete, then `asyncio.wait()` will not return. I've made encode/starlette#912 to attempt to work around that.
2. …
> asgi: Send http.disconnect message on receive() after response complete

- scripts/publish
I've published 0.13.dev0 manually.
Unintentionally it's published as "0.13.dev0" rather than 0.13.0.dev0 - if the publish script hadn't been broken in the first place then it would have errored on that clearly, rather than just failing without useful output.
> Fix VERSION_FILE in publish script.

- httpx/_models.py
Anytime I process the returned `json()` data from an API call, I run into mypy issues because the return type is currently `Union[dict, list]`:
```python
data = response.json()
_ = data["items"]
```
```console
debug/client.py:4: error: No overload variant of "__getitem__" of "list" matches argument type "str"
debug/client.py:4: note: Possible overload variants:
debug/client.py:4: note:     def __getitem__(self, int) -> Any
debug/client.py:4: note:     def __getitem__(self, slice) -> List[Any]
```
The workaround is this… (Note that marking as `: dict` is not enough, as mypy just won't let us down-grade a `Union` via a simple annotation.)
```
data: dict= response.json()  # type: ignore
```
But it's a pain, so this PR just marks the return type as `Any` — which is in line with …
> Mark `Response.json()` as returning `Any`

- docs/contributing.md
Prompted by https://github.com/encode/httpx/issues/929#issuecomment-624131087
I thought it'd be good to have it in the docs so we can point people to it as well.
> Document dev proxy setup

- CHANGELOG.md
- httpx/__version__.py
- setup.py
The 0.13.0.dev2 is a *pre-release* version. To install it, use `pip install httpx --pre`.
- Logging via HTTPCORE_LOG_LEVEL and HTTPX_LOG_LEVEL environment variables
and TRACE level logging. (HTTPCore Pull #79)
- Reuse of connections on HTTP/2 in close concurrency situations. (HTTPCore Pull #81)
- When using an `app=<ASGI app>` observe neater disconnect behaviour instead of sending empty body messages. (Pull #919)
> Version 0.13.0.dev2

- tests/client/test_client.py
- tests/conftest.py
Refs #943
* We've already got a test that ensures `response.elapsed > datetime.timedelta(0)`, so let's not try to enforce a "this should end up as more than one second" case.
* Let's bump the slow response default to a more reliably noticable 1 second delay.
> Attempt to resolve test flakiness

- scripts/test
When running `scripts/test` locally, we check the return result of the linting checks.
If they fail then prompt the user, and optionally run `scripts/lint`, then re-run the checks.
We *might?* still want to consider dropping `scripts/lint` in favour of `scripts/check --fix` in order to keep the two sets of linting/fixup in the same script, but let's treat that separately if so.
> If `scripts/check` fails then prompt and autofix.

- .github/workflows/test-suite.yml
- scripts/coverage
- scripts/test
- setup.cfg
Enforce test coverage when running the test suite.
Refs #316.
> Enforce coverage

- docs/advanced.md
- docs/async.md
- httpx/__init__.py
- httpx/_client.py
- httpx/_models.py
- httpx/_transports/asgi.py
- httpx/_transports/urllib3.py
- httpx/_transports/wsgi.py
- httpx/_utils.py
- tests/client/test_auth.py
- tests/client/test_proxies.py
Closes https://github.com/encode/httpx/issues/768
~I did some `dispatch > transport` renaming but did not rename the `_dispatch` package and the `*Dispatch` classes in it. I considered renaming the package to `_transports` and all classes to `*Transport` with `*Dispatch` aliases but thought it might be better to check first.~
Edit: Pipelines failed for some reason so I went for it while I gave GH actions some time to sort themselves out.
> Transport API

- httpx/_transports/urllib3.py
Refs #966
Instead of using `pool_limits` with `URLLib3Transport` this PR switches us to instead using their native pool limiting configuration options. I've taken the external naming and defaults in line with how `requests` adapter classes use `urllib3`.
One other thing we could consider here is if we'd like the external interface to be `URLLib3Transport` and `URLLib3ProxyTransport` for symmetry with the `httpcore` classes, and with the `urllib3` interface itself, bu t let's consider that independently.
> Use URLLib3 configuration options for URLLib3 transport

- httpx/_transports/urllib3.py
Drops `URLLib3Dispatch` given observation in https://github.com/encode/httpx/issues/966#issuecomment-632083663
Because:
* It's only ever existed in the pre-release `httpx` 0.13 pre-releases.
* It was never public API in any of those.
* It was only ever present under a different module name anyway, so any users of the pre-release versions, relying on a piece of private API, will have found the import is broken for them anyways.
> Drop URLLib3Dispatch compat shim

- httpx/_content_streams.py
- tests/test_multipart.py
The `files` argument allows `str/bytes` along with file objects, but we were not handling the `bytes` branch yet (incorrectly treating that as file objects).
I've provided a test, but also have a follow-up PR coming to tighten up the type checking in the multipart implementation (which was too lose for mypy to catch this).
> Fix bytes support in multipart uploads

- httpx/_types.py
When `files` is passed from a variable, mypy raises an error due to us using a `Dict` with union values:
```python
files = {"example": ("file name", "file content")}
_ = httpx.post("...", files=files)
```
```console
error: Argument "files" to "post" has incompatible type "Dict[str, Tuple[str, str]]"; expected "Optional[Dict[str, Union[Union[IO[str], IO[bytes], str, bytes], Tuple[Optional[str], Union[IO[str], IO[bytes], str, bytes]], Tuple[Optional[str], Union[IO[str], IO[bytes], str, bytes], Optional[str]]]]]"
note: "Dict" is invariant -- see http://mypy.readthedocs.io/en/latest/common_issues.html#variance
note: Consider using "Mapping" instead, which is covariant in the value type
```
This PR fixes this small UX bug. :-)
(Progressing on #650 would allow us to catch more of these …
> Improve typing support for the `files` parameter

- httpx/_content_streams.py
- setup.cfg
Refs #974
Use our type aliases for request files to more tightly type-check the `MultipartStream` implementation.
Helps catching any type-related issues such as the one resolved by #974.
> Tighten up types in multipart upload implementation

- CHANGELOG.md
- README.md
- docs/index.md
- httpx/__version__.py
Preliminary CHANGELOG and `__version__` update for 0.13.
Still required...
- Review if we want #970. (Use urllib3 native config for `URLLib3Transport` pooling options)
- Review if we want the second half of #966. (Use seperated `URLLib3Transport` and `URLLib3ProxyTransport` classes as the public API)
Up for reviews onto this in the meantime tho...
---
This release switches to `httpcore` for all the internal networking, which means:
* We're using the same codebase for both our sync and async clients.
* HTTP/2 support is now available with the sync client.
* We no longer have a `urllib3` dependency for our sync client, although there is still an *optional* `URLLib3Transport` class.
It also means we've had to remove our UDS support, since maintaining that would have meant having to push back …
> Version 0.13

- docs/http2.md
- httpx/__init__.py
* Add `URLLib3ProxyTransport` to `__init__`.
Which should be a helpful reminder to myself not to bypass the PR workflow, even if ya think you've got one extra tiny thing that oughta go in for the release. 😇
> Add urllib3proxy transport to init

- httpx/_config.py
- httpx/_utils.py
Currently creating a client with default options on httpx 0.13.0 produces these warnings:
```
.../lib/python3.8/site-packages/httpx/_utils.py:407
.../lib/python3.8/site-packages/httpx/_utils.py:407: DeprecationWarning: 'soft_limit' is deprecated. Use 'max_keepalive' instead.
warnings.warn(message, DeprecationWarning)
.../lib/python3.8/site-packages/httpx/_utils.py:407
.../lib/python3.8/site-packages/httpx/_utils.py:407: DeprecationWarning: 'hard_limit' is deprecated. Use 'max_connections' instead.
warnings.warn(message, DeprecationWarning)
```
> Fix pool option warnings for default connection pool

- CHANGELOG.md
- httpx/__version__.py
Pending #980, #979.
* Fix pool options deprecation warning. (Pull #980)
* Include `httpx.URLLib3ProxyTransport` in top-level API. (Pull #979)
> Version 0.13.1

- httpx/_client.py
I'd assumed we had `http2` support for sync Clients now, which is kind of true, in that the transport supports it now, but I'd forgotten that we didn't yet have an `http2=[False|True]` flag on the Client instance, since we've never needed one until now.
> Add 'http2' for Client

- .github/ISSUE_TEMPLATE/1-question.md
"Not getting an aswer" from the community chat is not a required item to submit a question issue. :-) (see https://github.com/encode/httpx/issues/987)
> Tweak Question issue template

- tests/concurrency.py
Cleaning up some dead code in the `tests/concurrency.py` module — some of it most likely went unused as part of #804.
> Remove unused concurrency test utils

- httpx/_types.py
Fixes an issue with our `TimeoutTypes` that makes mypy complain if users pass `None`'s as part of a timeout tuple (although `None` are accepted, meaning "no timeout"):
```python
import httpx
_ = httpx.Timeout((1.0, None, None, None))
```
```console
$ mypy example.py
example.py:3: error: Argument 1 to "Timeout" has incompatible type "Tuple[float, None, None, None]"; expected "Union[float, Tuple[float, float, float, float], Timeout, None]"
Found 1 error in 1 file (checked 1 source file)
```
> Fix handling of None values in timeout tuple type hint

- setup.cfg
Prompted by https://github.com/encode/httpx/pull/990#issue-422386898, refs #650 
Expanding type checking coverage to our `tests/` directory is very valuable to us, because it would allow to detect small typing support itches such as those resolved by #976 and https://github.com/encode/httpx/pull/985#issuecomment-633141145 earlier.
_But_ annotating test functions (eg `test_something(server: Server, param: str) -> None`) is cumbersome, time consuming, and actually not very useful in itself.
What we're interested in is the _inside_ of the test functions — the calls to HTTPX APIs and manipulation of returned values — because those mirror what users will do in the wild.
This PR tweaks our `mypy` config so that mypy is allowed to run type checking inside untyped test functions. This way, we …
> Add mypy config for tests directory

- httpx/_models.py
- tests/client/test_client.py
> Add "Content-Length: 0" on POST, PUT, PATCH if required.

- httpx/_types.py
- httpx/_utils.py
Refs #993, #985 
Makes more careful use of `typing.Union[str, bytes]` vs. `typing.AnyStr`.
Use `AnyStr` where we'd expect the types to be the same across everything in the signature. Eg. `typing.Mapping[AnyStr, AnyStr]` means "choose either str or bytes here, but be consistent.".
Resolves an issues where mypy errors with a really simple bit of `httpx` usage...
**example.py**
```python
import httpx
headers = {"content-type": "example"}
httpx.Headers(headers)
```
**MyPy**
```shell
$ venv/bin/mypy example.py 
example.py:5: error: Argument 1 to "Headers" has incompatible type "Dict[str, str]"; expected "Union[Headers, Dict[Union[str, bytes], Union[str, bytes]], Sequence[Tuple[Union[str, bytes], Union[str, bytes]]], None]"
Found 1 error in 1 file (checked 1 source file)
```
> Use AnyStr where appropriate

- CHANGELOG.md
- httpx/__version__.py
Related: https://github.com/encode/httpcore/pull/99
* Include explicit "Content-Length: 0" on POST, PUT, PATCH if no request body is used. (Pull #995)
* Add `http2` option to `httpx.Client`. (Pull #982)
* Tighten up API typing in places. (Pull #992, #999)
> Version 0.13.2

- tests/client/test_async_client.py
- tests/client/test_client.py
Refs https://github.com/encode/httpx/issues/650
We have still 3 issues in this file:
```
tests/client/test_async_client.py:29: error: Argument 1 to "update" of "Headers" has incompatible type "Dict[str, str]"; expected "Union[Headers, Dict[Union[str, bytes], Union[str, bytes]], Sequence[Tuple[Union[str, bytes], Union[str, bytes]]], None]"
tests/client/test_async_client.py:148: error: Argument "headers" to "post" of "AsyncClient" has incompatible type "Dict[str, str]"; expected "Union[Headers, Dict[Union[str, bytes], Union[str, bytes]], Sequence[Tuple[Union[str, bytes], Union[str, bytes]]], None]"
```
In above two test we defined headers like:
`headers = {"Custom-header": "value"}`
`headers = {"Expect": "100-continue"}`
which have type `Dict[str, str]` and I think they are valid type based …
> Added type annotation for tests/client/test_async_client.py

- httpx/_client.py
- tests/client/test_redirects.py
Fixes #822
I used `Scheme "blah" not supported` as the error message instead of `URL scheme must be "http" or "https".` used in other parts of the code. It makes more sense to show the actual invalid scheme since it's coming from the server and not something that the user specified.
I also tried the same test with `allow_redirects=False` but unfortunately when the response object is built, it needs a port which we can't derive from the custom scheme. Not sure how to solve this without changing the port definition of `Url` to allow a `None` port, ideas?
> Improve error when redirecting with custom schemes

- httpx/_client.py
Refs https://github.com/encode/httpcore/issues/44
In 12.x we used to default the keepalive_expiry to 5.0 to mitigate asyncio's flaky behaviour for checking the aliveness of the TCP connection. https://github.com/encode/httpx/blob/0.12.1/httpx/_dispatch/connection_pool.py#L89
We failed to continue to do so in 13.x when we switched to `httpcore`. This change reverts that.
> Include missing keepalive_expiry configuration

- CHANGELOG.md
- httpx/__version__.py
* Include missing keepalive expiry configuration. (Pull #1005)
* Improved error message when URL redirect has a custom scheme. (Pull #1002)
> Version 0.13.3

- docs/async.md
> Remove the UDS section from docs

- httpx/_models.py
- httpx/_transports/asgi.py
- httpx/_transports/wsgi.py
- tests/client/test_auth.py
- tests/client/test_cookies.py
- tests/client/test_headers.py
- tests/client/test_queryparams.py
- tests/client/test_redirects.py
- tests/test_multipart.py
- tests/test_timeouts.py
Since there were still a few uses of `dispatch` instead of `transport` in tests, pytest complained about deprecation warnings.
Same thing happened with `hard_limit` and `max_connections` from `httpx.PoolLimits`.
> Replace remaining occurrences of dispatch with transport

- docs/api.md
- httpx/_models.py
- tests/client/test_async_client.py
- tests/client/test_client.py
- tests/client/test_proxies.py
- tests/conftest.py
- tests/models/test_headers.py
- tests/models/test_url.py
Small work towards https://github.com/encode/httpx/issues/316, added a few tests to increase the coverage.
Also removed a couple of bits that were not used anymore.
> Increase test coverage, document Headers.copy(), misc cleanup

- docs/quickstart.md
- httpx/_client.py
- httpx/_models.py
- scripts/coverage
- tests/client/test_auth.py
- tests/client/test_proxies.py
- tests/client/test_redirects.py
- tests/concurrency.py
- tests/conftest.py
- tests/models/test_url.py
- tests/test_asgi.py
- tests/test_utils.py
- tests/test_wsgi.py
More work towards #316, continuation of #1003
After this is merged, the only remaining untested part will be `URLLib3Transport`.
Small note about `StreamContextManager`. [The only line not tested](https://github.com/encode/httpx/blob/8c84210555294ce10c681edae2df71627095a4e9/httpx/_client.py#L1543) is because the only usage of the context manager in an async environment is from [BaseClient.stream](https://github.com/jcugat/httpx/blob/e4048964d40fb1aec627c77d1c0adcd509fc1975/httpx/_client.py#L171) where it doesn't use the `close_client` parameter (and by default is `false`). The only other usage is from the [api.stream](https://github.com/jcugat/httpx/blob/e4048964d40fb1aec627c77d1c0adcd509fc1975/httpx/_api.py#L100) method but that is always called from a sync context, so the `__aexit__` …
> Increase test coverage - take 2

- tests/test_asgi.py
Refs https://github.com/encode/httpx/pull/998#issuecomment-643623769
Most ASGI tests were only being run on `asyncio`, but there's no reason we wouldn't also test on `trio` (the test app uses vanilla async APIs).
> Run ASGI tests on trio too

- httpx/_transports/asgi.py
Prompted by https://github.com/encode/httpx/pull/998#issuecomment-643623769, small bit of refactoring for `ASGITransport` to help reduce the diff there. I think these are valid readability improvements any case.
- Unify `typing` import style.
- Declare related variables in logical groups.
- Cleanup any unnecessary `nonlocal`'s
- Add some comments on how everything is split.
> Refactor ASGITransport.request()

- httpx/_models.py
- httpx/_transports/urllib3.py
- httpx/_transports/wsgi.py
- tests/client/test_headers.py
- tests/client/test_redirects.py
- Use `list(iterable)` for converting to a list rather than `[item for item in iterable]`
- Use dict comprehension rather than a list comprehension wrapped in `dict()`
> Improve list/dict comprehensions

- httpx/_transports/asgi.py
- scripts/check
- scripts/lint
- setup.cfg
See https://timothycrosley.github.io/isort/CHANGELOG/
isort removed the flags `--recursive` and `--apply`. They are the default behavior in isort v5.
> Make isort configuration compatible with isort v5

- httpx/_auth.py
- httpx/_config.py
Dont strip whitespace from base64 strings. Whitespace characters are not included in base64 character set, so AFAIK it should be impossible for `b64encode` output to contain them.
> Remove needless whitespace strips

- requirements.txt
While reviewing https://github.com/encode/httpx/pull/1050 I noticed that `isort` is not pinned to the major version like it was done in httpcore's PR https://github.com/encode/httpcore/pull/111. I think it's a good idea to have it in both.
Related to this, should we pin all the development dependencies to strict versions and let someting like dependabot keep them updated? That way we would avoid breakages like what happened here: https://github.com/encode/httpx/pull/1048#issuecomment-653781722
> Pin isort version

- httpx/_models.py
- tests/client/test_redirects.py
**Motivation**
`Response.next()` is documented in the [developer docs](https://www.python-httpx.org/api/#response) but did not actually exist yet.
> Add missing `Response.next()`

- httpx/_types.py
- scripts/check
- tests/client/test_async_client.py
- tests/client/test_auth.py
- tests/client/test_client.py
- tests/client/test_cookies.py
- tests/client/test_headers.py
- tests/client/test_properties.py
- tests/client/test_proxies.py
- tests/client/test_queryparams.py
- tests/client/test_redirects.py
- tests/conftest.py
- tests/test_api.py
- tests/test_config.py
- tests/test_content_streams.py
- tests/test_multipart.py
- tests/test_status_codes.py
Closes #650
Finally get us to enable `mypy` on `tests/` :-)
This PR consists in:
- Updating `scripts/check` so that mypy is also run on the `tests/` directory.
- Fixing or silencing any type errors in tests to make mypy pass.
> Type check tests

- httpx/__init__.py
- httpx/_client.py
- httpx/_config.py
- httpx/_models.py
- httpx/_transports/asgi.py
- httpx/_transports/urllib3.py
- httpx/_transports/wsgi.py
- httpx/_utils.py
- tests/client/test_async_client.py
- tests/client/test_client.py
- tests/test_exceptions.py
* Drop `ASGIDispatch`, `WSGIDispatch`, which has been replaced by `ASGITransport`, `WSGITransport`.
* Drop `dispatch=...` on client, which has been replaced by `transport=...`
* Drop `soft_limit`, `hard_limit`, which have been replaced by `max_keepalive` and `max_connections`.
* Drop `Response.stream` and `Response.raw`, which have been replaced by `aiter_bytes` and `aiter_raw`.
* Drop internal usage of `as_network_error` in favour of `map_exceptions`.
> Drop deprecated API

- httpx/_client.py
Drop errors for obsolete `proxies=...` usage.
> Drop deprecated proxies API

- httpx/_client.py
- httpx/_models.py
- httpx/_types.py
- tests/models/test_queryparams.py
Ensures marginally more consistent behaviour, eg...
```python
client.params = None
```
> Support QueryParams(None)

- httpx/_client.py
- tests/client/test_proxies.py
Move the following into private API space...
* `.get_proxy_map`
* `.init_transport`
* `.init_proxy_transport`
* `.proxies`
* `.transport`
I believe I omitted these in #997 because some of the proxy test cases call into them, which meant these were less clear than the cases in that PR, but I figure we really do want them private in any case, and if we've got some test cases that track a bit of internal state, then well okay, let's live with that for now.
There's also a few attributes that are set in `BaseClient.__init__` that look like contenders here, but I think we should treat those as a separate PR, so...
* `self.base_url` - Potentially modify this to a property setter / getter style, but not 100% obvious?
* `self.auth` - Potentially modify this to a property setter / getter style, but …
> More public API tightening

- httpx/_client.py
- tests/client/test_client.py
As discussed in #1025, this is a simple fix to prevent HSTS on single-label domains like Docker hostnames, while a decision is made about if HSTS should be part of httpx or not.
I've added a separated unit test for this, that'll be easy to drop if it's not needed.
Cheers 👋
> Skip HSTS preloading on single-label domains

- httpx/_client.py
- httpx/_exceptions.py
Refactors `map_exceptions` to also allow optional `**kwargs` which are passed to the new exception.
This is useful for us because the `httpcore` exception classes don't have an associated `request` because the model doesn't exist at that layer, but the equivelent `httpx` exception classes all do have an associated `request`.
As a result we can now do...
```python
with map_exceptions(HTTPCORE_EXC_MAP, request=request):
http_version, status_code, reason_phrase, headers, stream = transport.request(...)
```
Without having to do any extra dancing around re-catching the raised exception and setting the request.
> Refactor map_exceptions

- httpx/_auth.py
- httpx/_client.py
Minor enhancement.
Include the `request` instance where possible on exceptions, and use helpful error messaging.
> Include 'request' on TooManyRedirect and RequestBodyUnavailable

- httpx/_client.py
- httpx/_models.py
- httpx/_utils.py
- tests/client/test_async_client.py
- tests/client/test_client.py
- tests/models/test_requests.py
- tests/models/test_url.py
This PR pushes all `url.scheme` and `url.host` checking down into the `._transport_for_url` method.
This allows us to drop the `allow_relative` flag on the `URL` class, and instead just always allow relative URLs, up until the point that we're looking up a transport instance, at which point we enforce HTTP/HTTPS.
There are two benefits here...
* `allow_relative=...` wasn't really ever intended as a bit of public API, we just happened to be relying on it ourselves. It's cleaner for our API for allow eg `httpx.URL("")` as a valid relative URL, without having to explicitly enable it. But we *do* still want to raise an error if you attempt to issue a request with it.
* This change is a necessary pre-requisite for #954, since we don't necessarily want to hard-code enforce `http`/`https` …
> Drop `URL(allow_relative=bool)`

- httpx/_client.py
- httpx/_models.py
- httpx/_utils.py
- tests/client/test_proxies.py
- tests/client/test_redirects.py
- tests/models/test_requests.py
- tests/models/test_url.py
- tests/test_config.py
This PR changes `URL.port` from `int` to `Optional[int]`.
Previously any non http/https URL without an explicit port component would raise an error if `url.port` was accessed.
Now `url.port` is optional, and only returns any explicitly included port in the URL, without also trying to use a scheme-default if one is not present.
This is important because...
1. URL is more generically useful. Eg. `URL('ftp://www.example.com').port == None` which makes more sense than `KeyError("ftp")`.
2. This is a precursor to #954, since the only point we're now enforcing http/https schemes on URLs is strictly inside `_transport_for_url`, rather than at any point in the codebase that accesses `url.port`.
(Yes, it's a little bit fiddly)
> URL.port becomes Optional[int]

- scripts/coverage
- tests/client/test_async_client.py
- tests/client/test_client.py
* Add coverage onto missing line in `Response.next()`
* Exclude `URLLib3Transport` from coverage.
* Enforce 100% coverage elsewhere.
> Full coverage, with exception of URLLib3Transport

- httpx/_config.py
Tiny refactoring. `Proxy._build_auth_header` should be a private method.
> Keep Proxy._build_auth_header as a private method

- httpx/_auth.py
The only public API on any of our auth classes should be the `.auth_flow(...)` method.
This refactoring strictly moves methods/attributes to private names, as well as refactoring the `DigestAuth` implementation slightly so that `_DigestAuthChallenge` is now just a simple data holder.
From a user POV this is really just a private bit of refactoring, but it's good to be 100% clear that the internals of any of our auth implementations should be considered strictly opaque.
> Tighten public API on auth classes

- httpx/_transports/urllib3.py
Drop `proxy` argument that has been accidentally left over on `URLLib3Transport`.
It's not used anywhere, and it's not relevant since we seperate `URLLib3Transport` and `URLLib3ProxyTransport` classes.
> Drop extraneous `proxy` argument on `URLLib3Transport`.

- httpx/__init__.py
- httpx/_models.py
- httpx/_status_codes.py
- tests/test_status_codes.py
For consideration.
Currently we're exposing both `httpx.StatusCodes` and `httpx.codes` for working with status codes.
We're [only documenting `httpx.codes`](https://www.python-httpx.org/quickstart/#response-status-codes), and we probably only want a single canonical name here, right?
The documentation could also do with being expanded, at the very least in the API section.
Usages are like...
```python
>>> httpx.codes.OK
<codes.OK: 200>
>>> httpx.codes.OK == 200
True
>>> httpx.codes.get_reason_phrase(200)
'OK'
>>> httpx.codes.is_error(400)
True
>>> httpx.codes.is_redirect(400)
False
>>> httpx.codes.is_client_error(400)
True
>>> httpx.codes.is_server_error(400)
False
>>> httpx.codes(200).phrase
'OK'
>>> httpx.codes(200).value
200
```
> Single consistent name for status codes

- httpx/_client.py
- httpx/_utils.py
- requirements.txt
- tests/client/test_proxies.py
- tests/test_utils.py
This pull request refactors our URL matching for proxy lookups.
It adds a utility class `URLMatcher` that handles matching against the [proxy keys that we currently support](https://www.python-httpx.org/advanced/#http-proxying).
It's best explained through some examples...
```python
>>> from httpx._utils import URLMatcher  # Private API, intended for internal usage only.
>>> pattern = URLMatcher("all")
>>> pattern.matches(httpx.URL("http://example.com"))
True
>>> pattern = URLMatcher("https")
>>> pattern.matches(httpx.URL("https://example.com"))
True
>>> pattern.matches(httpx.URL("http://example.com"))
False
>>> pattern = URLMatcher("https://example.com")
>>> pattern.matches(httpx.URL("https://example.com"))
True
>>> pattern.matches(httpx.URL("http://example.com"))
False …
```
> URL matching

- httpx/_transports/asgi.py
- httpx/_transports/wsgi.py
Prompted by https://github.com/encode/httpx/pull/998#issuecomment-664703591
Our `WSGITransport` and `ASGITransport` implementations now only use public API, which is beneficial for other folks implementing transports, and basing their work on these.
One thing that we *could* choose to further tweak here would be... `httpcore.SyncByteStream` and `httpcore.AsyncByteStream` provide a simple base implementation that allows users to pass `iterator`/`close` or `aiterator`/`aclose` parameters. That's actually a bit fiddly if you've just got a non-iterating bytestring that you want to pass. We might choose to also support passing plain bytes to the base implementation. So...
```python
"""
The base interface for request and response bodies.
Concrete implementations should subclass this class, and …
```
> Use public API only from transports

- httpx/_config.py
- tests/test_config.py
- tests/test_timeouts.py
For consideration, wrt. 1.0 API tightening.
Ensures that `httpx.Timeout(...)` must strictly include an explicit default.
Usages like `httpx.Timeout()` and `httpx.Timeout(read_timeout=5.0)` are no longer valid. The default value must be explicitly included. Eg. `httpx.Timeout(None)` and `httpx.Timeout(None, read_timeout=5.0)`.
Docstring on the class is:
Timeout configuration.
**Usage**:
`httpx.Timeout(None)` *No timeouts.*
`httpx.Timeout(5.0)` *5s timeout on all operations.*
`httpx.Timeout(None, connect_timeout=5.0)`  *5s timeout on connect, no other timeouts.*
`httpx.Timeout(5.0, connect_timeout=10.0)`  *10s timeout on connect. 5s timeout elsewhere.*
`httpx.Timeout(5.0, pool_timeout=None)` *No timeout on acquiring connection from pool. 5s timeout elsewhere.*
> httpx.Timeout must include a default

- httpx/_models.py
- tests/models/test_headers.py
- tests/models/test_queryparams.py
Nice sensible symmetry and expected behaviours across each of the following...
* `Headers.get`
* `Headers.get_list`
* `Headers.items`
* `Headers.multi_items`
* `QueryParams.get`
* `QueryParams.get_list`
* `QueryParams.items`
* `QueryParams.multi_items`
The following have been renamed, but the synonyms remain, and are now pending deprecation...
* `Headers.getlist()` -> `Headers.get_list()`
* `QueryParams.getlist()` -> `QueryParams.get_list()`
> Consistent multidict methods

- scripts/test
In practice I've actually found this far more annoying that useful.
I think our scripts are in pretty great shape at the moment.
Closes #950.
> Drop the auto-prompting 'do you want to run scripts/lint now'

- httpx/_client.py
- httpx/_utils.py
- tests/client/test_proxies.py
- tests/test_utils.py
Prompted by https://github.com/encode/httpx/issues/977#issuecomment-667072653 (which I agree with :-))
> (Note that I've renamed `URLMatcher` in this example case, since I think `httpx.URLPattern` might be a better name)
> Rename URLMatcher -> URLPattern

- httpx/_client.py
Refs #1066 
Setting `client.trust_env = <bool>` isn't valid since it won't change already-initialized transports, so this PR changes it to a read-only property.
Light breaking change potentially, but I don't think it makes sense to add a deprecation path with a setter here.
> client.trust_env becomes read-only

- httpx/_models.py
- tests/models/test_headers.py
Fixes #899
`Headers` inherits from `MutableMapping`, and part of implementing this protocol is returning "set-like views" in `.keys()`, `.values()` and `.items()` (similarly to how dicts do). Previously it was difficult (see #903), but since #1089 we have an internal `Headers._dict` which we can use to build and return native views.
Now `Headers` behave even more like a native mapping. :-)
> Make Headers.keys(), Headers.values() and Headers.items() return set-like views instead of lists

- docs/advanced.md
- httpx/_config.py
- tests/test_config.py
- tests/test_timeouts.py
Fixes #1093 
```python
httpx.Timeout(read_timeout=1, write_timeout=1, connect_timeout=5, pool_timeout=10)
```
Becomes:
```python
httpx.Timeout(read=1, write=1, connect=5, pool=10)
```
> Switch to more concise Timeout parameters

- docs/advanced.md
- httpx/__init__.py
- httpx/_client.py
- httpx/_config.py
- tests/client/test_client.py
- tests/test_config.py
- tests/test_timeouts.py
Fixes #1094
Change the following with gentle deprecation:
- `httpx.PoolLimits(...)` becomes `httpx.Limits(...)`
- `Client(pool_limits=...)` becomes `Client(limits=...)`
- `AsyncClient(pool_limits=...)` becomes `AsyncClient(limits=...)`
> Rename PoolLimits to Limits

- httpx/_utils.py
- tests/client/test_proxies.py
Follow up on #1118, Closes #1082
> Handle bare env proxy hostname gracefully

- httpx/_models.py
- tests/models/test_headers.py
- tests/models/test_queryparams.py
Pulled through from a nice catch in #1118
I'd assumed that we ought to pragma: nocover these cases, rather than test them, but on a second look this *does* seem to be the pragmatic option, so let's just roll with it.
Thanks to @j178 for this!
> Use get_list consistently

- httpx/_client.py
If either `app=...` or `transport=...` are passed explicitly, then no env-var proxies should be used.
Closes #1039
Eg.
```python
client = httpx.Client(app=my_flask_app)
client = httpx.Client(transport=httpx.AsyncTransport(my_starlette_app)
```
> Setting `app=...` or `transport=...` should bypass environment proxies.

- docs/advanced.md
- docs/environment_variables.md
Promted by https://github.com/encode/httpx/pull/927#issuecomment-667642611
Our current proxies documentation is a bit lacking, and not necessarily nudging users to use the most simple solution whenever possible (i.e. `Client(proxies="http://...")`), so I dived my head into the world of web proxies and came up with this updated documentation, which outlines:
- Basic usage examples.
- Authentication support.
- Detailed docs about how proxies are routed, and what we support.
- Advanced discussions on forwarding vs tunneling. (Which I _think_ basically boils down to "HTTPX does the right thing for 99% of use cases, and if you know what you're doing here's how you can force things".) I removed the "hide traffic from proxies" example because I don't think we're confident enough to provide any …
> Revamp proxies documentation

- docs/advanced.md
Follow-up for #1123, refs https://github.com/encode/httpx/pull/1123#issuecomment-667664713
> I think we could possibly(?) switch the "Routing algorithm overview" to something a bit more general, that makes it clear that more specific patterns are matched in preference to less specific patterns, without getting into talking about "algorithms" or being quite so specific about implementation details.
> Refine docs phrasing on proxy routing

- httpx/_exceptions.py
Closes https://github.com/encode/httpx/issues/1108, and following rationale in https://github.com/encode/httpx/pull/1083#issuecomment-667934688, which I'll repeat here...
I think there's probably also a decent case to make for *not* deprecating it at all, and instead keeping it as a base class, but *only* for `RequestError` and `HTTPStatusError`, so that...
```python
try:
response = httpx.get("https://www.example.com/")  # May raise a RequestError subclass
response.raise_for_status()  # May raise HTTPStatusError
except httpx.HTTPError as exc:
pass
```
Which means existing code all keeps working as expected, while still providing finer-grained classes where needed.
It's also more concise than the alternative...
```python
try:
response = httpx.get("https://www.example.com/")  # May raise a …
```
> Keep HTTPError as a base class for .request() and .raise_for_status()

- README.md
- docs/index.md
- httpx/_client.py
- setup.cfg
- setup.py
- tests/client/test_client.py
Maybe? See the rationale in #1102
Fixes #1102, closes #896
Essentially:
```python
>>> r = httpx.get('http://www.paypal.com')  # -> Now kept over HTTP rather than forced to HTTPS.
```
I suppose if we want to move forward with this we'd want it in 0.14, rather than 1.0, since it might be a small breaking change?
Since this was an always-on feature not controlled by any options, I can't think of a smooth deprecation path, but any ideas welcome!
> Drop HSTS Preloading

- httpx/_client.py
- httpx/_models.py
Another niggly bit of API cleanup, that's a hangover from past implementation details.
Now that the `URL()` class is agnostic to relative/absolute URLs, the keyword argument naming in `URL.join(relative_url=...)` isn't appropriate.
I think we can get away with a unilateral rename, given that it's not *really* a very end-user facing bit of API, and it'll be called out in the 0.14 release notes.
> Clean up keyword argument name, using URL.join(url=...), not URL.join(relative_url=...).

- docs/advanced.md
- httpx/_utils.py
- tests/client/test_proxies.py
> Raise warning if proxy key is eg. "all" instead of "all://".

- httpx/_client.py
- httpx/_models.py
- tests/client/test_client.py
- tests/client/test_properties.py
* Support no-argument invocation of `httpx.URL()`.
* Support `client.base_url = ...` as a property.
* Resolve `base_url` joining behaviour.
So, an alternative implementation that closes #846, prompted by work in #1117.
The implementation here handles this by...
* Always ensuring that `base_url` includes a trailing slash on the path. Eg. `https://www.example.com/subpath/`.
* Always stripping any leading `/` when joining relative URLs.
This ends up given the behaviours you'd naturally expect from `base_url` usage, and also supports dotted paths, eg `../foo/bar`
> Base URL improvements

- docs/compatibility.md
> Note on differences in proxy keys vs. `requests`

- httpx/_models.py
- tests/client/test_client.py
This is one of those niggly little API bits that have only ended up in here because of implementation details.
We're not using `url.is_ssl` anywhere in our codebase, and now that we're agnostic to protocols *except* at the transport layer, this API doesn't feel right. (Eg `ftps://...` is an SSL URL, but would return false here.)
If any users *are* using this, they should migrate to a more explicit `if url.scheme == "https":`.
> Deprecate `URL.is_ssl`

- httpx/_client.py
- httpx/_utils.py
- tests/test_utils.py
@tomchristie 
I'm sorry, I've missed that the changes from #1127 caused several warnings during test suite executing. I've fixed that
**UPD** Probably we can enhance CI adding `-W error` to the `pytest` invocation?
> Fixed warnings in unit tests suite, caused by #1127 PR

- httpx/_models.py
- tests/models/test_cookies.py
> Fix behaviour with multiple Set-Cookie headers

- docs/api.md
- httpx/_client.py
Hi, from a short discussion in Gitter, I expanded some docstrings in client methods. This is perhaps continuation to the closed #397.
I decided to offer a minimal change, as I've not really had the chance of asking your opinion on anything. I tried to stay close to the style you already have in place. That being said, I have some questions.
- Should the verb docstrings refer to the documentation of the corresponding verb in parameters instead of `request`, or should they contain full duplicate parameter lists? Or would you rather have no documentation in them?
- Should the docstrings be in root form (imperative? sorry, I'm not a native English speaker) or not? HTTPX uses both, I decided on root, which I do prefer, i.e. "send a request" instead of "sends".
Some additional points that I …
> Expand client docstrings

- CHANGELOG.md
- httpx/__version__.py
* The `httpx.URL(...)` class now raises `httpx.InvalidURL` on invalid URLs, rather than exposing the underlying `rfc3986` exception. If a redirect response includes an invalid 'Location' header, then a `RemoteProtocolError` exception is raised, which will be associated with the request that caused it. (Pull #1163)
* Handling multiple `Set-Cookie` headers became broken in the 0.14.0 release, and is now resolved. (Pull #1156)
> Version 0.14.1

- httpx/__init__.py
Set `__module__ = 'httpx'` on all our public API.
Primarily useful for classes that haven't declared a `__repr__` method, but might also improve the output of other code-introspection tooling?
Before:
```python
>>> httpx.DigestAuth(username='', password='')
<httpx._auth.DigestAuth object at 0x106682850>
```
After:
```python
>>> httpx.DigestAuth(username='', password='')
<httpx.DigestAuth object at 0x103529650>
```
> Set `__module__ = 'httpx'` on everything we expose via the public API.

- docs/advanced.md
Related to #984
Refs https://github.com/encode/httpcore/pull/100
> Advanced transport docs, with "local_address=..." example.

- httpx/_models.py
- tests/models/test_url.py
So that...
```python
url = httpx.URL("https://tom%40example.org:abc123%40%20%25@example.org")
url.username == "tom@example.org"
url.password == "abc123@ %"
```
And...
```python
url = httpx.URL("https://example.org").copy_with(username="tom@example.org", password="abc123@ %")
url == "https://tom%40example.org:abc123%40%20%25@example.org"
```
Closes #858
Closes #328
Need to also have a think about what *exact* behaviour we're expecting from `.path`, `full_path`, and `.query`, but can treat those separately.
> Handle URL quoting username and password components.

- httpx/__init__.py
Prompted by https://github.com/encode/httpcore/pull/156/commits/35ecd2274faf1fdd4a6218bc07839d96b9791d7b
> Make `name` in httpx.__init__ private

- httpx/_api.py
- httpx/_client.py
This PR sets default `allow_redirects` to `True`. It was `False` before this PR.
This will align our behavior with most other http request libraries, except for [Requests](https://requests.readthedocs.io/en/v0.8.4/api/#requests.request).
> Fix #1146 Set default allow_redirects to true

- docs/api.md
- httpx/_client.py
- tests/client/test_auth.py
Closes #1066 
Make `Client.auth` / `AsyncClient.auth` properties, so that `.auth` can be set using the same argument types and logic than passed on client init.
```python
client.auth = ("username", "p@ssw0rd")
response = client.get(...)  # Uses Basic Auth.
```
Implementation-wise, we split the existing `._build_auth(request, auth)` helper into `._build_auth(auth)` and `._build_request_auth(request, auth)`. The former converts `AuthTypes` to an `Optional[Auth]` and is used in the `.auth` setter as well as in `._build_request_auth()` to convert the request-level auth info.
> Add `Client.auth` setter

- httpx/_models.py
Remove a redundant `if hasattr(self, '_raw_stream')` check in the `Response` model code.
We *always* have a raw_stream instance attached to the response. The check is a relic of an older version of the codebase, where this wasn't always the case.
See the `Response.__init__` code for handling both the `None` and the not-`None` cases... https://github.com/encode/httpx/blob/cb620e67c76202e6f64d22e45fedc0eb7c41e69e/httpx/_models.py#L710-L713
> Drop redundant hasattr check

- README.md
- docs/advanced.md
- docs/api.md
- docs/async.md
- docs/index.md
- docs/quickstart.md
When code examples use the `>>>` IDLE shell, use `pycon` (short for `py`thon `con`sole) syntax instead of `python`, to fix/improve syntax highlighting.
For example:
```python
>>> async with httpx.AsyncClient() as client:
>>>     r = await client.get('https://www.example.org/')
>>> r
<Response [200 OK]>
```
```pycon
>>> async with httpx.AsyncClient() as client:
>>>     r = await client.get('https://www.example.org/')
>>> r
<Response [200 OK]>
```
Docs: https://pygments.org/docs/lexers/#lexers-for-python-and-related-languages
> Docs: Use pycon for Python console code blocks

- httpx/_models.py
- tests/conftest.py
- tests/test_exceptions.py
Fix #1188
Add `map_exceptions` to `Response.iter_raw` and `Response.aiter_raw`, making sure all `httpcore` exceptions are mapped.
And add a slow_stream response test to make sure `ReadTimeout` ocurred while the client is reading the response body, not in the request time.
> Map httpcore exceptions for `Response` read methods

- httpx/_exceptions.py
Closes #1172.
Instead of...
```python-traceback
$ venv/bin/python ./example.py 
File "./example.py", line 2, in <module>
r = httpx.get('https://www.example.org/')
File "/Users/tomchristie/GitHub/encode/httpx/httpx/_api.py", line 170, in get
trust_env=trust_env,
File "/Users/tomchristie/GitHub/encode/httpx/httpx/_api.py", line 96, in request
allow_redirects=allow_redirects,
File "/Users/tomchristie/GitHub/encode/httpx/httpx/_client.py", line 664, in request
request, auth=auth, allow_redirects=allow_redirects, timeout=timeout,
File "/Users/tomchristie/GitHub/encode/httpx/httpx/_client.py", line 694, in send
request, auth=auth, timeout=timeout, allow_redirects=allow_redirects,
File "/Users/tomchristie/GitHub/encode/httpx/httpx/_client.py", line 723, in …
```
> Include underlying httpcore exception tracebacks

- docs/advanced.md
- docs/compatibility.md
- httpx/_api.py
- httpx/_client.py
Closes #1195 
Should I add tests to cover these parameters in top-level API functions?
> Add `proxies` parameter to top-level API functions

- httpx/_api.py
Remove description about `head(..., allow_redirects=False)` (left by #1183)
> Cleanup docstring leftover for #1183

- httpx/_models.py
- httpx/_types.py
- tests/models/test_cookies.py
I changed `CookieTypes`, added the test as it's said in https://github.com/encode/httpx/issues/1209
> Made cookies construct-able from a list of tuples

- httpx/_client.py
- tests/client/test_async_client.py
- tests/client/test_client.py
Closes https://github.com/encode/httpx/issues/1145
Note that once #977 is addressed we'll be able to test the proxies case more elegantly.
We're not being clever here about "ensure other transports still close if an exceptions occurs during `__exit__` in one transport". (Or the other fiddly case, of ensuring the `__exit__` is called on any already `__enter__`'d transports, if an exception occurs during `__enter__`.)
I *think* we should probably treat that as a follow up, and it's *possible* that we might only want to do so once #977 is addressed.
I think thats probably an okay approach to take since it's not any *worse* than our existing behaviour, which anyway doesn't handle "ensure other transports still close if an exceptions occurs during `close` in one transport", and besides …
> Context managed transports

- tests/client/test_cookies.py
- tests/client/test_headers.py
- tests/client/test_properties.py
- tests/client/test_proxies.py
- tests/client/test_queryparams.py
- tests/client/test_redirects.py
- tests/models/test_queryparams.py
- tests/models/test_responses.py
- tests/models/test_url.py
* Prefer `import httpx` rather than using `from httpx import ...`.
* Prefer using `httpx.Client()` rather than `httpx.AsyncClient` unless there's a reason to be using async.
Required footprint for #1219 should be *much* smaller after this.
> Better test case consistency. Prefer `import httpx` and `httpx.Client`.

- tests/client/test_auth.py
- tests/test_asgi.py
- tests/test_multipart.py
As we discussed in https://github.com/encode/httpx/pull/1197#issuecomment-680770927 , it was decided to move the test refactoring out from https://github.com/encode/httpx/pull/1197
In this PR I added closing to all unclosed `AsyncClient` in the tests
> Closing AsyncClient in all tests (#871)

- httpx/_auth.py
- tests/client/test_auth.py
Closes #1234 by correctly treating WWW-Authenticate headers as possibly occurring multiple times, and only dealing with “Digest” headers, and just ignoring other types of authentications.
> Handle multiple auth headers correctly

- httpx/_decoders.py
- httpx/_exceptions.py
- httpx/_models.py
- tests/models/test_responses.py
- tests/test_decoders.py
Make the response's request parameter optional
Part of #1227
> Make the response's request parameter optional

- tests/test_asgi.py
Refactor ASGI tests slightly, for simplicity.
No real need for a `functools.partial` onto one of the ASGI applications.
> Minor test refactoring

- tests/test_multipart.py
Light bit of test case refactoring - use `httpx.Client` in multipart test cases.
> Use sync client in test cases

- httpx/_status_codes.py
To align with Python 3.9: https://docs.python.org/3.9/whatsnew/3.9.html#http
> HTTP status codes `103 EARLY_HINTS`, `418 IM_A_TEAPOT` and `425 TOO_EARLY` are added to http.HTTPStatus. (Contributed by Dong-hee Na in bpo-39509 and Ross Rhodes in bpo-39507.)
Source: https://github.com/python/cpython/blob/da52be47690da0d9f78d0dce9ee5c3e4dbef49e1/Lib/http/__init__.py
> Add "Early Hints" and "Too Early" to Status Codes

- tests/models/test_responses.py
- tests/test_decoders.py
Now that `request=...` is optional on response instances, we can drop it's usage in test cases, except in any cases where it is actually required by the test.
> Drop Response(..., request=...) style in test cases.

- httpx/_client.py
- tests/client/test_async_client.py
- tests/client/test_client.py
- tests/client/test_proxies.py
As a part of https://github.com/encode/httpx/issues/871 it has been decided to prevent `httpx.Client` and `httpx.AsyncClient` from sending requests after being closed. 
Closes #871
> Issue warning on unclosed `AsyncClient`.

- httpx/_client.py
- httpx/_models.py
- tests/client/test_headers.py
- tests/models/test_requests.py
Closes #1226
Creating a `Request` instance directly has neater more minimal header behaviour.
Only includes mandatory headers.
```python
request = httpx.Request("POST", "http://example.org", json={"test": 123})
assert request.headers == httpx.Headers({
"Host": "example.org",
"Content-Type": "application/json",
"Content-Length": "13",
})
```
Instead the default headers are on the client instance...
```python
>>> client = httpx.Client()
>>> print(client.headers)
Headers({'accept': '*/*', 'accept-encoding': 'gzip, deflate, br', 'connection': 'keep-alive', 'user-agent': 'python-httpx/0.14.2'})
```
Can include additional headers...
```python
>>> client = httpx.Client(headers={'Custom-Header': 'Custom'})
>>> print(client.headers)
Headers({'accept': '*/*', 'accept-encoding': 'gzip, deflate, br', …
```
> Header refinements

- httpx/_exceptions.py
Fixes #1252 
Choose this PR or #1254
> Fix HTTPError message attribute doc

- httpx/_models.py
- tests/models/test_url.py
Closes #1258 
Note: first contribution, so let me know if I'm missing anything
> Type error on invalid url type

- docs/environment_variables.md
Tiny docs refactor PR to change the "underline" headers to more usual "shebang" style for headers in our "Environment Variables" docs page (like we do everywhere lese).
Came to me while reviewing https://github.com/encode/httpx/pull/1257
> Use shebang-style headers in environment variables docs

- httpx/_client.py
- tests/client/test_redirects.py
Internal refactoring to swap the order in which we handle auth/redirects.
Needed because `request` event hooks ought to be triggered after any initial authentication is applied to the request, but should not re-occur after redirects.
The flow also just generally makes more sense to be now:
Create the request -> Apply any authentication -> Follow any redirects -> Send the request to the network
For the sake of reviews I haven't re-ordered the methods, but I'll issue a follow-up PR to this which will swap them around so that the code ordering follows the execution flow.
> Swap auth/redirects ordering

- docs/advanced.md
- httpx/_models.py
- tests/models/test_responses.py
Having found #1208, I tried to track last downloaded raw chunk of the response.
The question is:
1. should we also track decoded response chunks? I don't see any reason since decoded stream length might be vary from the raw stream length, and it has no bearing with downloading process (but may be I missed something)
> Add progress to streaming download

- httpx/_client.py
Very tiny refactor, following on from #1267.
Switches the order of `_send_handling_auth` and `_send_handling_redirects` in the codebase, so that they follow the flow of execution.
> Switch auth/redirect methods to follow flow of execution better

- httpx/_models.py
- httpx/_types.py
Having working on https://github.com/encode/httpx/issues/1275 in https://github.com/encode/httpx/pull/1280, I've got a reasonable comment (from @StephenBrown2) that the PR could be split into several one to reduce problems with review.
In this PR I:
1. made `Request.prepare` private
1. Changed `QueryParamTypes` so that `QueryParams` accepts `bytes`
> Refactoring of models api

- tests/client/test_auth.py
Follow up to https://github.com/encode/httpx/pull/1281 - refactors `test_auth.py` to use the nice `MockTransport` class.
Possible later follow ups here...
* We should switch over to a plain `import httpx`. (`test_auth.py` uses from `httpx import ...` for a bunch of stuff, where we're mostly now sticking with a style of `import httpx` in other test cases.)
* There's a bunch of test cases that are currently async, but could probably be plain sync cases, which we should prefer where possible.
> Refactor test_auth.py to use `MockTransport` class.

- docs/advanced.md
Noticed that there was a copy-pasta in the docs for #1246
> Fix function name in event hooks docs

- httpx/_content_streams.py
- httpx/_models.py
- tests/test_content_streams.py
- tests/test_multipart.py
Now that we have an `encode_response` function, it makes sense for `encode` to be `encode_request`.
> Refactor `encode` -> `encode_request`

- httpx/_models.py
- httpx/_types.py
- tests/utils.py
Related to #1091
Improving our support for instantiating a request instance, from the transport API.
* `method` may now be either `str` or `bytes`.
* `url` now supports passing a raw URL. `(bytes, bytes, Optional[int], bytes)`.
Working towards being able to do something like...
```python
class CustomTransport:
def request(self, method, url, headers, stream, timeout):
request = httpx.Request(method, url, headers, stream)
...
response = httpx.Response(...)
return response.raw
```
> Requests from transport API

- httpx/_client.py
- httpx/_utils.py
For instance, see requests... https://github.com/psf/requests/blob/967a05bfffcb68f97296eda197b062221c2ebc0d/requests/utils.py#L196
> NetRC lookups should use host, not host+port

- httpx/_client.py
Instead of re-populating the `Host` header in the client on redirects away from the origin, we instead just remove it.
This is neater since the header will be re-populated by the `Request` instance, so we've only got one place where we need logic around populating it correctly.
> Neater `Host` header logic on redirects

- httpx/_client.py
"Remove the Host header, so that a new one **with be** auto-populated" -> "Remove the Host header, so that a new one **will be** auto-populated"
> Resolve typo in code comment

- CHANGELOG.md
- httpx/__init__.py
- httpx/__version__.py
- httpx/_client.py
- httpx/_config.py
- httpx/_models.py
- httpx/_transports/asgi.py
- httpx/_transports/wsgi.py
- setup.py
- tests/client/test_auth.py
- tests/client/test_client.py
- tests/client/test_event_hooks.py
- tests/client/test_redirects.py
- tests/models/test_headers.py
- tests/models/test_queryparams.py
- tests/test_config.py
- tests/test_timeouts.py
- tests/utils.py
Pushing this up so that we can figure out what else we want to block a 0.15 release on.
At the moment my thoughts would be...
I *think* other stuff can wait for nice smaller increments in the 0.15.x series. The only remaining API *changes* expected at that point are the possible transport API -> transport API as a context manager switch, and some very minor review over all the model classes. (Note that `URL` is now complete in this regard.)
What do we think, and am I missing anything critical here?
* Added support for event hooks. (Pull #1246)
* Added support for authentication flows which require either sync or async I/O. (Pull #1217)
* Added support for monitoring download progress with `response.num_bytes_downloaded`. (Pull #1268)
* Added `Request(content=...)` for byte content, …
> Version 0.15.0

- README.md
- docs/index.md
* Drop 'chardet' from requirements mentions.
* Pin note should be `0.15.*`
> Update docs for 0.15

- httpx/_transports/asgi.py
- tests/test_asgi.py
In the ASGI scope, the `path` key [should be URL escaped](https://asgi.readthedocs.io/en/latest/specs/www.html#http-connection-scope)...
> `path` *(Unicode string)* – HTTP request target excluding any query string, with percent-encoded sequences and UTF-8 byte sequences decoded into characters.
Also, since 0.15.0 we're making sure to properly URL escape path components, so we're more likely to be bumping into this bug. Eg. in the test case included here we use... 
```python
url = httpx.URL("http://www.example.org/").copy_with(path="/user@example.org")
```
Which from 0.15.0 onwards will result in `"http://www.example.org/user%40example.org"`, which will trigger the ASGI bug.
> Fix ASGITransport path escaping

- CHANGELOG.md
- httpx/__version__.py
* ASGITransport now properly applies URL decoding to the `path` component, as-per the ASGI spec. (Pull #1307)
> Version 0.15.1

- docs/advanced.md
The old name `max_keepalive` was removed recently, so this updates the docs.
> update arg name to `max_keepalive_connections`

- CHANGELOG.md
- httpx/__version__.py
- httpx/_client.py
* Fixed `response.elapsed` property. (Pull #1313)
* Fixed client authentication interaction with `.stream()`. (Pull #1312)
> Version 0.15.2

- httpx/_client.py
Asynchronous ``httpcore`` streams do not have ``close()`` method, they provide ``aclose()``. Fixes #1315 .
> Check for proper method to close stream in asynchronous case

- CHANGELOG.md
- httpx/__version__.py
* Fixed connection leak in async client due to improper closing of response streams. (Pull #1316)
> Release 0.15.3

- requirements.txt
- scripts/lint
- setup.cfg
As of isort 5 seed-isort-config is no longer needed.
We can get rid of some explicit config too as it's now more clever.
> Remove seed-isort-config

- httpx/_models.py
- tests/models/test_responses.py
Closes #1323
When `Response` instances were being instantiated directly, and when using `content=<str>` the response body was not automatically being read.
```python
response = httpx.Response(200, content="Hello, world!")
assert response.status_code == 200
assert response.reason_phrase == "OK"
assert response.text == "Hello, world!"
assert response.headers == httpx.Headers(
{
"Content-Length": "13",
}
)
```
> Fix automatic .read() when Response instances are created with content=<str>

- .vscode/settings.json
- httpx/_models.py
- tests/models/test_headers.py
- tests/models/test_requests.py
- tests/models/test_responses.py
Allows comparison of headers with dict or list:
```
response = httpx.get(...)
assert response.status_code == 200
assert response.text == "Hello, world!"
assert response.headers == {"Content-Length": "13"} # True
assert response.headers == [("Content-Length", "13")] # True
```
Closes #1325
> Support header comparisons with dict or list.

- docs/api.md
- docs/compatibility.md
- httpx/_client.py
- httpx/_models.py
- tests/client/test_redirects.py
Currently when using `allow_redirects=False`, we have interfaces for `response.next()` and `response.anext()`,
which can be used to issue the next redirect request.
The intent of these is to mirror the interface from `requests`, which also has a `response.next`.
*However* It turns out that I've made an error in what I thought the interface we were mirroring does. When using `requests` with `allow_redirects=False`, the `response.next` *isn't* a callable. It's an optional request instance, that can be used with `client.send(...)` to send the next response.
Since one of our desired aims is for full parity with requests, we *ought* to be covering that API, and *not* the callable `.next` interface that we're currently exposing.
```python
request = …
```
> Add `response.next_request`

- .github/workflows/test-suite.yml
- setup.py
Python 3.9.0 final is expected on Monday, 2020-10-05, see https://www.python.org/dev/peps/pep-0596/#schedule
> Run tests against Python 3.9 and add trove classifier

- httpx/_client.py
- tests/client/test_async_client.py
- tests/client/test_client.py
Closes #1317
Closes #1332
Tighens up the client open/closed state by making it tri-state under the hood: `UNOPENED`/`OPENED`/`CLOSED`.
End result of the changes here, are that only the following styles are valid...
```python
client.request(...)
client.close()  # If omitted, this will be called on `__del__` with sync client, or raise a warning on `__del__` with async client.
```
Or...
```python
with httpx.Client() as client:
client.request(...)
```
Because we're tri-state now we can make sure that simply importing but not using a client won't raise errors.
(Because under the hood, the client is initially in an `UNOPENED` state.)
```python
client = httpx.AsyncClient()
```
* Clients may no longer used once closed. Calling `client.get(...)` and pals will raise a …
> Tighten client closed-state behaviour

- httpx/_models.py
- tests/models/test_url.py
Closes https://github.com/encode/httpx/issues/1311
There was a bug with processing an ipv6 address as a part of request URL.
What has been changed:
1. I implemented the functionality from https://github.com/encode/httpx/issues/1311#issuecomment-704224592
1. Also I found the problem in `URL` constructor. If we pass a `RawURL` with ipv6 as a host, then host should be enclosed by square brackets, otherwise `rfc3986.iri_reference(...)` won't process it
> Correctly handle ipv6 addresses as a part of URL

- httpx/_transports/asgi.py
- tests/test_asgi.py
Prompted by https://github.com/encode/starlette/issues/1067
> Force lowercase ASGI headers

- requirements.txt
- scripts/test
- setup.cfg
After encode/uvicorn#809 and https://github.com/encode/httpcore/pull/218 it would be great to introduce the same changes in `httpx`
> Replacing pytest-cov by coverage

- CHANGELOG.md
- httpx/__version__.py
* Support literal IPv6 addresses in URLs. (Pull #1349)
* Force lowercase headers in ASGI scope dictionaries. (Pull #1351)
> Version 0.16.1

- httpx/_transports/asgi.py
- tests/test_asgi.py
> Add raw_path to scope in ASGITransport

- tests/client/test_redirects.py
`AsyncClient` in this test case was not being closed cleanly.
> Close AsyncClient properly in `test_async_next_request`

- tests/conftest.py
Prompted by https://github.com/encode/httpx/pull/1364#issuecomment-715883069
Refs https://github.com/encode/uvicorn/issues/836
We're passing `host="localhost"`, which fails on uvicorn `0.12.2` (there's already a fix in `master` there for this: https://github.com/encode/uvicorn/pull/827), resulting in our test suite to hang (because the server fails to start, and we keep checking `server.ready` indefinitely).
This PR removes this flag entirely, since we actually don't need it. This means this PR can be merged regardless of uvicorn fixing support for non-IP `host` values. This should also get our CI builds to pass again.
> Drop unecessary host="localhost" in https_server fixture to fix CI build

- httpx/_client.py
- httpx/_models.py
- httpx/_multipart.py
- tests/test_multipart.py
I couldn't find a straight-forward way to test invalid values.
> Include invalid name/value when raising TypeError in DataField

- docs/advanced.md
- docs/compatibility.md
- docs/environment_variables.md
- docs/third-party-packages.md
Closes #1383
When interlinking in the docs, use relative links to the source markdown files, so that both the rendered docs, *and the documentation source files directly on GitHub* interlink correctly.
> Use relative links for interlinking markdown files in docs

- httpx/_transports/wsgi.py
Closes #1365
The WSGI `PATH_INFO` component should be unquoted, in the same way the ASGI `path` component is.
See current WSGI `PATH_INFO` handling...
https://github.com/encode/httpx/blob/f8f543057a9feb5330784401b5fed168c5288e36/httpx/_transports/wsgi.py#L86
And current ASGI `path` handling...
https://github.com/encode/httpx/blob/f8f543057a9feb5330784401b5fed168c5288e36/httpx/_transports/asgi.py#L92
> WSGI 'PATH_INFO' should be URL unquoted

- httpx/_client.py
- httpx/_config.py
- tests/test_config.py
Closes #1395
We do *also* want #1302, but I think it makes sense to include `keepalive_expiry` in the `Limits` config either ways around.
> Add keepalive_expiry to Limits config

- httpx/_client.py
- tests/client/test_client.py
**Update**: Prompted by #1405 
An alternative to #1406 that tweaks URL merging to operate on `.raw_path`, rather than `.path`. Rationale: `.path` is URL-decoded and might swallow pre-existing `%2F` characters into `/`. On the other hand `.raw_path` doesn't do URL-decoding, so it is suitable for handling encoded slashes as well.
> Properly preserve encoded slashes when using `base_url`

- httpx/_models.py
- test.py
- tests/models/test_cookies.py
Simple test:
```python
import httpx
if __name__ == '__main__':
r = httpx.get('https://www.example.org/')
r.cookies.set(name="foo", value="bar", domain="http://blah.com")
r.cookies.set(name="fizz", value="buzz", domain="http://hello.com")
print(repr(r.cookies))
```
Results in:
```
<Cookies[<Cookie foo=bar for http://blah.com />, <Cookie fizz=buzz for http://hello.com />]>
```
Closes #1377
> Add repr to Cookies for displaying available cookies

- docs/compatibility.md
Prompted by some discussion on Gitter:
A small addition to our Requests compatibility guide to discuss differences in request/response encodings.
Ideally the bulk of this should live in a "Discussions" section of the docs ("How does HTTPX deal with encodings?"), but until we have that then I guess it's okay to have this documented here. :-)
We do have a lengthy docstring in the code about this, but it's good to have some words in the public docs as well:
https://github.com/encode/httpx/blob/27df5e49c7a97a17f68862a3fa901c11e30a4b5a/httpx%2F_decoders.py#L248-L269
> Document content encoding differences with Requests

- docs/compatibility.md
In `requests`, event hook callbacks can mutate response/request objects. In HTTPX, this is not the case.
Added text to address this difference, and added a link to the best alternate HTTPX offers in this circumstance.
More context:
https://github.com/encode/httpx/issues/1343#issuecomment-703223097
> Updates compatibility guide to address event hooks

- docs/async.md
Add curio docs in Supported async environments as new sub-section below AsyncIO, Trio
Fixes #1418
> Add curio docs in Supported async environments

- docs/contributing.md
Tiny tweak to our contributing docs: there were still mentioning Travis CI even though we switched to GitHub Actions.
> Remove stale reference to "Travis" in contributing guide

- docs/advanced.md
- docs/troubleshooting.md
- mkdocs.yml
Prompted by https://github.com/encode/httpx/issues/1433#issuecomment-749012975
We're getting a bunch of related / similar / duplicate questions about common proxies gotchas. This PR introduces a new "Troubleshooting" page to the docs, as well as two entries that address two questions we've been having for some time:
* "`The handshake operation timed out`" on HTTPS requests when using a proxy (#1412, #1433, and more previous issues + questions in the community chat)
* Error when making requests to an HTTPS proxy (#1424, #1428)
> Add troubleshooting guide, with initial proxies entries

- README.md
- docs/index.md
Updating Note related to current beta state of project in `README.md`.   
New estimate for v1 release is set to `sometime in 2021`.
> Update README to reflect new estimate for v1.0 release

- setup.py
Makes it easy to find out about changes, and it gets a little "present" icon, for example https://pypi.org/project/django-linear-migrations/
> Add Changelog link to PyPI page

- httpx/_transports/wsgi.py
- tests/test_wsgi.py
https://www.python.org/dev/peps/pep-3333/#environ-variables
> SERVER_NAME, SERVER_PORT
> \---\---\---\---\---\---\---\---\---\---\---\---\---\---\---\---\---\---\---\---
> When HTTP_HOST is not set, these variables can be combined to determine a default. See the URL Reconstruction section below for more detail. SERVER_NAME and SERVER_PORT are required strings and must never be empty.
Fixed #1468
> Handle default ports in WSGITransport

- docs/environment_variables.md
It's easy to believe that any .pem files there will get picked up automatically, but that's not the case. I've reused the link that the Python docs use in https://docs.python.org/3/library/ssl.html#ssl.SSLContext.load_verify_locations.
Quoting a coworker: "weird thing is that we tried to use `SSL_CERT_DIR` and it didn't work, but `SSL_CERT_FILE` did".
> Explain SSL_CERT_DIR specific format

- httpx/_transports/mock.py
- tests/client/test_async_client.py
Prompted by https://github.com/encode/httpx/pull/1401#issuecomment-756465514
Allow usages like...
```python
async def hello_world(request):
return httpx.Response(200, text="Hello, world!")
transport = httpx.MockTransport(hello_world)
async with httpx.AsyncClient(transport=transport) as client:
response = await client.get("https://www.example.com")
assert response.status_code == 200
assert response.text == "Hello, world!"
```
> Allow handler to optionally be async when MockTransport is used with AsyncClient

- httpx/_client.py
- tests/client/test_async_client.py
Now, clients can catch an exception that occurs during close.
[closes #1463]
> map_exceptions in request.aclose()

- mkdocs.yml
Right now our docs is broken wrt syntax highlighting: code blocks render as "plain text".
Turns out a fair bit has changed in the world `mkdocs-material` and Markdown extensions since we last deployed docs. MkDocs-Material went from 5.* to 7.*, and circa 6.2.* it seems to have migrated from `codehilite` to [Highlight](https://facelessuser.github.io/pymdown-extensions/extensions/highlight/) as their primary syntax highlighting engine. As a result the CSS class changed from `.codehilite` to `.highlight` — hence the fix in this PR to get code blocks highlighting back. :-)
> Fix docs syntax highlighting

- setup.py
The version 0.12.0 of httpcore is not compatible. When this version is installed, all the tests using `httpx.Client()` will fail with the following error
`AttributeError: 'Client' object has no attribute '_transport'`
> Incompatible with httpcore 0.12.0

- httpx/_types.py
> CertTypes `keyfile` and `password` should be Optional types.

- docs/compatibility.md
- docs/quickstart.md
`HEAD` is changed to follow redirects by default in GH-1183. Update the corresponding description in the doc.
> Fix redirect description about HEAD

- httpx/_client.py
- httpx/_decoders.py
- httpx/_exceptions.py
- httpx/_models.py
- httpx/_transports/base.py
- httpx/_transports/default.py
- tests/client/test_async_client.py
- tests/client/test_redirects.py
- tests/conftest.py
- tests/models/test_responses.py
- tests/test_decoders.py
- tests/test_exceptions.py
Follow-on to #1522
Transports should now raise `httpx` exception classes, rather than `httpcore` exception classes.
* The httpcore -> httpx exception mapping now *only* occurs within the `HTTPTransport()` class, which uses the  `httpcore` library.
* The `RequestError` exceptions no longer require a request argument at the point of instantiation. The client class ensures that any `RequestError` raised by a transport will have a `request` attribute attached to it.
* Transports now use plain byte iterables, with `extensions['close']`/`extensions['aclose']` for any optional close callback.
> Push httpcore exception wrapping out of client into transport

- httpx/_models.py
- httpx/_transports/base.py
- httpx/_transports/default.py
The Transport API extensions `reason_phrase` and `http_version` are now mandated as being bytes.
> Extensions reason_phrase and http_version as bytes

- httpx/_client.py
- tests/client/test_redirects.py
More consistent structuring for ensuring we don't leave unclosed responses hanging in exception cases.
Essentially, any time we're internally calling a method that returns a response, we want to follow that with a `try...except...` block, and ensure we close the response if an exception occurs.
This pull request neatens up that behaviour, and likely closes some unseen edge cases as a result.
> Neaten up our try...except structure for ensuring responses

- httpx/_client.py
- httpx/_models.py
- tests/client/test_client.py
- tests/models/test_url.py
Use a more resilient implementation for merging against a `base_url`.
Prevents the merge URL from being treated as absolute in some cases.
Eg, previously...
```python
>>> client = httpx.Client(base_url="https://example.org/some/path")
>>> client.build_request("GET", "/sub:path")
<Request('GET', 'sub:path')>
```
Is now fixed...
```python
>>> client = httpx.Client(base_url="https://example.org/some/path")
>>> client.build_request("GET", "/sub:path")
<Request('GET', 'https://example.org/some/path/sub:path')>
```
Also now deals more correctly with joining relative URLs, eg...
```python
httpx.URL("/path/to/somewhere/").join("../somewhere-else")
URL('/path/to/somewhere-else')
```
Closes #1498
> Fix some cases of merging with base_url

- docs/advanced.md
[Simple docs typo PR]
Update the docs to match default value of `max_keepalive` as given in the variable `DEFAULT_LIMITS` in `_config` at https://github.com/encode/httpx/blob/master/httpx/_config.py#L359
> Fix typo in docs to match `max_keepalive` default

- httpx/_content.py
- httpx/_models.py
- httpx/_multipart.py
- httpx/_utils.py
- tests/test_content.py
- tests/test_multipart.py
Closes #1500
Allow integers, floats, booleans, and None as valid values for URLEncoded and Multipart content.
Use `"true"` and `"false"` string literal for booleans. `""` for the None case. And `str(value)` for anything else.
> Handle `data={"key": [None|int|float|bool]}` cases.

- httpx/_transports/default.py
- tests/client/test_async_client.py
- tests/client/test_client.py
Seems like a typo sneaked by in the `AsyncHTTPTransport` 😉 
I couldn't find a better way of testing it than asserting that the `http_version` was passed from the `server` all the way up to the `resonse.extensions`.
> Fix extenstions typo in AsyncHTTPTransport

- docs/async.md
> added docs for startup/shutdown of ASGI apps

- docs/third_party_packages.md
> Add httpx-auth and pytest-httpx to third party documentation

- LICENSE.md
This is actually just because it niggles me that it's the only file displayed in the interface that doesn't have an associated PR against the latest change on it. 🤣
> Fix up license whitespacing

- docs/advanced.md
- httpx/__init__.py
- httpx/_client.py
- httpx/_content.py
- httpx/_models.py
- httpx/_multipart.py
- httpx/_transports/asgi.py
- httpx/_transports/base.py
- httpx/_transports/default.py
- httpx/_transports/mock.py
- httpx/_transports/wsgi.py
- httpx/_types.py
- tests/test_content.py
This pull request allows us to compare the following two alternatives...
* The HTTPX Transport API, using `stream` as a plain primitive `Iterable[bytes]`/`AsyncIterable[bytes]`, with `close`/`aclose` extensions for handling close callbacks. 
* The HTTPX Transport API, using simple `httpx.SyncByteStream`/`httpx.AsyncByteStream` interfaces for streams.
Note that the `request.stream` and `response.stream` interfaces also change as a result of this.
The pros of this approach are that the Transport API presents a more natural interface...
**Before:**
```python
with httpx.HTTPTransport() as transport:
status_code, headers, stream, extensions = transport.handle_request(
method=b'GET',
url=(b'https', b'www.example.com', 443, b'/'),
headers=[(b'Host', b'www.example.com')],
stream=[],
extensions={} …
```
> Stream interface

- httpx/_api.py
- httpx/_client.py
Added to documentation to show that `verify` can be an `ssl.SSLContext`, as this is not immediately obvious from the developer interface documentation due to the lack of type hints on the signature that is rendered.
> Update `verify` parameter description

- httpx/_client.py
- httpx/_models.py
- tests/client/test_async_client.py
- tests/client/test_client.py
- tests/models/test_responses.py
Stop supporting `Response(on_close=...)` in the API, which really is a bit of niggly implementation detail that's being unnecessarily exposed.
I figure we can get away without any deprecation period on this one with a 0.18 bump, since it really has only every been intended as an implementation detail, rather than user-facing API.
Instead, once we've got a response instance we upgrade the stream on it to a bound stream, that closes the timer once it's elapsed.
Figure this is worth doing, since *API is king*, and we really don't want that public API close callback there if we can avoid it.
> Drop 'Response(on_close=...)' from API

- docs/compatibility.md
- httpx/_content.py
- tests/client/test_auth.py
- tests/models/test_requests.py
- tests/test_content.py
Currently we're supporting `data=<bytes|text|bytes-iter|async-byte-iter>` for requests compatibility,
although we're recommending against it.
I think we ought to escalate this into a more formal deprecation warning, and then remove it entirely.
Having a stricter, more consistent API here feels like a clear improvement to me vs `requests`.
> Escalate the distinction between `data=...` and `content=...` to be stricter.

- httpx/_models.py
Had a look at the attributes of `Response` while thinking about https://github.com/encode/httpx/discussions/1562. Looks like `call_next` is not used for anything.
> Drop Response.call_next

- README.md
- docs/index.md
- httpx/_api.py
- httpx/_client.py
- httpx/_compat.py
- setup.py
Possible refactoring that is worth our consideration.
Somewhat related to #998, since we also use `contextlib.asynccontextmanager` there, so both that pull request and this one lean on the `async_generator` package for 3.6 backport support.
> Drop StreamContextManager in favour of `contextlib.contextmanager`/`asynccontextmanager`

- httpx/_exceptions.py
- httpx/_models.py
- tests/models/test_requests.py
Minor user-experience & consistency tweak.
For non-streaming cases we should pre-load `request.content`.
This leads to neater consistency between requests/responses, and ensures that the request content is readily accessible to introspection.
```pycon
>>> r = httpx.Request("POST", "https://www.example.com", content=b'...')
>>> r.content  # Previously this would raise 'httpx.RequestNotRead'
b'...'
```
```pycon
>>> r = httpx.Request("POST", "https://www.example.com", json={"example": "payload"})
>>> r.content  # Previously this would raise 'httpx.RequestNotRead'
b'{"example": "payload"}'
```
```pycon
>>> r = httpx.Request("POST", "https://www.example.com", content=[b'.' for i in range(3)])
>>> r.content
File "<stdin>", line 1, in <module>
File …
```
> For non-streaming cases, populate `request.content` automatically.

- docs/compatibility.md
- httpx/_api.py
- httpx/_client.py
- tests/client/test_cookies.py
Closes #1404
Documentation here is as follows...
---
If using a client instance, then cookies should always be set on the client rather than on a per-request basis.
This usage is supported...
```python
client = httpx.Client(cookies=...)
client.post(...)
```
This usage is deprecated...
```python
client.post(..., cookies=...)
```
We prefer enforcing a stricter API here because it provides clearer expectations around cookie persistence, particularly when redirects occur.
> Deprecate per-request cookies

- httpx/_models.py
- tests/models/test_url.py
Refs #1275
Throughout our URL model we're differentiating neatly between byte-wise cases and str cases.
We're always using bytes when escaping is not applied, and str when escaping *is* applied.
Eg...
```python
url = httpx.URL("https://jo%40email.com:a%20secret@example.com:1234/pa th")
assert url.username == "jo@email.com"
assert url.password == "a secret"
assert url.userinfo == b"jo%40email.com:a%20secret"
assert url.path == "/pa th"
assert url.raw_path == b"/pa%20th"
```
This pull request is a proposal for treating IDNA domain names similarly, so...
```python
url = httpx.URL("https://müller.de:80")
assert url.host == "müller.de"
assert url.raw_host == b"xn--mller-kva.de"
```
For API consistency this also necessarily results in `url.netloc` becoming a byte interface, which actually makes …
> Differentiate between 'url.host' and 'url.raw_host'

- httpx/__init__.py
- httpx/_client.py
- httpx/_status_codes.py
- httpx/_utils.py
- tests/client/test_client.py
- tests/client/test_proxies.py
- tests/test_status_codes.py
The following API changes have been issuing deprecation warnings since 0.17.0 onwards, and are now fully deprecated...
* You should now use `httpx.codes` consistently instead of `httpx.StatusCodes`.
* Use `limits=...` instead of `pool_limits=...`.
* Use `proxies={"http://": ...}` instead of `proxies={"http": ...}` for scheme-specific mounting.
> Escalate 0.17 deprecation warnings to becoming fully deprecated.

- httpx/_models.py
- tests/models/test_queryparams.py
Tweak QueryParams implementation internally, so that we're just using a single data-structure.
`._dict = {k: [v1, v2, v3]}`
Instead of a pair of data structures...
`._dict = {k: v1}`
`._list= [(k, v1), (k, v2), (k, v3)]`
Note that this also resolves a minor minor buglette:
The `QueryParams.get()` docstring states *"Get a value from the query param for a given key. If the key occurs more than once, then only the first value is returned."*
However, prior to this change, for cases with multiple values, the *last* value was being returned.
> Tweak QueryParams implementation

- httpx/_client.py
- httpx/_models.py
- httpx/_utils.py
- tests/models/test_queryparams.py
As outlined in #1599.
Refs #1275.
Drop support for `QueryParams.__setitem__` and `QueryParams.update()` in favour of an immutable-only interface, in line with our `URL` design. All manipulation methods now return new QueryParams instances:
```python
q = httpx.QueryParams()
q = q.set("a", "123")
assert q == httpx.QueryParams("a=123")
q = q.add("a", "456")
assert q == httpx.QueryParams("a=123&a=456")
q = q.remove("a")
assert q == httpx.QueryParams("")
q = q.merge({"b": "789"})
assert q == httpx.QueryParams("b=789")
```
I've opted for a hard deprecation here, with `.update()` raising a RuntimeError, because immutability vs. mutability isn't something we ought to go "we're halfway there" on.
> Immutable QueryParams

- httpx/_models.py
- tests/models/test_url.py
Neaten out the URL interface as follows:
* Support `httpx.URL(**kwargs)`
* Support `url.copy_with(params=...)`
* Support `url.params`
* Support `url.copy_set_param()`, `url.copy_add_param()`, `url.copy_remove_param()`, `url.copy_merge_params()`
For instance:
```python
u = httpx.URL("https://www.example.com/", username="tom@gmail.com", password="123 456")
assert u == "https://tom%40gmail.com:123%20456@www.example.com/"
u = httpx.URL(scheme="https", host="www.example.com", path="/')
assert u == "https://www.example.com/"
u = httpx.URL("https://www.example.com/")
u = u.copy_with(params={"search": "is green a colour?"}
assert u == "https://www.example.com/?search=is+green+a+colour%3F"
u = httpx.URL("https://www.example.com/?a=123")
assert u.params == httpx.QueryParams({"a": "123"})
u = …
```
> Expand URL interface

- httpx/_models.py
- tests/client/test_proxies.py
- tests/models/test_url.py
Normalize the port component of URLs, so that...
```python
assert httpx.URL("http://www.example.com") == httpx.URL("http://www.example.com:80")
print(httpx.URL("http://www.example.com:80"))  # URL('http://www.example.com')
```
Following this part of the WHATWG spec...
> If url’s port is url’s scheme’s default port, then set url’s port to null.
And using the set of default ports as defined by https://url.spec.whatwg.org/#url-miscellaneous
I figure this probably helps iron away a few possible corner cases. It more neatly matches browser behaviour, and it's in line with other aspects of normalization that we're providing for, eg...
```python
assert httpx.URL("http://WWW.EXAMPLE.COM") == httpx.URL("http://www.example.com")
```
It also has the nice property that `url.netloc` now properly …
> Perform port normalization for `http`, `https`, `ws`, `wss`, and `ftp` schemes.

- README.md
- docs/index.md
- httpx/_decoders.py
- requirements.txt
- setup.py
- tests/models/test_responses.py
- tests/test_decoders.py
The `brotlipy` package has been superseded by the `brotlicffi` package.
See #1604
> Update brotli support to use the brotlicffi package

- httpx/_api.py
Refs #1611
Our refactoring to remove the `StreamContextManager` class in https://github.com/encode/httpx/pull/1577/files#diff-52ea133fd8a901d7004a1242a4db84ffa3be26864fb6b6c2c1dbd1f36e7d2027 omitted to pass through the `timeout=...` parameter in the top-level `httpx.stream(...)` function.
As a result, in 0.18.0 when using `httpx.stream(..., timeout=...)` the timeout parameter was not taking any effect, and the default timeout was instead being used.
> Add missing `timeout=...` to top-level `httpx.stream()` function.

- CHANGELOG.md
- httpx/__version__.py
* Update brotli support to use the `brotlicffi` package (Pull #1605)
* Ensure that `Request(..., stream=...)` does not auto-generate any headers on the request instance. (Pull #1607)
* Pass through `timeout=...` in top-level httpx.stream() function. (Pull #1613)
* Map httpcore transport close exceptions to httpx exceptions. (Pull #1606)
> Version 0.18.1

- httpx/_content.py
- httpx/_multipart.py
- httpx/_utils.py
- tests/test_content.py
Closes #1490
Step 1: Add failing test case for `content=io.BytesIO(...)`:
```python
def test_bytesio_content():
headers, stream = encode_request(content=io.BytesIO(b"Hello, world!"))
assert isinstance(stream, typing.Iterable)
assert not isinstance(stream, typing.AsyncIterable)
content = b"".join([part for part in stream])
assert headers == {"Content-Length": "13"}  # Currently returns {'Transfer-Encoding': 'chunked'}
assert content == b"Hello, world!"
```
Step 2: Refactor `peek_filelike_length` to return `Optional[int]`, rather than raising an exception when the length cannot be determined.
Step 3: Use `peek_filelike_length` in the `elif isinstance(content, Iterable):` case of `encode_content(...) -> (headers, stream)`, switching between either `Content-Length: <length>` or …
> Prefer `Content-Length` over `Transfer-Encoding: chunked` for `content=<file-like>` cases.

- docs/advanced.md
The current [Mock transports](https://www.python-httpx.org/advanced/#mock-transports) example reads:
```
```
However, at the time of writing this, if the `TESTING` envvar is not set, a `KeyError` would be raised instead of following the `HTTPTransport` branch.
This patch aims to make the example more robust.
> Make the MockTransport example more robust/correct

- .github/workflows/test-suite.yml
- docs/advanced.md
- requirements.txt
- tests/conftest.py
Closes #1678.
**EDIT**: Failing due to `mypy`. - @kludex
**EDIT**: Changed "Related to #...." to "Closes #...." - @tomchristie
> 👷 Add Python 3.10 beta to the CI

- docs/advanced.md
- docs/environment_variables.md
please ensure you've discussed the your proposal prior to issuing a pull request.
> Adding netrc environment variable into the documentation

- CHANGELOG.md
- httpx/__version__.py
* Support for Python 3.10. (Pull #1687)
* Expose `httpx.USE_CLIENT_DEFAULT`, used as the default to `auth` and `timeout` parameters in request methods. (Pull #1634)
* Support [HTTP/2 "prior knowledge"](https://python-hyper.org/projects/hyper-h2/en/v2.3.1/negotiating-http2.html#prior-knowledge), using `httpx.Client(http1=False, http2=True)`. (Pull #1624)
* Clean up some cases where warnings were being issued. (Pull #1687)
* Prefer Content-Length over Transfer-Encoding: chunked for content=<file-like> cases. (Pull #1619)
> Version 0.18.2

- README.md
Simple documentation typos may be raised as stand-alone pull requests.
> ✏ Fix third party documentation link

- docs/contributing.md
- scripts/test
Refs https://github.com/encode/httpx/pull/1669#issuecomment-867497780
> Allow passing additional pytest args to scripts/test

- httpx/_compat.py
ssl.OP_NO_TLSv1
ssl.OP_NO_TLSv1_1
are deprecated in py3.7+ and using these options prevents
downstream users of httpx.create_ssl_context using
minimum_version
> use context.minimum_version in py3.7+ where available

- httpx/_transports/wsgi.py
I _think_ this should say WSGI, not ASGI
> Fix typo in wsgi.py

- tests/conftest.py
Inline the confusing SERVER_SCOPE literal as suggested in #1771,
and effectively remove the Literal import bringing typing_extensions
requirement.
> Inline SERVER_SCOPE and remove typing_extensions requirement

- tests/models/test_responses.py
Fix test_json_without_specified_encoding_*_error tests on big endian
platforms.  The tests wrongly assume that data encoded as "utf-32-be"
can not be decoded as "utf-32".  This is true on little endian platforms
but on big endian platforms "utf-32" is equivalent to "utf-32-be".
To avoid the problem, explicitly decode as "utf-32-le", as this should
trigger the expected exception independently of platform's endianness.
> Fix JSON wrong encoding tests on big endian platforms

- httpx/_client.py
Add a client default for `allow_redirects`, supporting the following usages...
```python
client = httpx.Client(allow_redirects=<True|False>)
```
This brings `allow_redirects` in line with the `timeout` and `auth` parameters, in that they both have per-request-arguments and client-defaults, and use `USE_CLIENT_DEFAULT` as the default request argument.
We'll probably later follow up on this with https://github.com/encode/httpx/discussions/1785 - but this step make sense in it's own right, deserves to be a pull request on it's own. Other steps can follow later.
> Add `Client(allow_redirects=<...>)`

- setup.py
So, `httpx` itself doesn't have any specific requirements on which `h2` version should be installed.
That's actually up to `httpcore`.
This pull request updates the `extras_require` to reflect that.
*However*... I'm a bit wary that pip's dependency resolution *might* not actually get this right, so this pull request is a bit exploratory. 
Closes #1798
> Update HTTP/2 support in `extras_require`

- httpx/_multipart.py
- httpx/_types.py
- tests/test_multipart.py
Fixes #1706
Forces `FileContent` to be `bytes` or `BytesIO` instances. For `str` and `StringIO` instances a `TypeError` is raised.
> enforce-upload-files-binary-type

- README.md
- docs/index.md
- httpx/_decoders.py
- httpx/_models.py
- setup.py
- tests/models/test_responses.py
- tests/test_decoders.py
Use `charset_normalizer` to auto-detect character encodings in cases where no `Content-Type: text/...; charset=...` is included.
See https://github.com/encode/httpx/discussions/1657 and https://github.com/tomchristie/top-1000 for some evidence-led rationale behind this change.
> Add `charset_normalizer` detection.

- setup.cfg
- tests/client/test_proxies.py
- tests/test_timeouts.py
Sometimes it's useful to have the tests that use the network
marked so they can be skipped easily when we know the network
is not available.
This is useful for example on SUSE and openSUSE's build servers.
When building the httpx packages (actually, any package in the
distribution) the network is disabled so we can assure
reproducible builds (among other benefits). With this mark, it's
easier to skip tests that can not succeed.
> Add a network pytest mark for tests that use the network

- httpx/_client.py
- tests/client/test_async_client.py
- tests/client/test_client.py
When using a client, the expectation is that users should use one of the two following styles...
```python
with httpx.Client() as client:
...
```
Or...
```python
...
```
This pull request introduces a little bit of guarding around the opening of a `client` with block in order to enforce that unexpected usages mixing the two styles don't occur, so that we can't...
* Reopen a client once it's been closed.
* Enter into a client `with` block more than once.
Nailing down the possible usages here should just help guard against odd unexpected states.
Closes #1615
> Stricter enforcement of client lifespan styles.

- README.md
- requirements.txt
Test cases on Python 3.6 are hanging, both when running locally, and on CI.
Locally I ran...
```python
scripts/install -p python3.6
venv/bin/pytest --full-trace
```
in order to track down where the tests were hanging. Issue was when waiting for the uvicorn server to be available.
Pinning to Uvicorn 0.14.0 appears to resolve the issue.
> Resolve Python 3.6 tests hanging.

- requirements.txt
Idea raised on #1680:
> Should we make sure that we have more strictly pinned dependancies before pulling this in?
> 
> Eg... https://github.com/encode/httpcore/pull/184/files
> 
> _Originally posted by @tomchristie in https://github.com/encode/httpx/issues/1680#issuecomment-862320582_
> 📌 Pin development requirements

- docs/compatibility.md
- httpx/_transports/wsgi.py
- tests/test_wsgi.py
I found this from here: https://github.com/falconry/falcon/blob/e255bff9ae5a90d0cb3fe9af7c16917f18a92dc3/falcon/request.py#L1879
Based on the documentation at https://modwsgi.readthedocs.io/en/master/user-guides/debugging-techniques.html#apache-error-log-files, I believe Falcon is right and HTTPX is wrong.
This PR:
1. Adds a parameter so that we can test it and users can easily collect the logs in their tests if they want.
2. Changes the default from an inaccessible `BytesIO` (wrong type of stream, can't be accessed by user) to `sys.stderr` so that users (or pytest automatically) will capture the logs.
> BUG: wsgi.error should be TextIO, not BytesIO in WSGI transport

- httpx/_client.py
- httpx/_models.py
- httpx/_status_codes.py
- tests/models/test_responses.py
Add API for status code checks...
* `.is_informational`  Check for 1xx responses
* `.is_success`  Check for 2xx responses
* `.is_redirect`  Check for 3xx responses
* `.is_client_error`  Check for 4xx responses
* `.is_server_error`  Check for 5xx responses
Checking for a properly formed URL redirect is now...
* `.has_redirect_location`
The `.raise_for_status()` method now raises on any response except 2xx.
> API for status code checks.

- README.md
- docs/index.md
- httpx/_main.py
HTTP/2 requests displayed in the console should:
* Use `"HTTP/2"` in the version.
* Display lowercase headers.
As it happens the HTTP/2 displays in the console are not completely ideal, because we print them in the `request` event hook, but we *don't actually know* at that point if HTTP/2 will be successfully negotiated or not. Still it's close enough to display it as an HTTP/2 request, and have the response indicate which version *actually* got used.
Sometime further down the line we'll want to address this with some additional information for verbose displays, eg...
```
* Connected to www.example.com (1.2.3.4) on port 443. (HTTP/2 Negotiated)
GET / HTTP/2
host: www.example.com
accept: */*
accept-encoding: gzip, deflate, br
connection: keep-alive
user-agent: python-httpx/1.0.0.beta0 …
```
> Tidy up the formatting of HTTP/2 requests

- docs/advanced.md
Custom response handlers need to run `response.read()` before they can read the content of the response. However when using an AsyncClient this will produce an error of `RuntimeError: Attempted to call a sync iterator on an async stream.`. Took me some digging to figure out I just needed to use `response.aread()` here instead of `response.read()` so figured I would an MR with an expansion on the note for anyone else.
Thanks!
have been …
> Expand docs note for async custom handler responses

- httpx/_models.py
The `response.url` property is now correctly annotated as `URL`, instead of `Optional[URL]`.
Closes #1928
> Fix `response.url` annotation.

- CHANGELOG.md
- httpx/__version__.py
* The `response.url` property is now correctly annotated as `URL`, instead of `Optional[URL]`. (#1940)
> Version 0.21.1

- httpx/_content.py
- httpx/_multipart.py
- tests/test_content.py
Resolves #1911
When digging into this, it turns out that when sending an upload file we're using `iter(file_obj)`, which *happens* to be a line-by-line iterator, and might yield super-large chunks for binary files. That happens to be slow because you don't really end up streaming the file to the network at all, but rather batching it all up in memory first.
The low-hanging fruit here is to cap the size of the chunks that we send to a max of 64k, which from a bit of prodding seems to be a fairly decent value.
It's possible that using `.read()` on a stream if it exists might be beneficial too, but I've not dug into that yet.
> Read upload files using `read(CHUNK_SIZE)` rather than `iter()`.

- .github/workflows/test-suite.yml
> CI should just use Python "3.9", not "3.9.5"

- CHANGELOG.md
- httpx/__version__.py
* HTTP/2 support for tunnelled proxy cases. (#2009)
* Improved the speed of large file uploads. (#1948)
> Version 0.21.2

- httpx/_content.py
- tests/test_api.py
> Fix for stream uploads that subclass SyncByteStream/AsyncByteStream

- CHANGELOG.md
- httpx/__version__.py
* Fix streaming uploads using `SyncByteStream` or `AsyncByteStream`. Regression in 0.12.2. (#2016)
> Version 0.21.3

- CHANGELOG.md
Version was specified incorrectly.
See: https://github.com/encode/httpx/pull/2016#issuecomment-1006721639
> Fix typo in change-log.

- docs/async.md
There is no 'backend' parameter to AsyncHTTPTransport and it seems that
the backend is detected automatically for anyio as it is for other async
libraries.
> Drop mention of backend selection for AsyncHTTPTransport() in docs

- httpx/_multipart.py
- httpx/_types.py
- tests/test_multipart.py
Compliment to https://github.com/encode/starlette/pull/1311
> Allow custom headers in multipart/form-data requests

- README.md
- docs/advanced.md
- docs/index.md
- httpx/_config.py
- httpx/_transports/default.py
- requirements.txt
- setup.py
- tests/client/test_proxies.py
- tests/test_config.py
Integration against `httpcore` 0.14.5, which adds SOCKS5 proxy support, via [the fantastic `socksio` package](https://github.com/sethmlarson/socksio).
> SOCKS proxy support

- httpx/_models.py
- tests/client/test_headers.py
These two tests were failing beforehand
> Fix Headers.update to correctly handle repeated headers

- httpx/_api.py
Evening, hope you are all doing well.  While having a little study through the docs and code, I noticed that in some requests the `json`, `data` and `files` arguments are well documented when they are excluded, however binary content via `content=` for the request body is not, this patch updates the documentation to outline that.
Thanks again for the time to review these changes and your time on the library in general.
> Update documentation to outline that binary content is also excluded in certain requests

- setup.py
Relax the version bind on rich to allow v11.  There are no test
regressions with the new version, and CLI seems to work correctly.
> Allow rich-11

- httpx/_main.py
Escapes the download name so that it won't render console markup.
> Fix console markup escaping issue

- httpx/_multipart.py
- tests/test_multipart.py
> Always rewind files on multipart uploads.

- httpx/_decoders.py
- httpx/_models.py
- tests/models/test_responses.py
> Ensure that `iter_bytes` and `iter_raw` do not ever yield any zero-length chunks.

- httpx/_client.py
- httpx/_utils.py
- tests/client/test_redirects.py
- tests/test_utils.py
Closes #1850
Added a utility function to check if a URL is a HTTPS upgrade of another URL. It will only work if the default ports (80 and 443) are used.
> Preserve Authorization header on HTTPS redirect (#1850)

- httpx/_utils.py
Based on what @tomchristie recommended to make https://github.com/encode/httpx/pull/1909 this PR into a shorter one to validate multiple things and let it more clear and ready for review.
> Refactor `httpx/_utils.py`

- httpx/_main.py
- tests/conftest.py
- tests/test_main.py
Closes #2049
Changed print_response to simply display the content length of a binary response.
`get_lexer_for_response` returns 'Text only' for a `Content-Type: text/...` response, so it will be properly displayed using `rich.syntax.Syntax`. Those responses which do not get a corresponding lexer are considered binary and their output is suppressed.
To make the tests pass I had to add another route to the test server that would return a binary response. Feel free to point it out if there's another way to do it.
> Suppress binary output on the command line.

- README.md
- docs/index.md
* The 0.21 release note is out of date.
* Tweak the trailing blurb, in line with https://github.com/encode/starlette/pull/1477 and https://github.com/encode/uvicorn/pull/1365
> Docs tweaks

- docs/advanced.md
- httpx/_config.py
Closes: #2079 
Updated docs and class docstring for `keepalive_expiry` param.
> Fix: Keep-alive configuration is not documented. 

- docs/advanced.md
The argument to `httpx.Limits` is named `max_keepalive_connections` but is referenced as `max_keepalive` in the docs. This updates the single place I found it referenced incorrectly.
Thanks for all the great work on `httpx` 🙏
> Fix invalid max_keepalive_connections argument name

- requirements.txt
Refs https://github.com/encode/httpx/pull/2097#issuecomment-1080008519
CI currently broken due to mkdocs < 1.3.0 being broken after a new Jinja2 release
See: https://github.com/mkdocs/mkdocs/issues/2799
```
+ venv/bin/mkdocs build
File "/Users/florimond/Developer/python-projects/httpx/venv/bin/mkdocs", line 8, in <module>
sys.exit(cli())
File "/Users/florimond/Developer/python-projects/httpx/venv/lib/python3.10/site-packages/click/core.py", line 1128, in __call__
return self.main(*args, **kwargs)
File "/Users/florimond/Developer/python-projects/httpx/venv/lib/python3.10/site-packages/click/core.py", line 1053, in main
rv = self.invoke(ctx)
File "/Users/florimond/Developer/python-projects/httpx/venv/lib/python3.10/site-packages/click/core.py", line 1659, …
```
> Upgrade mkdocs to 1.3.0 to fix scripts/build failure

- httpx/_compat.py
- requirements.txt
As mentioned on https://github.com/encode/httpx/pull/2097#issuecomment-1082207141, the pipeline is broken due to `black`/`click`.
Thanks @ofek! :)
> Bump `black` to 22.3.0

- httpx/_client.py
- tests/client/test_async_client.py
Based on #2148 but adding a test case which doesn't introduce `sleep` into our test suite.
Closes #2139
> Close responses when on cancellations occur during reading.

- docs/contributing.md
- docs/troubleshooting.md
Per https://www.python-httpx.org/compatibility/#proxy-keys, there should always be a `://` after the protocol. The given examples raise an exception when used as-is.
> docs: Fix proxy examples

- httpx/_exceptions.py
The `RequestBodyUnavailable` class no longer exists?
> Remove `RequestBodyUnavailable` from module docstring

- setup.py
Follow on from https://github.com/encode/httpx/pull/2097 which dropped Python 3.6 support.
> Drop `async_generator` requirement.

- docs/async.md
> removed curio from async.md

- requirements.txt
This PR gets CI back in shape as there is an issue with `mkautodoc` when the latest Markdown version is installed:
```console
Python 3.10.0 (default, Nov 28 2021, 23:05:33) [GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import mkautodoc
File "<stdin>", line 1, in <module>
File "/home/florimond/dev/fairness/httpx/venv/lib/python3.10/site-packages/mkautodoc/__init__.py", line 1, in <module>
from .extension import MKAutoDocExtension, makeExtension
File "/home/florimond/dev/fairness/httpx/venv/lib/python3.10/site-packages/mkautodoc/extension.py", line 4, in <module>
from markdown.util import etree
ImportError: cannot import name 'etree' from 'markdown.util' …
```
> Pin markdown==3.3.7 to prevent mkautodoc loading failure

- docs/exceptions.md
- docs/quickstart.md
- mkdocs.yml
I didn't raise a discussion about this, but this PR also serves as a hands-on proposal. Happy to discuss separately if need be.
This PR restructures the documentation in four well-visible sections:
<details>
<summary>Open for text version</summary>
* Usage
* Quickstart
* Advanced usage
* Guides
* Async Support
* HTTP/2 Support
* Requests Compatibility
* Troubleshooting
* API Reference
* Developer Interface
* Exceptions
* Environment variables
* Community
* Third-Party Packages
* Contributing
* Code of Conduct
</details>
This takes inspiration from the 4-part Tutorials/How-To's/Discussions/Reference theorised by Daniele Procida (see [What nobody tells you about documentation (talk)](https://www.youtube.com/watch?v=t4vKPhjcMZg)).
It doesn't _exactly_ match that structure -- e.g. I don't …
> Rework docs structure

- docs/advanced.md
Prompted by https://github.com/encode/httpx/discussions/1755
* Clarify what "Connection retries" means
* Explain how to do retries beyond what HTTPX provides out-of-the-box.
> Expand docs about retries

- README.md
- docs/index.md
Python3.6 references are still present in documentation even after
officially dropping support.
#2136
> Update docs to reflect supported python versions

- httpx/_models.py
- httpx/_utils.py
Prompted by https://github.com/encode/httpx/pull/2302 which surfaced a warning in the upcoming Python 3.11 as `cgi` is being deprecated as per [PEP-594](https://peps.python.org/pep-0594/).
> Replace cgi which will be deprecated in Python 3.11

- setup.py
This is quite sad.
@michaeloliverx brought this to our attention on: https://github.com/encode/httpx/commit/45b7cfaad3a8987ea35fa5bf092bbdda485444fd#commitcomment-82042745.
The `Used by` section on the project's profile disappeared after we removed the `setup.py`. We can either accept this PR or revert https://github.com/encode/httpx/pull/2334, to have it back,
I'll let you folks decide @florimondmanca @tomchristie 🙏 
I'll update the Starlette and Uvicorn according to what is decided here.
Closes #2352
> Add fake setup.py

- httpx/_urls.py
- tests/models/test_queryparams.py
Closes #2331
We might also want to distinguish between `q=` and `q` at some point, but that's a more complex conversation.
> Fix empty query params

- httpx/_client.py
This is coming from: https://github.com/encode/httpx/discussions/1633#discussioncomment-717752
> Add thread-safety note on the `Client` docstring

- scripts/install
Installation should start by updating `pip` to the latest version.
Resolves issue noted in https://github.com/encode/httpx/pull/2334#issuecomment-1268308195
> Always use latest version of `pip`.

- httpx/_multipart.py
- httpx/_types.py
- tests/test_multipart.py
Closes #2069.
Allow `str` for simple multipart uploads...
```python
httpx.post(url, files={"upload": "some content"})
```
However we (continue to) explicitly disallow `io.StringIO` and files opened in text mode, since we can't upfront determine their byte-length.
I think this is probably a pretty okay middle-ground, supporting the simple text-use-case, while enforcing bytes for the file-like cases. Not a breaking change, since we're *expanding* our supported cases here.
> Allow str content for multipart upload files

- httpx/_client.py
- httpx/_types.py
The public API is now "fully typed" with generous use of `Any`. I have ideas of how to get rid of those but wanted to limit the scope of this PR.
- Initially raised as discussion #2181 
**Notable Changes**
- Added `[..., typing.Any]` to all Callables in `_client.py` pending narrower typing.
- Typed `RequestData` type alias as `Dict[Any, Any]`.
> Stricter typing for EventHooks

- requirements.txt
- setup.cfg
- tests/test_multipart.py
Minor PR to drop usage of the `cgi` module in favor of `multipart`
Also drops the deprecation warning filters that should no longer necessary
> Drop cgi module from test_multipart

- .github/workflows/test-suite.yml
Python 3.11 stable was released on 2022-10-24, see https://pythoninsider.blogspot.com/2022/10/python-3110-is-now-available.html
> Run tests against Python 3.11 stable

- docs/compatibility.md
I was recently migrating a project from Requests to HTTPX, and I stumbled a bit on the default socket timeouts being different between the two, which I haven't seen explicitly mentioned anywhere.
This adds a mention of those differences to the compatibility section, feel free to edit it or move it around as you choose.
> Mention default timeout differences from Requests in compatibility docs

- CHANGELOG.md
- httpx/__version__.py
- pyproject.toml
- setup.py
I think we should probably roll a 0.23.1 (or a 0.24.0) release here.
We've got a fairly substantial list of work since the latest release.
There are a couple of minor removals included here, but they're only for old undocumented aspects, so I *think* we're probably okay including them in a minor, but I'm happy to go with the group consensus here.
Closes #2443
* Support for Python 3.11. (#2420)
* Allow setting an explicit multipart boundary in `Content-Type` header. (#2278)
* Allow `tuple` or `list` for multipart values, not just `list`. (#2355)
* Allow `str` content for multipart upload files. (#2400)
* Support connection upgrades. See https://www.encode.io/httpcore/extensions/#upgrade-requests
* Don't drop empty query parameters. (#2354)
* Drop `.read`/`.aread` from …
> Version 0.23.1

- requirements.txt
- tests/test_multipart.py
Prompted by https://github.com/encode/starlette/discussions/1960
We don't actually need to parse the multipart content in order for us to test the expected behaviour, so...
Let's instead assert that the response body looks as expected, directly.
Drops a test requirement for us, and actually makes the tests clearer & more explicit.
> Drop `multipart` requirement from tests.

- CHANGELOG.md
Refs #2457.
See also https://github.com/encode/httpx/pull/2400#issuecomment-1320009779
> Explicit warning about changes in 0.23.1

- docs/compatibility.md
Following up on https://github.com/encode/httpx/discussions/2330#discussioncomment-4167768 I added a note about requests compatibility with form data and query params -- namely that httpx only supports dictionaries whereas requests also supports lists of tuples.
As suggested, I added this note after the Query Parameters section, however, it might also bear mentioning in the Request Content section?
> update requests compatibility docs on query and form params

- httpx/_client.py
- httpx/_transports/default.py
- httpx/_types.py
The type change from `Dict` to `Mapping` in the `httpcore` extensions has [caused a CI failure](https://github.com/encode/httpx/actions/runs/3547801638/jobs/5983626106)...
From this PR: https://github.com/encode/httpcore/pull/614
I think we want the same type change in `httpx` as well.
> Switch `extensions` from `Dict` to `Mapping`.

- httpx/_compat.py
- httpx/_transports/mock.py
This was resolved in typeshed and newer mypy versions have inherited the fix.
pyright reports:
[after.txt](https://github.com/encode/httpx/files/10110416/after.txt)
[before.txt](https://github.com/encode/httpx/files/10110417/before.txt)
> Remove typeshed iscoroutine workaround

- docs/api.md
Hi, looking at the docs while wrapping the `Response` object a few minor discrepancies exist.  Both `iter_lines()` & `aiter_lines()` do not accept an optional `chunk_size` argument, just updating that.  I _think_ this is the right place for this change.
Thanks for your time and a great library.
> [docs] Remove `chunk_size` arg from `iter_lines()` & `aiter_lines()` in documentation.

- httpx/_auth.py
- httpx/_compat.py
- httpx/_main.py
- httpx/_models.py
- httpx/_transports/asgi.py
- httpx/_transports/mock.py
- httpx/_transports/wsgi.py
- httpx/_urls.py
- httpx/_utils.py
- setup.cfg
- tests/client/test_auth.py
Being explicit about the parameters helps find bugs and makes the library easier to use for users.
- Tell mypy to disallow generics without parameter values
- Give all generic types parameters values
> Typing: always fill in generic type parameters

- httpx/_auth.py
- tests/client/test_auth.py
- tests/test_auth.py
this implements digest authentication state reuse as discussed in #1467.
Contrary to the [comment](https://github.com/encode/httpx/issues/1467#issuecomment-1280656164) i am not skipping most of the authentication flow if a previous challenge exists. Otherwise a failed authentication (401) would not result in a retry with the new server challenge (`test_digest_auth_resets_nonce_count_after_401` would fail).
> reuse the digest auth state to avoid unnecessary requests

- setup.cfg
- tests/client/test_proxies.py
- tests/conftest.py
- tests/test_content.py
- tests/test_exceptions.py
- tests/test_multipart.py
- tests/test_wsgi.py
- tests/utils.py
The only places mypy reports issues is in the test suite.
Part of the work for #2436
> Typing: enable disallow_incomplete_defs

- httpx/_compat.py
- httpx/_config.py
- httpx/_utils.py
- setup.cfg
- tests/conftest.py
- Add explicit exports for names imported from _compat and _models
- Correct import of the uvicorn Server class
Part of #2436
> Typing: Enable no_implicit_reexport

- setup.cfg
- tests/test_status_codes.py
- tests/test_wsgi.py
- ignore mypy when it comes to comparing an IntEnum member with an int
- Correct type hint for `test_wsgi_server_port`'s `expected_server_port`
parameter.
Part of the work for #2436
> Typing: enable strict_equality

- httpx/_types.py
- httpx/_urls.py
- tests/models/test_url.py
Closes #2462 with a basic test, happy to add tests for more scenarios
> Add back in URL.raw with NamedTuple

- httpx/_content.py
- tests/test_content.py
> Raise TypeError if content is passed a 'dict' instance.

- tests/models/test_responses.py
Refs #2492
There's no need to import `brotli` here. We're only using it to create some broken compressed content. (We do a compression, then slice it.)
Instead, just use some nonsense content. That'll raise the same `DecodingError`.
> Drop unneccessary private import in tests

- httpx/_utils.py
- tests/models/test_queryparams.py
Prompted by #2515. (Doesn't presume any particular resolution to that case.)
Closes #746 - we don't support bytes (or other unexpected types) as QueryParam values. Let's raise a clear error, rather than coercing an unexpected `str` value.
Before this change...
```python
>>> httpx.URL("http://www.example.com/", params={"query": b"abc"})
URL('http://www.example.com/?query=b%27abc%27')
```
After this change...
```python
>>> httpx.URL("http://www.example.com/", params={"query": b"abc"})
TypeError: Expected str, int, float, bool, or None. Got <class 'bytes'>.
```
> Raise `TypeError` on invalid query params.

- pyproject.toml
I was super honored to learn that my favorite http library is using my hatch-fancy-pypi-readme!
When adding it to my brag list, I've noticed two problems in your usage and wanted to offer you the simple solutions:
1. Your relative image URLs from the README 404 – this is why I've added the substitutions feature (if the logo is an absolute link just for PyPI, I can also make it relative if you'd like).
2. Your Changelog is _really_ long so I would recommend trimming it. I've added the technique that I use personally.
You can test the result by running `pipx run hatch-fancy-pypi-readme`, but here's how the tail looks like after this PR:
```markdown
...
A huge amount of credit is due to `requests` for the API layout that
much of this work follows, as well as to `urllib3` for plenty of design …
```
> PyPI readme: fix screenshot links & trim changelog

- httpx/_utils.py
- tests/models/test_queryparams.py
This reverts commit 4cbf13ece2e584b45b935df0a0c670e1863c4569 / PR #2523
See discussion at https://github.com/encode/httpx/discussions/2538 and in #2523 — this change is potentially breaking and should be considered for a future release instead (i.e. 0.24.0).
> Revert "Raise `TypeError` on invalid query params. (#2523)"

- CHANGELOG.md
- httpx/__version__.py
~~Depends on #2539~~
We've now had two recent cases of tidying up edges of the API *in minor point releases* which have led to breakages in user codebases. Both of these have been due to my lead. Calling these out so that we can tighten up our release process, and for me in particular to slow down on hitting go on releases.
Release draft is here... https://github.com/encode/httpx/releases/tag/untagged-9adfb8466a6a6537698a
---
* Version 0.23.2 accidentally included stricter type checking on query parameters. This shouldn've have been included in a minor version bump, and is now reverted. (#2523, #2539)
> Version 0.23.3

- tests/test_multipart.py
Refs #2492 
This is just a test refactoring.
Use `httpx.Request(...)` to handle the multipart tests, rather than importing the `encode_request` function, which is a private implementation detail. Having tests against our public API makes more sense than digging into private imports.
> Drop private import of 'encode_request' in test_multipart

- docs/advanced.md
- docs/environment_variables.md
- httpx/__init__.py
- httpx/_auth.py
- httpx/_client.py
- httpx/_utils.py
- tests/client/test_auth.py
- tests/client/test_properties.py
- tests/fixtures/.netrc-nopassword
- tests/test_utils.py
Closes #2532
Prompted by https://github.com/encode/httpx/issues/2532#issuecomment-1368907498
We currently automatically handle [`netrc` authentication](https://docs.python.org/3/library/netrc.html), which is baked directly into the `Client`, and which is enabled unless the developer sets `trust_env=False`.
* Browsers, which do *not* use `netrc` authentication.
* The `curl` command line client, which *only* uses `netrc` authentication if explicitly enabled.
The suggest here is that we should make a behavioural change, and *no longer* bake `netrc` authentication directly into the client, in favor of providing an explicit `NetRCAuth()` class.
Some usage examples...
```python
auth = httpx.NetRCAuth()
client = httpx.Client(auth=auth)
auth = httpx.NetRCAuth(file="/path/to/netrc")
client = …
```
> Add `NetRCAuth()` class.

- httpx/_client.py
ASyncClient docstring is not aligned with Client docstring. The sslcontext option for the verify parameter is not present. This PR fix this.
> Add sslcontext to the asynclient docstring

- httpx/_urls.py
- pyproject.toml
- requirements.txt
- scripts/check
- scripts/lint
- setup.cfg
- tests/client/test_async_client.py
- tests/models/test_requests.py
- tests/models/test_responses.py
- tests/test_exceptions.py
- tests/test_wsgi.py
Ref.: https://github.com/encode/httpx/discussions/2607
> Use ruff instead of flake8, autoflake and isort

- CHANGELOG.md
- httpx/__version__.py
* The logging behaviour has been change to be more in-line with other standard Python logging usages. We no longer have a custom `TRACE` log level, and we no longer use the `HTTPX_LOG_LEVEL` environment variable to auto-configure logging. We now have a significant amount of `DEBUG` logging available at the network level. Full documentation is available at https://www.python-httpx.org/logging/ (#2547, encode/httpcore#648)
* The `Response.iter_lines()` method now matches the stdlib behaviour and does not include the newline characters. It also resolves a performance issue. (#2423)
* Query parameter encoding switches from using + for spaces and %2F for forward slash, to instead using %20 for spaces and treating forward slash as a safe, unescaped character. This differs from `requests`, but …
> Version 0.24.0

- httpx/_auth.py
Discussed in #2665 - closes #2666
> Fixes #2666: None is the default value of file for httpx.NetRCAuth

- httpx/_utils.py
- tests/test_utils.py
Closes #2660 
The `get_environment_proxies` function in **_utils.py** is responsible for parsing and mounting proxy info from system environment.
https://github.com/encode/httpx/blob/4b5a92e88e03443c2619f0905d756b159f9f0222/httpx/_utils.py#L229-L264
For env `no_proxy`, according to [CURLOPT_NOPROXY explained](https://curl.se/libcurl/c/CURLOPT_NOPROXY.html), it should support domains, IPv4, IPv6 and the `localhost`. However, current `get_environment_proxies` function implementation only supports domains correctly as it always adds wildcard `*` in front of the `hostname`. 
I encountered error when my environment `no_proxy` includes IPv6 address like `::1`. It is wrongly transformed into `all://*::1` and causes urlparse error since the _urlparse.py parses the `:1` as port.
To fix this issue, …
> fix: NO_PROXY should support IPv4, IPv6 and localhost

- httpx/_urlparse.py
- tests/test_urlparse.py
> Fix optional percent encoding behaviour.

- httpx/_urlparse.py
- tests/test_urlparse.py
Include more visibility about the error in some `InvalidURL` exceptions.
Prompted by #2659, #2674
> Additional context in InvalidURL exceptions.

- httpx/_multipart.py
This is a minor patch proposal fixing fixing an issue with a recently introduced check for binary file objects in multipart uploads. The currently used check
https://github.com/encode/httpx/blob/f1157dbc4102ac8e227a0a0bb12a877f592eff58/httpx/_multipart.py#L125-L128
misses out on file objects that read and write byte-like objects, but have the `mode` attribute set to `r` such as [ZipFile.open()](https://docs.python.org/3/library/zipfile.html#zipfile.ZipFile.open) which is binary-only.
> More robust check for upload files in binary mode

- httpx/_utils.py
- scripts/check
The `ruff` command in `./scripts/check` is not catching the errors, but running `./scripts/lint` does.
This PR will fix both ruff command and the bare exception issue.
> Fix ruff error and script

- docs/third_party_packages.md
Hello people! Long time no see.
As I just released a new version of [httpx-sse](https://github.com/florimondmanca/httpx-sse) after a contributor fixed an issue there, it came to me that the package was not listed on this page yet. I don't know if there's a particular ordering we adhere to.
Given that it received contributions and my comment here https://github.com/encode/httpx/issues/1278#issuecomment-1304794902 received a fair bunch of traffic, it looks like it's being useful to people. It's mostly "done" and low-maintenance so I'm happy to keep it under my hood for now.
Perhaps this might even... ?
Closes #1278
Edit: oh well, this exact kind of PR was suggested by Tom a few months ago! https://github.com/encode/httpx/issues/304#issuecomment-1332418303
> Add httpx-sse to Third Party Packages

- httpx/_urlparse.py
- tests/test_urlparse.py
Fix which gen-delims need to be escaped for path/query/fragment components in URL.
* `path` now allows `: / [ ] @` instead of `: @ /`
* `query` now allows `: / [ ] @ ?` instead of `/ ?`
* `fragment` now allows `: / [ ] @ ? #` instead of `/ ?`
Closes #2694
> Fix for gen-delims escaping behaviour in path/query/fragment

- CHANGELOG.md
- httpx/__version__.py
* Provide additional context in some `InvalidURL` exceptions. (#2675)
* Fix optional percent-encoding behaviour. (#2671)
* More robust checking for opening upload files in binary mode. (#2630)
* Properly support IP addresses in `NO_PROXY` environment variable. (#2659)
* Set default file for `NetRCAuth()` to `None` to use the stdlib default. (#2667)
* Set logging request lines to INFO level for async requests, in line with sync requests. (#2656)
* Fix which gen-delims need to be escaped for path/query/fragment components in URL. (#2701)
> Version 0.24.1

- httpx/_transports/wsgi.py
- tests/test_wsgi.py
- I noticed that WSGI environs sent to applications with `httpx.Client(app=app)` did not contain a SERVER_PROTOCOL
- [PEP-3333](https://peps.python.org/pep-3333/#environ-variables) indicates that this key must be present in the WSGI environ, and popular WSGI frameworks (such as [webob](https://github.com/Pylons/webob)) assume it will be as well
- It looks like httpx defaults to using `HTTP/1.1` for a nearly identical case in the ASGITransport, so I did the same here
- I'm more than happy to discuss any of this further!
- _to my knowledge, this does not require a documentation update_
> Ensure all WSGITransport environs have a SERVER_PROTOCOL

- CHANGELOG.md
- httpx/_transports/default.py
- pyproject.toml
> Add `socket_options` argument to `httpx.HTTPTransport` class

- httpx/_urlparse.py
- tests/models/test_url.py
- tests/test_urlparse.py
Closes https://github.com/encode/httpx/issues/2721
Encodes `/` as `%2F` in query parameters for more robust behavior matching browser implementations. See issue for discussion.
> Always encode forward slashes as `%2F` in query parameters

- docs/async.md
Update docs regarding usage of client context manager inside hot loops, since we know that it negatively affects performance
> async recommendations

- docs/advanced.md
> docs: upload progress

- docs/quickstart.md
- httpx/_models.py
- tests/models/test_responses.py
Discussion at https://github.com/encode/httpx/discussions/2766
httpstatuses.com redirects to https://www.webfx.com/web-development/glossary/http-status-codes/ which has advertisements and is now generally an unpleasant resource — I'll spare you the visit:
Instead we use the Mozilla documentation which looks like this: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/200
> Use Mozilla documentation instead of `httpstatuses.com` for HTTP error reference

- docs/third_party_packages.md
Discussed in https://github.com/encode/httpx/discussions/2797
[`Hishel`](https://github.com/karosis88/hishel) is an elegant HTTP Cache implementation library for the [HTTPX](https://github.com/encode/httpx) and [HTTP Core](https://github.com/encode/httpcore)  projects.
The philosophy is to provide a library that is **fully integrated into the `HTTPX` and `HTTP Core` ecosystems**, as well as a **single and powerful way** to add an HTTP Cache layer on top of **`HTTPX`'s Transports and `HTTP Core`'s connection pulls**.
Due to its very similar code base and compatibility with these two diamonds, `Hishel` is meant to be the little brother to `HTTPX` and `HTTP Core`.
```python
import hishel
cl = hishel.CacheClient()  # instead of httpx.Client()
resp = cl.get('https://www.encode.io')  # takes …
```
> Add `Hishel` into the `Third Party Packages`

- CHANGELOG.md
- docs/api.md
- docs/quickstart.md
- httpx/_models.py
- tests/client/test_async_client.py
- tests/client/test_client.py
make it possible to write code like `r = httpx.get('...').raise_for_status().json()`
Refs https://github.com/encode/httpx/discussions/2775
> Make `raise_for_status` chainable

- httpx/_models.py
To remove the unknown dict type info
(variable) extensions: ResponseExtensions | dict[Unknown, Unknown]
Simple add typing information for the extensions variable, as the default dict is "unknown"
> Update Typeinfo for extensions in Response class

- CHANGELOG.md
- httpx/_config.py
- httpx/_transports/default.py
- pyproject.toml
Closes #1434
Because HTTPS proxies are now supported by httpcore, this pull request simply provides an API for that feature.
> HTTPS proxies support

- CHANGELOG.md
- httpx/__version__.py
* Drop support for Python 3.7. (#2813)
* Support HTTPS proxies. (#2845)
* Change the type of `Extensions` from `Mapping[Str, Any]` to `MutableMapping[Str, Any]`. (#2803)
* Add `socket_options` argument to `httpx.HTTPTransport` and `httpx.AsyncHTTPTransport` classes. (#2716)
* The `Response.raise_for_status()` method now returns the response instance. For example: `data = httpx.get('...').raise_for_status().json()`. (#2776)
* Return `500` error response instead of exceptions when `raise_app_exceptions=False` is set on `ASGITransport`. (#2669)
* Ensure all `WSGITransport` environs have a `SERVER_PROTOCOL`. (#2708)
* Always encode forward slashes as `%2F` in query parameters (#2723)
* Use Mozilla documentation instead of `httpstatuses.com` for HTTP error reference (#2768)
> Version 0.25.0

- tests/client/test_proxies.py
Refactor a test case that imports from private namespace, as suggested in #2492.
The original version constructs `URLPattern`s to compare. This PR destructs them.
> test: Drop private imports from `test_proxies.py`

- CHANGELOG.md
- httpx/_models.py
- tests/models/test_responses.py
Discussed in #2041
After `Response.text` is accessed, if you try to change `Response.encoding`, nothing happens. So just raise an Exception on change to `encoding` after `text` is accessed.
> Raise ValueError on `Response.encoding` being set after `Response.text` has been accessed

- .github/workflows/publish.yml
- .github/workflows/test-suite.yml
- CHANGELOG.md
- httpx/_compat.py
- httpx/_config.py
- pyproject.toml
Follow on from https://github.com/encode/httpcore/pull/807.
The [third and final Python 3.12 release candidate](https://discuss.python.org/t/python-3-12-0rc3-released-honestly-the-final-release-candidate-i-swear/34093?u=hugovk) is out! :rocket:
> ## Call to action
> 
> We strongly encourage maintainers of third-party Python projects to prepare their projects for 3.12 compatibilities during this phase, and where necessary publish Python 3.12 wheels on PyPI to be ready for the final release of 3.12.0.
Python 3.12.0 final is due out in two weeks: [2023-10-02](https://peps.python.org/pep-0693/).
See also https://dev.to/hugovk/help-test-python-312-beta-1508/
> Add support for Python 3.12

- httpx/_urlparse.py
- tests/test_urlparse.py
The ``encode_host`` method used the regular expression in the variable IPv4_STYLE_HOSTNAME. This was before:
``r"^[0-9]+.[0-9]+.[0-9]+.[0-9]+$"`` which wrongly allows hostnames like ``023b76x43144`` to pas as a ipv4 address. This is now fixed by changed the url to ``r"^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$"``
> Fix encode host

- httpx/_auth.py
Motivated similarly to https://github.com/encode/httpx/pull/2909
We only need to import the stdlib `netrc` module if the `NetRCAuth()` class is being explicitly used.
Let's avoid unneccessary dependencies where possible.
> Lazily import 'netrc' module.

- httpx/_models.py
- httpx/_utils.py
- tests/test_utils.py
The `Response.json()` method appears unnecessarily complicated, I think this is a historical appendix that can be surgically tidied up. The stdlib implementation of `json.loads` already includes the charset detection that we're currently providing with our internal `guess_json_utf()` function.
* Switch `test_utils` to use a public API for testing JSON utf-8 encodings.
* Remove the internal `guess_json_utf()` function.
* Simpliy the `Response.json()` method.
> Cleanup `response.json()` method.

- httpx/_transports/default.py
- pyproject.toml
- requirements.txt
- scripts/check
- scripts/lint
[Ruff](https://docs.astral.sh/ruff/) introduced a new formatter that can completely replace black, allowing us to use ruff instead of ruff + black.
Ruff formatter, like ruff linter, is extremely fast.
> Use ruff format

- CHANGELOG.md
- httpx/__version__.py
Provisionally marked up for a release tomorrow...
* Add support for Python 3.12. (#2854)
* Add support for httpcore 1.0 (#2885)
* Raise `ValueError` on `Response.encoding` being set after `Response.text` has been accessed. (#2852)
> Version 0.25.1

- pyproject.toml
Force httpcore dependency to be above `1.0.0` because `httpx>=0.25.0` is not compatible with `httpcore<0.17.2`.
> 📌 pin httpcore==1.*

- CHANGELOG.md
- httpx/_auth.py
- httpx/_client.py
- httpx/_config.py
- httpx/_content.py
- httpx/_decoders.py
- httpx/_models.py
- httpx/_transports/default.py
- tests/client/test_async_client.py
- tests/client/test_auth.py
- tests/client/test_client.py
Hello! Thanks for awesome package! 🔥
First of all, I though about create an issue, but this is too small fix for that, dear maintainers
should I create an Issue or Discussion for that super small fixes?
Here I did little work for fixing of missed type hints of few of __init__()
According to https://peps.python.org/pep-0484/
`(Note that the return type of __init__ ought to be annotated with -> None.`
So type checkers (mypy, pyright) will work fine after this PR.
> add missing type hints to __init__(...)

- CHANGELOG.md
- httpx/__version__.py
* Add missing type hints to few `__init__()` methods. (#2938)
> Version 0.25.2

- httpx/_client.py
- httpx/_decoders.py
- httpx/_exceptions.py
- httpx/_main.py
- httpx/_models.py
- httpx/_multipart.py
- httpx/_transports/default.py
- httpx/_urlparse.py
- httpx/_urls.py
- pyproject.toml
- tests/client/test_auth.py
- tests/models/test_cookies.py
- tests/test_config.py
- tests/test_multipart.py
- tests/test_utils.py
A prototype to avoid using strings and comments longer than 88 (the default).
88 line length also used by the formatter.
Follow-up #2901
> Ruff linter: Use the default line-length

- tests/models/test_url.py
I would like to deal with https://github.com/encode/httpx/issues/2883.
In order to tackle this comprehensively I'm suggesting we *start by tidying up our existing URL test cases*.
There are two parts to this:
* Reorganise the existing tests in `models/test_url.py` - The current ordering of the tests isn't coherent.
* Remove `test_urlparse.py`, moving test cases into `models/test_url.py` - All the test cases there are now properly against the public `httpx.URL()` interface, tackled previously as part of the #2492.
This pull request deals with the first of these two bullet-points.
I'll follow up with the second part once this is in.
Here's the explanation of the proposed change (assuming I've got it correct 😅)...
* Tests are re-ordered, these no removal, addition, or modifying of test …
> Reorganise tests in 'test_url.py'

- httpx/_content.py
- httpx/_utils.py
- pyproject.toml
- tests/client/test_redirects.py
- tests/models/test_requests.py
- tests/models/test_responses.py
- tests/test_content.py
I decided to decompose my PR on incorporating `itertools.chain` a bit, and some of it can be automated by [C416](https://docs.astral.sh/ruff/rules/unnecessary-comprehension/). So this PR enables [C416](https://docs.astral.sh/ruff/rules/unnecessary-comprehension/) in `ruff` to simplify code.
> Enabling `ruff` C416

- CHANGELOG.md
- httpx/__version__.py
* The `proxy` argument was added. You should use the `proxy` argument instead of the deprecated `proxies`, or use `mounts=` for more complex configurations. (#2879)
* The `proxies` argument is now deprecated. It will still continue to work, but it will be removed in the future. (#2879)
* Fix cases of double escaping of URL path components. Allow / as a safe character in the query portion. https://github.com/encode/httpx/pull/2990.
* Handle `NO_PROXY` envvar cases when a fully qualified URL is supplied as the value. (#2741)
* Allow URLs where username or password contains unescaped '@'. (#2986)
* Ensure ASGI `raw_path` does not include URL query component. (#2999)
* Ensure `Response.iter_text()` cannot yield empty strings. (#2998)
> Version 0.26.0

- requirements.txt
Both `certifi` and `chardet` now contains typing info so we no longer need `types-certifi` and `types-chardet`.
See also https://github.com/encode/httpx/discussions/3014
> `types-certifi` and `types-chardet` are no longer needed

- httpx/_client.py
Except for the async/await syntax, `AsyncClient` and `Client` are supposed to be the same.
I isolated them into separate files and used `git diff --no-index --word-diff asyncclient.py syncclient.py` to find and fix differences.
> Keep clients in sync

- CHANGELOG.md
- httpx/_auth.py
- tests/test_auth.py
Fixes a typo that breaks old RFC 2069 mode digest auth.
The issue is that HA1 is added both on line 283, and again on line 293. ([According to RFC, it should be there only once.](https://datatracker.ietf.org/doc/html/rfc2069#section-2.1.2))
Also mentioned in https://github.com/encode/httpx/issues/2788#issuecomment-1677260605
> Fix RFC 2069 mode digest authentication

- docs/advanced/transports.md
The gist referenced by this documentation is out of date with `httpx` and doesn't currently work.
I'd like to see a third-party `urllib3` transport, but for now we should probably drop it from the docs.
Discussion: https://github.com/encode/httpx/discussions/2994
> Drop outdated section

- tests/test_utils.py
> test `obfuscate_sensitive_headers` via public api

- httpx/_models.py
- tests/test_utils.py
> test `parse_header_links` via public api

- docs/advanced/transports.md
Now includes examples with...
* `HelloWorldTransport`
* `HTTPSRedirect`
* `DebuggingTransport`
* `ProxyRoundRobin`
> Improve 'Custom transports' docs

- CHANGELOG.md
- httpx/__version__.py
* The `app=...` shortcut has been deprecated. Use the explicit style of `transport=httpx.WSGITransport()` or `transport=httpx.ASGITransport()` instead.
* Respect the `http1` argument while configuring proxy transports. (#3023)
* Fix RFC 2069 mode digest authentication. (#3045)
> Version 0.27.0

- httpx/__init__.py
- httpx/_api.py
- httpx/_auth.py
- httpx/_client.py
- httpx/_config.py
- httpx/_content.py
- httpx/_exceptions.py
- httpx/_models.py
- httpx/_status_codes.py
- httpx/_transports/__init__.py
- httpx/_transports/asgi.py
- httpx/_transports/base.py
- httpx/_transports/default.py
- httpx/_transports/mock.py
- httpx/_transports/wsgi.py
- httpx/_types.py
- httpx/_urls.py
- pyproject.toml
- tests/test_exported_members.py
This is a little refactor of our import strategy.
Now the main `__init__.py` file contains a lot of imports to deliver the public API that we want to expose in httpx.
It's actually working perfectly, but we can make it even simpler by splitting that logic and exposing the API from each module.
So in each module, we should define the variable `__all__`, which will contain the names of the classes that we want to expose at one level higher.
And each time we want to introduce a new public API, we will just modify the variable `__all__` from the module that class belongs to, rather than modifying the main `__init__.py` module of the httpx library.
> Define and expose the API from the same place

- docs/advanced/authentication.md
Fix docs basic authentication typo
```python shell
>>> httpx.__version__
'0.27.0'
>>> httpx.BasicAuthentication
File "<stdin>", line 1, in <module>
AttributeError: module 'httpx' has no attribute 'BasicAuthentication'
>>> httpx.BasicAuth
<class 'httpx.BasicAuth'>
>>> 
```
> fix docs basic authentication typo

- httpx/_client.py
- tests/test_timeouts.py
Discussion here https://github.com/encode/httpx/discussions/3110
On `httpx.client.send()`, now the timeout of the request is set if not set already.
This is for cases in which `httpx.client.send()` is used with `httpx.Request()` instead of `client.build_request()`
I expected timeout tests for the non-async client too. But since there are only async tests I didn't create a non-async test.
I didn't think a documentation change was needed since this is (for me) the expect behavior.
> Fix client.send() timeout when used with a new Request instance

- httpx/_client.py
A couple of the documentation links in httpx/_client.py docstrings were out of date and led to 404's:
https://www.python-httpx.org/advanced/#request-instances
https://www.python-httpx.org/advanced/#merging-of-configuration
These have been updated to:
https://www.python-httpx.org/advanced/clients/#request-instances
https://www.python-httpx.org/advanced/clients/#merging-of-configuration
I hope this doesn't require a prior discussion 😄
> Docs: fix 404ing /advanced/#<anchor> links -> /advanced/clients/#<anchor>

- CHANGELOG.md
- docs/contributing.md
Similarly to https://github.com/encode/httpx/pull/3123, some links to the /advanced/ section of the docs were out of date.
There is also one instance of link text changing from `Writing custom transports` -> `Custom transports` to match the section header.
There is an outstanding broken link in README.md that I wasn't sure about, maybe it should point to https://www.python-httpx.org/advanced/transports/#wsgi-transport?
```
[. . .] directly to [WSGI applications](https://www.python-httpx.org/advanced/#calling-into-python-web-apps) or [. . .]
```
> Fix broken links in docs/contributing.md and CHANGELOG.md

- docs/api.md
Update `URL.__init__()` signature in the API documentation.
Since version 0.14.0 (August 7th, 2020), via #1073, the `allow_relative` parameter is no longer supported. I removed it and left `**kwargs`. Let me know if you prefer to display the allowed `kwargs` instead.
> Update URL.__init__ signature in API docs

- README.md
- docs/advanced/proxies.md
- docs/contributing.md
- docs/http2.md
- docs/index.md
This fix would reduce typing when copying cli codes from the docs. Now you can just click the copy button then without any modify to paste to your cli.
For example, if the cli code comes with a $, when I copied it I need remove the leading $ in my cli.
The normal code blocks are not changed. :)
Hope this could improve the experience.
> Removed leading $ from cli code blocks

- httpx/_urlparse.py
Return early for cases where there are no `.` or `..` components in the path.
> Fast path returns for normalize_path cases

- httpx/_api.py
- httpx/_client.py
- httpx/_config.py
- httpx/_types.py
- httpx/_urls.py
Refs https://github.com/encode/httpx/issues/3176#issuecomment-2068231852
Our public methods currently include a shortcut type `URLTypes`, which is not public API.
This refactoring removes the shortcut type in favor of explicit typing.
There are also other similar cases, tho one this is an easy refactoring to demonstrate.
> Clean up URL signature.

- CHANGELOG.md
- httpx/_urlparse.py
- tests/models/test_url.py
Prompted by https://github.com/encode/httpx/discussions/3248.
*before*...
```python
>>> httpx.get("https://www.example.com\n")
...
File "/Users/tomchristie/GitHub/encode/httpx/httpx/_urlparse.py", line 163, in urlparse
raise InvalidURL(error)
httpx.InvalidURL: Invalid non-printable ASCII character in URL.
```
*after*...
```python
>>> httpx.get("https://www.example.com\n")
...
File "/Users/tomchristie/GitHub/encode/httpx/httpx/_urlparse.py", line 168, in urlparse
raise InvalidURL(error)
httpx.InvalidURL: Invalid non-printable ASCII character in URL, '\n' at position 23.
```
> Improve InvalidURL error message.

- CHANGELOG.md
- httpx/__version__.py
As suggested in https://github.com/encode/httpx/pull/3139#issuecomment-2299677531
* Support for `zstd` content decoding using the python `zstandard` package is added. Installable using `httpx[zstd]`. (#3139)
* Improved error messaging for `InvalidURL` exceptions. (#3250)
* Fix `app` type signature in `ASGITransport`. (#3109)
> Version 0.27.1

- CHANGELOG.md
- httpx/__version__.py
- httpx/_types.py
See https://github.com/encode/httpx/discussions/3287.
I guess we want to roll a minor point release based on this.
> Reintroduce `URLTypes`.

- .github/workflows/test-suite.yml
- CHANGELOG.md
- httpx/_client.py
- tests/test_asgi.py
- tests/test_wsgi.py
This pull request deals with removing the already deprecated `app=...` parameter, which has been dropped in favor of the more explicit `transport = httpx.WSGITransport(...)` and `transport = httpx.ASGITransport()` configurations.
Related: #3314
> Remove deprecated 'app' parameter.

- CHANGELOG.md
- httpx/_transports/asgi.py
- httpx/_utils.py
- pyproject.toml
Prompted by https://github.com/encode/httpx/pull/2858#pullrequestreview-2332409048, thanks @T-256.
This is a more constrained part of #2858. I'll follow up with the remainder of that PR seperately.
Removes the `sniffio` requirement.
* Where async detection is used in `ASGI` we can use a lazy optional import.
* Usage in the `_utils` is overkill. The async implements just use `time.perf_counter()` anyway so let's switch to that.
> Drop `sniffio` requirement.

- docs/advanced/ssl.md
- httpx/_client.py
- httpx/_compat.py
- httpx/_config.py
- httpx/_transports/default.py
- httpx/_types.py
- tests/test_config.py
- tests/test_utils.py
This PR follows up on #3022, and...
* Drops the overloaded style of `verify=str`, in favor of the existing `.load_verify_locations(...)` API.
* Drops the `cert` parameter, in favor of the existing `.load_cert_chain(...)` API.
* Simplifies the internal `SSLContext` setup [in line with stdlib](https://github.com/python/cpython/blob/8b9a8e0e082f849f6db03b2ed9074a86813b3b77/Lib/ssl.py#L735-L757).
* Removes the certificate debug logging, which was odd as the single debug case in `httpx` and which is defunct now that we're using a more explicit style.
At this point we have a nice simple `httpx.SSLContext(verify: bool)` API, with an uncomplicated implementation.
We do also still need to include release notes / migration / rationale, hopefully clear to all why this is an improvement over the …
> Drop overloaded usage of 'verify' and 'cert'.

- httpx/_client.py
- httpx/_utils.py
More internal refactorings, keeping that codebase clean & sharp.
> Cleanup `response.elapsed` implementation.

- httpx/_client.py
- httpx/_content.py
With httpx==0.27.0, I'm getting deprecation warnings like:
```python
/Users/hugo/my-project/.tox/py312/.venv/lib/python3.12/site-packages/httpx/_client.py:680: DeprecationWarning: The 'app' shortcut is now deprecated. Use the explicit style 'transport=WSGITransport(app=...)' instead.
warnings.warn(message, DeprecationWarning)
-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
```
This points to where the deprecated code is in HTTPX and isn't actionable for me.
Instead, if would be more helpful to point to where the deprecated code is being called _from_, so I can fix my code (or report to the library).
Adding `stacklevel=2` gives:
```python
/Users/hugo/my-project/.tox/py312/.venv/lib/python3.12/site-packages/litestar/testing/client/sync_client.py:77: …
```
> Warn with `stacklevel=2` to show caller of deprecation

- docs/compatibility.md
Typo in documentation about reading a response and updating a request field.
> typo: Reading a response expose response text, not request text

- docs/advanced/transports.md
Closes #3349 
Just a minor documentation fix referring to the non-existent `httpx.Mounts`
We also have some undocumented attributes and need to tidy up the API documentation. I believe this will be addressed within the scope of #3091
> Docs minor fix

- httpx/_models.py
Just a sharp lil' bit of refactoring.
> Concise URL instantiation.

- httpx/__init__.py
- httpx/_api.py
- httpx/_client.py
- httpx/_config.py
- httpx/_transports/default.py
This pull requests *retains but deprecates* the `verify=<...>` and `cert=<...>` parameters, and the `httpx.create_ssl_context()` helper function.
* `verify=<...>` becomes deprecated. Use `ssl_context = httpx.SSLContext()` instead.
* `cert=<...>` becomes deprecated. Use `ssl_context = httpx.SSLContext()` instead.
* `create_ssl_context()` becomes deprecated. Use `ssl_context = httpx.SSLContext()` instead.
The `SSL_CERT_FILE` and `SSL_CERT_DIR` environment variables are no longer supported by default.
I think this probably gets the branch to a point where we could release a 0.28 version introducing the deprecation gradually.
Thoughts?
> Allow deprecated `verify=<...>` and `cert=<...>`.

- httpx/_urlparse.py
- tests/models/test_url.py
Review and update which characters should be percent escaped when parsing & normalising URLs.
Based on the URL living standard... https://url.spec.whatwg.org/
Prompted by https://github.com/encode/httpx/discussions/3360
> Review URL percent escaping sets, from whatwg.

- httpx/_urls.py
- tests/models/test_url.py
Don't try to be clever about which `safe=...` characters to use when calling `urlescape()`.
> Just use default `safe=...` characters for `urlescape`

- tests/client/test_auth.py
This test case issues a warning on 3.11+
```
tests/client/test_auth.py:273: netrc files without a password are invalid with Python < 3.11
```
Let's just tidy this case up completely.
> Cleanup unneccessary test case

- httpx/_models.py
- httpx/_utils.py
Issue: #3381
This PR refactors  the `normalize_header_key` as an inline method and moves `normalize_header_value` function to _models.py from _utils.py.
> Move normalize header functions from _utils.py to _models.py

- httpx/_models.py
- httpx/_utils.py
- scripts/lint
- tests/models/test_headers.py
- tests/test_utils.py
Related issue: #3381
This PR moves the following remaining utility functions from `_utils.py` to `_models.py` that are only used in `_models.py` (except `to_bytes_or_str`):
* `is_known_encoding`
* `parse_header_links`
* `parse_content_type_charset`
* `obfuscate_sensitive_headers`
Related tests are also moved accordingly, i.e. from `tests/test_utils.py` to `tests/models/test_headers.py`.
---
Additionally, this PR fixes the script `scripts/lint` by using `ruff check` due to the following error:
```
error: `ruff <path>` has been removed. Use `ruff check <path>` instead.
```
> Move remaining utility functions from _utils.py to _models.py 

- CHANGELOG.md
- docs/advanced/ssl.md
- docs/contributing.md
- httpx/__init__.py
- httpx/_api.py
- httpx/_client.py
- httpx/_config.py
- httpx/_main.py
- httpx/_transports/default.py
- httpx/_urls.py
- tests/test_config.py
Suggested upgrade path for an upcoming 0.28 release...
We *do* have some backwards incompatible changes that we want to issue, but clearly need to minimise disruption to our userbase. Here's what we're currently looking at...
---
The 0.28 release includes a limited set of backwards incompatible changes.
SSL configuration has been significantly simplified.
* The `verify` argument no longer accepts string arguments for custom verify paths.
* The `cert` argument has now been removed.
* The `SSL_CERT_FILE` and `SSL_CERT_DIR` environment variables are no longer automatically used.
For users of the standard `verify=True` or `verify=False` cases this should require no changes.
For information on configuring more complex SSL cases, please see the [SSL …
> Graceful upgrade path for 0.28.

- httpx/_client.py
- httpx/_utils.py
- tests/client/test_headers.py
- tests/test_utils.py
Related issue: #3381
This PR moves the following remaining utility functions from `_utils.py` to `_client.py` that are only used in `_client.py`:
* `port_or_default`
* `same_origin`
* `is_https_redirect`
Related tests are also moved accordingly (to `tests/client/test_headers.py`)
> Move utility functions from _utils.py to _client.py

- httpx/_client.py
Updating deprecated docstring Client() class. Keyword param "proxies" is no longer used and supported, but it was still "optional" by the docstring of the class. That docstring is now updated to avoid developers on passing deprecated params.
> Updating deprecated docstring Client() class

- CHANGELOG.md
- tests/models/test_requests.py
> Add test for request params behavior changes (#3364)

- CHANGELOG.md
- httpx/_config.py
Fix for the case where `verify=False` and client-side certs are being used.
Refs #3441.
> Fix `verify=False`, `cert=...` case.

- CHANGELOG.md
- httpx/__version__.py
* Fix SSL case where `verify=False` together with client side certificates.
---
Release draft... (maintainers) https://github.com/encode/httpx/releases/tag/untagged-cd33408902cf0089b895
> Version 0.28.1

- .github/workflows/test-suite.yml
- pyproject.toml
Python 3.13 was released in October:
* https://devguide.python.org/versions/
* https://peps.python.org/pep-0719/
Let's add it to the CI and classifiers.
Python 3.8 went EOL at the same time, shall we drop support for that too?
> Add support for Python 3.13

- docs/advanced/clients.md
- docs/quickstart.md
While reading the docs for multipart file uploads, I wrongly assumed `httpx` will take care of closing the uploaded files because it was not done manually in the examples. Of course, I understand that the docs never stated this and closing files is usually a caller's responsibility, but I think it's still a good idea to make the examples more practical and less prone to confusion.
> docs: Use `with` to open files in multipart examples

- docs/api.md
Documentation of httpx does not mention the parameters of `httpx.Proxy()`. They can be important e.g. in the case of custom `ssl_context`. This PR documents them in the API Reference.
> Docs: Add `httpx.Proxy` to api.md

- docs/third_party_packages.md
[httpx-retries](https://github.com/will-ockmore/httpx-retries) is a third-party package which implements request retry. 
There's been extensive discussion on this feature in https://github.com/encode/httpx/issues/108 - take a look at the end of the thread (specifically, the [recent comment I left](https://github.com/encode/httpx/issues/108)) for the current state of play.
I've added the package to the third-party packages docs; I've also sorted the entries alphabetically, as there's quite a few, to make it easier to browse (if this is an undesired change, let me know, I'll revert it!). I've run the docs locally, to verify everything looks good.
> Add httpx-retries to third party packages docs

- httpx/_exceptions.py
- httpx/_urls.py
- requirements.txt
- tests/test_content.py
Unblocks #3648 which is currently failing on the command [`ruff format`](https://docs.astral.sh/ruff/formatter).
* #3648 
* https://github.com/astral-sh/ruff/releases
> Upgrade Python formatter ruff
