- httpcore/__init__.py
- httpcore/compat.py
- httpcore/pool.py
- tests/conftest.py
- tests/test_timeouts.py
> Add PoolTimeout, and timeout tests

- httpcore/exceptions.py
- httpcore/models.py
- tests/conftest.py
- tests/test_client.py
> Add `raise_for_status()` to API

- httpcore/decoders.py
As [suggested](https://github.com/encode/httpcore/pull/54/commits/9c3c3ddb2bf3b8565f77f01931ee95cb09dc181d#r283245393)
> Exclude decoder's flush try..except from coverage

- scripts/test
- tests/conftest.py
- tests/test_config.py
Split from #54 working towards #26
> Test config

- httpcore/models.py
- tests/models/test_requests.py
- tests/models/test_url.py
Increasing the test coverage #26 ever so slightly.
> Include URL.__hash__ in test

- httpcore/dispatch/connection_pool.py
- httpcore/models.py
- tests/client/test_auth.py
- tests/conftest.py
> Drop unused interface on ConnectionStore

- httpcore/concurrency.py
- scripts/test
- tests/test_timeouts.py
> 100% test coverage

- README.md
- httpcore/__init__.py
- httpcore/api.py
- tests/test_api.py
Added `httpcore.get(url, **options)`, and pals.
> Add top-level API

- http3/client.py
Any intermediate redirect responses should be closed.
> Close redirect responses

- http3/dispatch/http11.py
> Improve HTTP protocol detection

- http3/dispatch/connection_pool.py
- http3/dispatch/http11.py
- http3/dispatch/http2.py
- http3/exceptions.py
- setup.py
- tests/dispatch/test_http2.py
- tests/dispatch/utils.py
> Check for connection aliveness on pool re-acquiry

- httpx/decoders.py
I tested separately with each libraries and the unit-tests were passing !
> Added Support for both brotli libraries

- httpx/client.py
- httpx/models.py
- requirements.txt
- scripts/lint
- tests/dispatch/test_connection_pools.py
- tests/models/test_responses.py
- tests/models/test_url.py
- tests/test_multipart.py
I've made a few little changes that I think will be useful.
> added flake8 plugins.

- README.md
- docs/contributing.md
This adds a more comprehensive guide covering the nox functions
and also contributions other than coding
> Update contributing guide

- CHANGELOG.md
- MANIFEST.in
- httpx/__version__.py
- setup.py
> Release 0.7.1

- httpx/dispatch/connection_pool.py
- tests/dispatch/test_connection_pools.py
> Release semaphore if connection is dropped

- httpx/decoders.py
- tests/test_decoders.py
> added control to calling decode for empty contents.

- docs/api.md
- docs/index.md
- httpx/client.py
- httpx/dispatch/asgi.py
- httpx/dispatch/http11.py
- httpx/dispatch/http2.py
- httpx/dispatch/threaded.py
- httpx/dispatch/wsgi.py
- httpx/models.py
- tests/client/test_async_client.py
- tests/client/test_client.py
> Response.protocol -> Response.http_version

- httpx/__init__.py
- httpx/concurrency/asyncio.py
- httpx/dispatch/connection.py
- httpx/interfaces.py
- tests/dispatch/utils.py
> Drop Protocol str enum class in favor of plain old strings

- CHANGELOG.md
- httpx/__version__.py
- setup.py
Trying to get our release schedule to at least once a week for minor releases.
> Release 0.7.2

- tests/client/test_async_client.py
- tests/client/test_client.py
- tests/conftest.py
- tests/dispatch/test_connection_pools.py
- tests/dispatch/test_connections.py
- tests/test_api.py
- tests/test_concurrency.py
- tests/test_timeouts.py
- tests/test_utils.py
> Add server.url property in tests

- tests/models/test_url.py
Bringing coverage back to 100%
This PR may or may not have been triggered by my OCD 😄
> Add test for origin from URL string

- httpx/concurrency/asyncio.py
- httpx/config.py
> Drop NPN support

- tests/client/test_auth.py
@sethmlarson mentioned them in the review so I thought I'd add them.
https://github.com/encode/httpx/pull/332/files/cc0fd23223c215baffc0c5fbfd74aab9530b2bd0#r322686809
https://github.com/encode/httpx/pull/332/files/cc0fd23223c215baffc0c5fbfd74aab9530b2bd0#r322685183
> Additional digest auth tests

- docs/async.md
> Document + recommend async with syntax for AsyncClient

- tests/dispatch/utils.py
Refs https://github.com/encode/httpx/pull/339#issuecomment-531601806
> Fix remaining references to BaseStream in tests

- tests/conftest.py
- tests/dispatch/test_connections.py
- tests/test_config.py
> Use a certificate issued from the trustme CA in tests

- CHANGELOG.md
- httpx/__version__.py
Fixes #359 
I experimented with [keepachangelog](https://keepachangelog.com/en/1.0.0/)-inspired categories. Been using them in changelogs for various projects and I think they're really useful to capture the different types of changes. Let me know if that plays nice here!
> Release 0.7.3

- docs/contributing.md
- scripts/publish
Fixes #313
I may update this again once 0.7.3 is fully released. :)
> Document release process

- httpx/config.py
This helped me with debugging #377, would be a good addition for users as well.
> Add debug logging to SSLConfig

- setup.py
- test-requirements.txt
Prompted by https://github.com/encode/httpx/pull/387
> Remove trio pip extra

- httpx/api.py
I deleted the wrong parameters in #408 . Sorry about that!
> Fix wrongly deleted params introduced #408

- docs/async.md
- docs/quickstart.md
Found some small issues while browsing the docs, this PR fixes them.
> Fix broken docs

- docs/advanced.md
- docs/compatibility.md
> Add requests.Session compatibility docs

- docs/advanced.md
> Fix some grammar in Advanced docs

- docs/contributing.md
- mkdocs.yml
- noxfile.py
Prompted by https://github.com/encode/httpx/pull/451#issuecomment-538735714
> Make nox always reuse virtualenvs by default

- .travis.yml
as per comment in #402 , separated PR for win32 tests in Travis
> Added win32 to the build matrix

- docs/advanced.md
- httpx/client.py
- httpx/utils.py
- tests/test_utils.py
Closes #384 
previous:
After lru_cache:
> added lru cache for get_netrc_login function

- docs/advanced.md
- docs/index.md
- httpx/api.py
Closes https://github.com/encode/httpx/issues/480
> Drop proxies arg from the high level API

- docs/advanced.md
> Document client-level configuration

- CHANGELOG.md
- httpx/__version__.py
We mostly have a few tweaks here and there, but it's been some time since 0.7.5 was released so I figured it was time to wipe the slate clean. :-)
> Release 0.7.6

- httpx/multipart.py
> Stringify the given file name

- httpx/dispatch/asgi.py
Simplify the ASGI dispatch implementation.
Doesn't stream responses, but also we get to drop all the background manager gumpf.
> Simplify ASGI dispatch

- httpx/concurrency/asyncio.py
- httpx/concurrency/base.py
- httpx/concurrency/trio.py
- httpx/config.py
- httpx/dispatch/connection_pool.py
- httpx/dispatch/proxy_http.py
- tests/test_config.py
- tests/test_timeouts.py
> Pool timeouts should be on the TimeoutConfig, not PoolLimits

- docs/advanced.md
> Link to ASGI docs

- httpx/dispatch/http11.py
As mentioned in https://github.com/encode/httpx/issues/565#issuecomment-559798817, sending the request and receiving the response concurrently is not necessary for HTTP/1.1
> Don't use background task in HTTP/1.1 dispatcher

- docs/index.md
> Alpha note, and recommendations on pinning versions

- httpx/dispatch/http11.py
- httpx/dispatch/http2.py
- httpx/dispatch/proxy_http.py
Renamed the `BaseSocketStream` attribtues on `H11Connection` and `H2Connection` instances from `connection.stream` to `connection.socket`.
I think `self.socket.write(...)` is more clearly a "we're really about to do some I/O operation" than `self.stream.write(...)`, so I'm happy with how this looks.
More importantly tho' we really *really* ought to have a clearer HTTP/2 implementation with an `HTTP2Stream` instance for each HTTP/2 stream. We'll want the connection class to hold a `.streams` dictionary, mapping stream IDs onto `HTTP2Stream` instances.
Making this isolated change here & now, because it's a tiny step in that direction.
Not a user facing change, so won't make the CHANGELOG.
> Rename BaseSocketStream attributes on connections. 

- httpx/concurrency/base.py
- httpx/concurrency/trio.py
> Cleanup comments on handling MultiError

- httpx/concurrency/asyncio.py
Pull `backport_start_tls` into a standalone function, and `pragma: nocover` it.
> Tweak backport_start_tls implementation, and add 'nocover'.

- httpx/concurrency/asyncio.py
- httpx/concurrency/auto.py
- httpx/concurrency/base.py
- httpx/concurrency/trio.py
- httpx/dispatch/connection_pool.py
Small refactoring of `BasePoolSemaphore` / `Backend.get_semaphore()`
> Refactor `get_semaphore()`

- docs/compatibility.md
> Typo tweak

- httpx/dispatch/http2.py
> Disable HTTP/2 strict header validation

- httpx/models.py
- tests/models/test_url.py
> `params=...` argument on URL should merge, not replace.

- httpx/dispatch/http2.py
Work based on https://github.com/encode/httpx/issues/236#issuecomment-526995883
> To get a response we need to not send an empty DATA frame with end_stream=True, we need to have the end_stream=True on the HEADERS frame.
Rather than any extra API on the ContentStream implementation, we're [just checking the request headers to determine if there's any body to send](https://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html#sec4.3).
> The presence of a message-body in a request is signaled by the inclusion of a Content-Length or Transfer-Encoding header field in the request's message-headers.
* Don't include `Transfer-Encoding` header on HTTP/2 requests, since the protocol deals with body framing.
* For no-body requests, send `end_stream` on the headers, not on an empty body.
Closes #236 …
> Gracefully end_stream early on no-body requests.

- docs/api.md
- docs/compatibility.md
- docs/quickstart.md
- httpx/client.py
- httpx/dispatch/proxy_http.py
- httpx/models.py
- tests/client/test_async_client.py
- tests/client/test_client.py
- tests/dispatch/test_connection_pools.py
- tests/dispatch/test_connections.py
- tests/dispatch/test_proxy_http.py
- tests/models/test_responses.py
- tests/test_api.py
- tests/test_decoders.py
> Rename 'read/close' to 'aread/aclose' on Response

- docs/advanced.md
- docs/api.md
- httpx/client.py
> Rename 'close' to 'aclose' on Client

- httpx/dispatch/connection_pool.py
- tests/dispatch/test_connection_pools.py
> Release max_connections for keepalive connections when closing the connection pool

- httpx/client.py
- httpx/dispatch/asgi.py
- httpx/dispatch/base.py
- httpx/dispatch/connection.py
- httpx/dispatch/connection_pool.py
- httpx/models.py
- tests/client/test_auth.py
- tests/client/test_cookies.py
- tests/client/test_headers.py
- tests/client/test_proxies.py
- tests/client/test_queryparams.py
- tests/client/test_redirects.py
- tests/test_multipart.py
Refactoring for re-introducing the sync API.
> Dispatcher -> AsyncDispatcher

- docs/async.md
> Small typo fix in async.md

- README.md
- docs/index.md
A way to ensure newcomers are immediately exposed to the built-in async support provided by HTTPX. :-)
> Add an async example to intro snippets

- httpx/_api.py
Fixes https://github.com/encode/httpx/issues/831
Should've been removed as part of https://github.com/encode/httpx/pull/485
> Remove proxies from Request docstring

- CHANGELOG.md
Version 0.12 was released March 9th, 2020.
> Fix CHANGELOG date

- .github/workflows/publish.yml
- .github/workflows/test-suite.yml
- scripts/build
- scripts/publish
Publish to PyPI and docs deploys triggered by tagging a release in GitHub.
See also https://github.com/encode/httpcore/pull/62
> Publish workflow

- httpx/_client.py
Missing line to actually fix https://github.com/encode/httpx/issues/873
> Pass http2 flag to proxy dispatch

- docs/advanced.md
- httpx/_config.py
Closes https://github.com/encode/httpx/issues/926 and https://github.com/encode/httpx/issues/787
> Document pool_limits and SSL context on verify

- README.md
- docs/advanced.md
- docs/index.md
> Update dependencies in docs

- docs/advanced.md
Quick cleanup for #857 - had the question in the chat earlier today, and it turned out we were not mentioning yet that streaming uploads were built in.
> Add note on streaming uploads

- docs/advanced.md
- docs/quickstart.md
Prompted by https://github.com/encode/httpx/issues/11#issuecomment-644249424 cc @librehat
> Add note on data fields in multipart form encoding

- tests/client/test_async_client.py
- tests/client/test_client.py
Follow up to #1073.
I marked the conversation as resolved without having realised that I hadn't yet committed this follow up.
Thanks so much for the thorough reviews! ✨
> Parameterise invalid URL tests

- httpx/_client.py
- tests/client/test_properties.py
> Add `Client.timeout` property.

- httpx/_models.py
Minor bit of tidying up around how we use `rfc3986`
> Minor rfc3986 refactoring

- httpx/_client.py
- httpx/_exceptions.py
- httpx/_models.py
- tests/client/test_redirects.py
- tests/models/test_url.py
- tests/test_api.py
> Map rfc3986 exceptions

- httpx/_models.py
- tests/models/test_requests.py
> Ignore transfer-encoding if content-length presents

- docs/advanced.md
- docs/exceptions.md
Minor fix here.
Realised we didn't include this along with #1163
> Include invalid url exception in docs

- tests/client/test_redirects.py
Cleanup for #1183 
Adds a test to verify that redirects are on by default for HEAD requests.
> Add test for HEAD redirect behavior

- docs/advanced.md
> Document Unix Domain Socket usage

- docs/api.md
- httpx/_api.py
- httpx/_client.py
Closes #1154
Add a docstring for `stream()`, and update `docs/api.md`.
> Add stream docstring

- tests/client/test_client.py
- tests/client/test_properties.py
- tests/client/test_queryparams.py
- tests/client/test_redirects.py
Hi folks, I saw #1228 and I created this pull request. I hope it's ok 😄 
Fixes #1228
> Replace httpx.URL for str in tests

- CHANGELOG.md
- httpx/__version__.py
I think it's worth us rolling a minor release now, and then after that we can start to merge in some of the outstanding feature PRs into the `master` branch, eg...
#1197 - Currently waiting to merge, because it'll require a proper version bump.
#1182 - Currently waiting to merge, because it'll require a proper version bump.
#1217 - Major feature
#1196 - Major feature
#1246 - Major feature
---
* `http.Response()` may now be instantiated without a `request=...` parameter. Useful for some unit testing cases. (Pull #1238)
* Add `103 Early Hints` and `425 Too Early` status codes. (Pull #1244)
* `DigestAuth` now handles responses that include multiple 'WWW-Authenticate' headers. (Pull #1240)
* Call into transport `__enter__`/`__exit__` or `__aenter__`/`__aexit__` when client is used in a …
> Version 0.14.3

- tests/models/test_cookies.py
I found that one of the tests started to fail
It was `test_multiple_set_cookie`, the reason was the cookie expiration (on 2020-09-08). I updated expiration date to 2029
> Fixed test_multiple_set_cookie

- httpx/_content_streams.py
Prompted by [a lovely little observation](https://github.com/encode/httpx/pull/1265/files#r486924364) by @JayH5 👍
> Refactor to use `isinstance(..., typing.Iterator)`

- httpx/_client.py
> Fix response.elapsed

- tests/client/test_auth.py
Minor refactor in a test case that was causing a warning.
> Fix warning test case

- httpx/_auth.py
Plus order consistency because why not..
> Small namedtuple refactor

- CHANGELOG.md
- httpx/__version__.py
* Add `response.next_request` (Pull ##1334)
> Version 0.15.5

- docs/async.md
TypeError is occured.
```
TypeError: hello() takes 0 positional arguments but 1 was given
```
> fix code example, in async.md

- httpx/_models.py
- httpx/_status_codes.py
> Drop NBSP characters

- docs/advanced.md
A tiny little PR for some improvements I could see to our advanced timeout docs. :-)
> Tweak advanced timeouts docs

- docs/exceptions.md
> Update exceptions.md for spelling mistake

- docs/environment_variables.md
- httpx/_status_codes.py
Tiny aesthetic nitpick that's also consistent with the rest of the file
Edit: Unrelated mypy error had to be ignored, not sure what's happening there but looks like a change in mypy
> Fix doc capitalization

- docs/api.md
> fix-1457: URL's full_path -> raw_path from pull #1285 in docs as well

- httpx/_multipart.py
- tests/test_multipart.py
Closes #1482
Based on #1484. (Thanks @j178!)
> Fix Content-Length for unicode file contents with multipart

- httpx/_client.py
Only call into `.close()` on a client instance if it is garbage collected in the `OPENED` state.
This seems a self-evident improvement to me, since it now properly mirrors the async case.
Also:
* Extra comments on `UNOPENED`, `OPENED`, `CLOSED`
* Extra comments on `AsyncClient.__del__`
> Neater close logic

- .github/ISSUE_TEMPLATE/1-issue.md
- .github/ISSUE_TEMPLATE/config.yml
> Tweak issue config.yml

- docs/advanced.md
Closes https://github.com/encode/httpx/issues/1224
> Added docs for using client-side ssl certificates

- docs/advanced.md
* Be more specific about when the hooks are called
* Explicitly mention and demonstrate that hooks are allowed to modify requests
See https://github.com/encode/httpx/discussions/1637
> docs: slightly clarify event hooks

- requirements.txt
> ➕ Add types-certifi to satisfy mypy 0.902

- .github/PULL_REQUEST_TEMPLATE.md
Small typo on the PR template.
> ✏️ Update PULL_REQUEST_TEMPLATE.md

- docs/async.md
> [Docs] Add AnyIO under "Supported async environments"

- docs/third_party_packages.md
> Add httpx-caching

- .github/workflows/test-suite.yml
- setup.py
> Test under Python 3.10.0-beta.3

- httpx/_core/_async/connection_pool.py
- httpx/_core/_sync/connection_pool.py
- httpx/_core/base.py
- httpx/_transports/default.py
- tests/test_exceptions.py
> Wire up HTTPTransport

- httpx/_config.py
- httpx/_transports/default.py
- tests/test_config.py
Discussed in https://github.com/encode/httpx/discussions/1783
> Drop mode argument, 'httpx.Proxy(..., mode=...)'

- CHANGELOG.md
> Fix 0.19.0 release date in CHANGELOG

- httpx/_models.py
- tests/models/test_responses.py
Raised through discussion https://github.com/encode/httpx/discussions/1819
> Fix `iter_bytes` with empty content.

- docs/compatibility.md
Everything stands already in the PR title.
> :pencil: Docs patch following PR #1791 section compatibility.encoding

- httpx/_transports/wsgi.py
- tests/test_wsgi.py
> Close WSGI iterable when WSGIByteStream is closed

- httpx/_compat.py
This PR fixes an issue I encountered due to conditional imports and type checking with pyright.
> Fix conditional imports for pyright

- CHANGELOG.md
- README.md
- docs/index.md
> Version 0.21 release notes

- httpx/_client.py
> Fix typo on _merge_url

- httpx/_main.py
- httpx/_multipart.py
I couldn't find anything to refer in python documentation but I'm pretty sure f-string handle string casting in default.
Also I don't know code refactoring is acceptable or not, I'm reading httpx code and I thought these changes could be useful as a PR
Thanks for this wonderful package
> Tiny refactor on _multipart.py & _main.py

- docs/exceptions.md
> update docs to use StreamClosed instead of old ResponseClosed

- httpx/_main.py
> Fix cli docs --proxies #2124

- setup.py
Allow rich 12.*
No test regression and CLI seems to work.
> Allow rich 12

- httpx/_exceptions.py
> Add `request` getter/setter to `HTTPError`

- docs/advanced.md
This is a tiny documentation change. But this part actually confused me for sometime so maybe worth clarifying.
> Clarify customizing authentication docs

- httpx/_auth.py
> Case insensitive algorithm detection for digest authentication.

- docs/api.md
```
def iter_bytes(
self, chunk_size: typing.Optional[int] = None
) -> typing.Iterator[bytes]:
```
> add `[chunk_size]` for `a?iter_.*` methods

- docs/advanced.md
> Update link to trustme

- requirements.txt
This solves the `mkautodoc` issue.
> Bump `mkdocs` from 1.3.0 to 1.3.1

- httpx/_multipart.py
> Allow tuple or list for multipart values

- README_chinese.md
I read the Chinese version of README, it has a much of grammatical errors and punctuation errors.
Meanwhile, I update it to the latest README file.
(By the way, I'm Chinese.)
> Make chinese README better

- requirements.txt
See also https://github.com/encode/httpcore/pull/590
> Pin importlib-metadata

- mkdocs.yml
Closes #2397 
Hey everyone! This is my first PR here. Please let me know if there's anything I missed. 🙏
> Add dark mode toggle to documentation site

- httpx/_config.py
- httpx/_content.py
- httpx/_status_codes.py
- httpx/_transports/mock.py
- setup.cfg
- tests/test_config.py
- tests/test_content.py
https://github.com/encode/httpx/issues/2436#issuecomment-1312248604
> Remove and dissallow unused type ignores

- httpx/_decoders.py
- httpx/_main.py
- httpx/_models.py
- httpx/_urls.py
- httpx/_utils.py
- setup.cfg
- tests/conftest.py
- tests/test_content.py
> Typing: enable warn_return_any

- setup.cfg
- tests/client/test_async_client.py
- tests/client/test_auth.py
- tests/client/test_client.py
- tests/client/test_redirects.py
- tests/conftest.py
- tests/models/test_requests.py
- tests/models/test_responses.py
- tests/test_api.py
- tests/test_content.py
- tests/test_decoders.py
- tests/test_main.py
- tests/test_wsgi.py
Only the test suite needed adjusting to add type hints.
Part of the work for #2436
> Typing: enable disallow_untyped_calls

- tests/client/test_auth.py
Refs #2492
This isn't *quite* the same as mentioned in #2492, since it's about a *consistent* import style in the case of this module, rather than about avoiding *private* namespace imports.
But it's a similar issue... We're just using `import httpx` everywhere else, so let's do that here too.
> Use consistent import style

- tests/test_content.py
Switch the tests in `test_content.py` to use `httpx.Request(...)` and `httpx.Response(...)` instead of testing an internal function directly.
Refs https://github.com/encode/httpx/issues/2492
> Use httpx public API for 'test_content' tests.

- httpx/_utils.py
- tests/test_multipart.py
> Drop private import of 'format_form_param' from tests

- pyproject.toml
> Bump rich pin to allow version 13

- httpx/_client.py
> set logging request lines to INFO level for async method also

- CHANGELOG.md
- Updates the CHANGELOG with the fix from #2708
- Creates a new `Unreleased` CHANGELOG heading. This name is based on the convention from [Keep a Changelog](https://keepachangelog.com/en/1.0.0/)
> Update changelog with WSGITransport SERVER_PROTOCOL fix

- docs/quickstart.md
This PR fixes a sample in the `quickstart.md`.
> Fix sample in quickstart.md

- CHANGELOG.md
- httpx/_types.py
- pyproject.toml
- requirements.txt
> Change extensions type

- CHANGELOG.md
Version 0.25.1 header needed tidying up.
> Tidy up headers in CHANGELOG.md

- pyproject.toml
This adds `tests` and `requirements.txt` to sdist.
See https://github.com/encode/httpx/discussions/2926#discussioncomment-7472927
> Add tests and requirements.txt to sdist

- tests/test_asgi.py
Tidy up an unnecessary import.
> Tidy up import

- httpx/_config.py
- httpx/_multipart.py
- requirements.txt
> Remove unused type: ignore

- docs/advanced/clients.md
- docs/advanced/proxies.md
- docs/advanced/transports.md
- docs/async.md
- docs/compatibility.md
- docs/environment_variables.md
- docs/index.md
- docs/quickstart.md
- docs/third_party_packages.md
- docs/troubleshooting.md
Fixes references issues caused by #3049
> Fix sections references

- httpx/_compat.py
- httpx/_decoders.py
- httpx/_exceptions.py
- httpx/_transports/default.py
- httpx/_urlparse.py
- pyproject.toml
- tests/client/test_auth.py
- tests/test_auth.py
- tests/test_multipart.py
Needed for https://github.com/encode/httpx/pull/3129
> Fix Ruff v0.3.0 violations

- README.md
- docs/index.md
Fix doc links for making requests directly to WSGI/ASGI apps.
> Fix doc links for making requests directly to WSGI/ASGI apps

- httpx/_transports/asgi.py
Update deprecated use of ASGITransport.
> Update asgi.py docstring

- CHANGELOG.md
Update 0.27.1 notes.
Release draft... https://github.com/encode/httpx/releases/tag/untagged-3c669fedcd6387030abd
> Update CHANGELOG for 0.27.1 release date.

- .github/workflows/test-suite.yml
Enable TestSuite for PRs to version branches.
Thanks to @karpetrosyan for noticing this https://github.com/encode/httpx/pull/3314#issuecomment-2371690887
> Enable TestSuite for PRs to version branches.

- docs/third_party_packages.md
As suggested in https://github.com/encode/httpx/issues/304#issuecomment-1332418303
> Add `httpx-ws` to third party packages.

- httpx/_config.py
> Import ssl on demand

- CHANGELOG.md
Highlight behavioural change to json-on-the-wire.
Refs. #3367
> Sharper CHANGELOG entry.

- src/ahttpx/_parsers.py
- src/ahttpx/_pool.py
- src/ahttpx/_server.py
- src/httpx/_network.py
- src/httpx/_parsers.py
- src/httpx/_pool.py
- src/httpx/_server.py
- tests/test_parsers.py
* Add `HTTPParser.keep_alive`.
* Server... always read request to completion on keep alives.
* `HTTPParser.complete` -> `.reset`
* Close streams on server exit.
* Don't raise `KeyboardException` on server exit.
> Server connection handling.

- src/ahttpx/_parsers.py
- src/ahttpx/_pool.py
- src/ahttpx/_server.py
- src/httpx/_network.py
- src/httpx/_parsers.py
- src/httpx/_pool.py
- src/httpx/_server.py
- tests/test_parsers.py
* `HTTPParser.complete` -> `.reset`.
* Add `HTTPParser.is_keepalive` API.
* Clean exits on `KeyboardInterupt`.
> Connection resets
